### ISSUE TITLE
Option to sort cluster output files by the size of clusters

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#102]
A user requested an option to sort cluster output files (consout, profile and others) by the size of clusters.

**Comment by torognes** [comment]
The option -cluster_sort has been added in the summer branch. It will sort the consout and profiles files by decreasing cluster abundance.

**Comment by frederic-mahe** [comment]
Hi @torognes, what about naming that new option `--clusterout_sort`?

Other options impacting the output contain the tag `out` (e.g., `--msaout`, `--consout`, `--sizeout`). It would make it different from input options like `--cluster_size`. We could start a pattern here, making it easier for users to understand how the role of each option.

What do you think?

**Comment by torognes** [comment]
Agreed. Changed the names to clusterout_sort and clusterout_id.
