### ISSUE TITLE
Missing output in uchime_denovo mode

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#104]
As James V posted on the [vsearch forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/vsearch-forum/GjkTFtYaIvU), the total number of sequences reported in the chimera and non-chimera output files can be less than the number of sequences in the input file.

This is because borderline sequences (`?`) are excluded from both output files.

I suggest the following improvements to the documentation:
```
--chimeras filename
Output chimeric sequences to filename, in fasta format. Borderline sequences (see --uchimeout's 18th field) are not included. Output order may vary when using multiple threads.
--nonchimeras filename
Output non-chimeric sequences to filename, in fasta format. Borderline sequences (see --uchimeout's 18th field) are not included. Output order may vary when using multiple threads.
```
We could also create a `--borderline filename` option to output borderline sequences, thus removing the ambiguity, and somehow warning users about that behavior.
```
--borderline filename
Output borderline sequences to filename, in fasta format. A borderline sequence has a score >= minh, but does not fulfill at least one of this criteria: divergence from the closest parent must be at least mindiv; number of differences in left part segment must be at least mindiffs; number of differences in right part segment must be at least mindiffs. Output order may vary when using multiple threads.
```

**Comment by torognes** [comment]
Good idea. Added to summer branch.
