### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#105]
Change license to dual AGPL + 3-clause BSD license.

**Comment by frederic-mahe** [comment]
That's OK with me.

**Comment by colinbrislawn** [comment]
:clap: Thank you!
This makes the vsearch license friendly with QIIME2.
https://github.com/biocore/qiime/issues/1962

**Comment by wasade** [comment]
This is fantastic news!

cc @rob-knight @gregcaporaso

**Comment by gregcaporaso** [comment]
:fireworks: Great news, thanks for your willingness to change the license!!

**Comment by torognes** [comment]
Actually I think we should rather use a dual license with a choice of either the ordinary GNU GPL version 3 license or the 2-clause BSD license. The ordinary GPL version 3 (not Affero) is more permissive than the current GNU Affero GPL license, and the BSD 2-clause license is more permissive than the BSD 3-clause license.

Since @frederic-mahe and @xflouris have already indicated that they agree I will soon change the notices in the code.

**Comment by colinbrislawn** [comment]
> is more permissive

@torognes Thank you for making great software and letting us do anything with it!
(Except, of course, redistributing its binary or source without reproducing that copyright notice, this list of conditions, or the following disclaimer.)

**Comment by torognes** [comment]
The new license applies to the latest commits in the summer branch.
