### ISSUE TITLE
Replace CityHash by FarmHash or MetroHash?

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#106]
Google has released FarmHash 1.1.0, replacing CityHash.

https://code.google.com/p/farmhash/

Perhaps it is better?

**Comment by frederic-mahe** [comment]
Nice! Authors say it is faster than CityHash in most cases. They also introduced architecture-specific improvements.

**Comment by torognes** [comment]
Or MetroHash?

http://www.jandrewrogers.com/2015/05/27/metrohash/
https://github.com/jandrewrogers/MetroHash

See https://github.com/rurban/smhasher for comparisons.

**Comment by torognes** [comment]
Some tests with dereplication indicated that using Metrohash had little or slightly negative effect on performance.

**Comment by torognes** [comment]
The time used to compute hashes in vsearch is so small that it is negligible in almost all cases. I have performed some test on this. There is no point in trying to improve performance of hashing.
