### ISSUE TITLE
Request regarding abundance labeled output

### ISSUE THREAD

**Issue by walterst** [torognes/vsearch#109]
Hello guys,

This isn't necessarily your responsibility, but I found an issue with dropping in vsearch (with 1.1.3 and 1.1.2) as a replacement for usearch61 with QIIME, in particular the identify_chimeric_seqs.py with method usearch61. In particular, the output of the initial abundance sorted reads do not have the "size=" output, which throws off the parsers in QIIME.

Command being called:
vsearch v1.1.2_osx_x86_64, 8.0GB RAM, 4 cores
usearch61 --maxaccepts 1 --consout /Users/tony/temp_junk/test_vsearch_chimera/sample_seqs.fna_consensus_with_abundance.fasta --usersort --id 0.97 --sizeout --minseqlength 64 --wordlength 8 --uc /Users/tony/temp_junk/test_vsearch_chimera/sample_seqs.fna_consensus_with_abundance.uc --cluster_smallmem /Users/tony/temp_junk/sample_seqs.fna --maxrejects 8 --strand plus --log /Users/tony/temp_junk/test_vsearch_chimera/sample_seqs.fna_smallmem_clustered.log 

Example output fasta label from vsearch
>centroid=1111883;seqs=1;
Example output fasta label from usearch61
>centroid=1111883;seqs=1;size=1;

**Comment by torognes** [comment]
Thanks for the request. Will fix this in upcoming version.

**Comment by torognes** [comment]
Fixed in 1.2.18.
