### ISSUE TITLE
details of msa output

### ISSUE THREAD

**Issue by dereneaton** [torognes/vsearch#110]
Is the `msa` output a true multiple sequence alignment, meaning it performs an all-by-all alignment, or are sequences aligned only relative to the seed? If it's all-by-all, how well does it perform relative to the default options for `muscle`?

**Comment by torognes** [comment]
No, it is just a simple alignment of the seed (centroid) against the other sequences. I seems to work okay if the sequences are not too different, but in general it is probably does not produce very good multiple alignments. But it is fast and simple.
