### ISSUE TITLE
Support xz compressed files

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#115]

**Comment by torognes** [comment]
There is a library here: http://tukaani.org/xz/
However, it seems more difficult to implement than with gzip and bzip2 compressed files because the API does not handle files directly AFAIK.

**Comment by frederic-mahe** [comment]
As discussed in [issue #39](https://github.com/torognes/vsearch/issues/39), the possibility to read for `stdin` would bring support for `xz` indirectly:
```sh
vsearch --fastq_chars <(xzcat file.fastq.xz)
```
`vsearch` would be ready for any present and future compression formats, as long as the shell offers decompression tools. @torognes, I know you know it already, I just wanted to put it in writing for future users.

**Comment by torognes** [comment]
Reading xz compressed files can be achieved using the new support for pipes in version 2.0.0.
