### ISSUE TITLE
Support AVX2

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#119]
Use the libssa library: https://github.com/RonnySoak/libssa

**Comment by torognes** [comment]
Or perhaps [parasail](https://github.com/jeffdaily/parasail)?

**Comment by colinbrislawn** [comment]
👍 for parasail, as it supports proteins alignments as well, to close #42. Also @jeffdaily is nice.

**Comment by frederic-mahe** [comment]
I just finished reading [parasail's paper](http://www.biomedcentral.com/1471-2105/17/81). Indeed, it seems very interesting as it covers local, semi-global and global alignments, nucleotide and amino acids, and is generally fast.

I am not sure that parasail can return backtraces or alignments though (it is planned but not implemented yet). That could be a problem.

**Comment by frederic-mahe** [comment]
Using parasail would also solve issue #16 (accelerate single query vs. single subject, important for clustering). I never tried but with git submodules it seems easy to clone parasail's git repository inside vsearch's.

**Comment by torognes** [comment]
I like the idea of using Parasail, but after considering it a bit I am a bit concerned about the performance. Computing the alignments now accounts for about 80% of the time used for clustering and changes here will have a major impact.

1) One thing is that It seems like there is little to gain from using AVX2 on short sequences. Only sequences longer than 200bp seems to benefit from AVX2. See fig 1b/c in Parasail paper.

2) Another thing is that VSEARCH currently uses the approach as in SWIPE to compare one query against multiple (up to 8) target sequences in parallel (inter-task), while Parasail parallellizes the comparison of one query against one target (intra-task) using e.g the striped algorithm. The SWIPE approach stills seems to be faster if many alignments of one query is required. But if only one alignment is needed, the other approach may be much faster. How this affects VSEARCH depends on how many alignments it is necessary to compute for each query on average, which depends on maxaccepts and maxrejects and more. I'll try to find out how this is likely to play out.

3) Another important thing is that VSEARCH and USEARCH allows particular left terminal, internal and right terminal gap penalties to be specified independently for the query and target sequences. In total 12 different gap penalty parameters may be specified (left/internal/right, query/target, open/extend). By default the terminal gap penalties are lower than the internal gap penalties. Parasail does not seem to support such gap penalties. It is not trivial to add this to Parasail.

**Comment by colinbrislawn** [comment]
1) parasails most consistent improvement is with global alignments, when prefix scan is used. See [Fig 3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4748600/figure/Fig3/). This is a great fit for amplicon search and clustering. Like you said, neither prefix scan or AVX show a consistent improvement in local alignments.

2) Good distinction about parallelization method. Given that vsearch is typically run with maxaccepts and maxrejects >1 , this improvement may be less helpful, even if it solves #16. 

3) Extending support for gap penalties could be a big challenge, and `libssa` does support some (all?) of these.

**Comment by frederic-mahe** [comment]
> 2) Another thing is that VSEARCH currently uses the approach as in SWIPE to compare one query against multiple (up to 8) target sequences in parallel (inter-task), while Parasail parallellizes the comparison of one query against one target (intra-task) using e.g the striped algorithm. The SWIPE approach stills seems to be faster if many alignments of one query is required. 

This is something I was wondering while reading the Parasail paper. Does vsearch perform mostly comparisons that require inter-task or intra-task parallelization? I wasn't sure, but It seems to me that vsearch does mostly inter-task (one-to-many) comparisons. And Torbjørn's approach is still the fastest for this.

Now, the question remains: can Torbjørn's approach benefit from using AVX2 instructions? could it compare a query to 16 sequences at a time instead of 8?

**Comment by frederic-mahe** [comment]
Closing for now. We can always revisit in the future (use the tag PotentialFuture to select these items)

**Comment by frederic-mahe** [comment]
[QuickEd](https://github.com/maxdoblas/QuickEd): High-performance exact sequence alignment based on bound-and-align (2025) [Doblas _et al_.](https://doi.org/10.1093/bioinformatics/btaf112), _Bioinformatics_.

Especially fast for long and noisy sequences (> 10 kb).
