### ISSUE TITLE
sizeorder option

### ISSUE THREAD

**Issue by pschloss** [torognes/vsearch#122]
usearch 6.1 and 7.x have an undocumented option called sizeorder, it is not in version 8.x. I'm wondering how difficult it would be to incorporate into vsearch. This option was used in a recent paper by He et al. () as what they called abundance-based greedy clustering (AGC). From my communications with Edgar and He, 

> The effect of the -sizeorder option is to rank hits by decreasing size=N annotations in the database sequence instead of by decreasing identity (or by increasing E-value for local alignments). ... If you do clustering with -maxaccepts > 1, the effect of -sizeorder is to assign a query sequence to the cluster with highest abundance (size=N value in the label of the centroid sequence) instead of the centroid with highest identity. Regardless, the identity of the query with the centroid must be at least the threshold given by the -id option.

I'm wondering how difficult it would be to incorporate the --sizeorder option into vsearch. In my analyses, vsearch generates clusters that are comparable to the usearch-based AGC, which are actually better than the useach-based DGC. I'm thinking that if there's a vsearch-based AGC, it will be even better. If time is tight, you could point me to where this would go in the source code and I'd be happy to file a pull request.

**Comment by torognes** [comment]
Thanks for the suggestion. I don't think this should be too difficult. I'll look into it in the coming days.

**Comment by torognes** [comment]
I've added this option now. I hope it works as expected.

**Comment by pschloss** [comment]
thanks!
