### ISSUE TITLE
Remove dependency on crypto libraries

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#124]
Insert public domain code for md5 and sha1 to get rid of the dependency of the crypto libraries and their complicated licenses.

**Comment by colinbrislawn** [comment]
[MD5](http://openwall.info/wiki/people/solar/software/public-domain-source-code/md5)

I'm not finding an sha1 implementation which is variantly public domain. [These](https://oauth.googlecode.com/svn/code/c/liboauth/src/sha1.c) [two](http://pushover.sourceforge.net/repos/head/src/sha1.cpp) claim to be.

**Comment by torognes** [comment]
Thanks. I found a public domain SHA1 implementation here that I will use: http://www.ghostscript.com/doc/jbig2dec/sha1.c

**Comment by torognes** [comment]
Fixed in 1.4.1.
