### ISSUE TITLE
realloc() error clustering on v.1.4.1

### ISSUE THREAD

**Issue by ghbio** [torognes/vsearch#126]
Hi, 
I am trying VSEARCH and I want to cluster a 1.7 GB fasta file of protein coding sequences. At the beginning of the run (when reading 26% of the file) I get the following error:  
```Reading file my_file.fasta 26%*** glibc detected *** vsearch: realloc(): invalid next size: 0x0000000001e998b0 ***```  
My command was:
 `vsearch --cluster_fast my_file.fasta -centroids centroids.fasta -id 0.95 --iddef 0 --strand both --uc uc_results.txt`  
I got the same error with the binary file v1.4.1_linux_x86_64 and also with the same version compiled from source on centOS 6.2. I have been able to run the same command successfully with smaller files.
The sequences in my fasta file have a great size variability (average ~400 bp), the maximum sequence length being 15588 bp. Could this error be similar to issue #48?

Thank you very much.
Pablo

**Comment by torognes** [comment]
Thanks you for reporting this bug. I will look into it now.

**Comment by torognes** [comment]
I am unable to reproduce this error with any of my data files. The FASTA parser has changed substantially lately and have perhaps not been tested vigorously enough. Would it be possible for you to send me  the "my_file.fasta" in some way?

**Comment by ghbio** [comment]
Hi and sorry for the delay. I get the same error if I try to `vsearch --cluster_fast` a file with just the three longest sequences of my dataset (the longest of them is 15.5 kbp). A subset of sequences from a `head -300 my_file.fasta` (the file is unsorted) runs fine and doesn't trigger the error. I am sure I can e-mail you both of the files for you to do your tests with them.
Thanks again.

**Comment by torognes** [comment]
Thanks for sending me the files. It runs fine on Mac but crashes on Linux. I'll look further into it.

**Comment by torognes** [comment]
I think I found the problem and solved it. Some misplaced parentheses caused too little memory to be allocated. The new vsearch version 1.4.5 should solve the problem. But please not that vsearch works best with sequences shorter than about 5000bp. Longer sequences will make it much slower.

**Comment by ghbio** [comment]
Thank you very much. It is also working for me now. 
Chhers,
Pablo
