### ISSUE TITLE
Fatal error: Cannot determine amount of RAM with 1.4.2 on OSX 10.8.5

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#127]
I just downloaded the newest vsearch version from the release channel. It returns this error. 

```
$ cd vsearch-1.4.2-osx-x86_64/
$ cd bin/
$ ll
total 568
drwxr-xr-x@ 3 asdf\Domain Users   102B Oct  2 16:00 .
drwxr-xr-x@ 8 asdf\Domain Users   272B Oct  2 16:00 ..
-rwxr-xr-x@ 1 asdf\Domain Users   282K Oct  2 10:57 vsearch
$ ./vsearch 


Fatal error: Cannot determine amount of RAM
```

Let me know how I can to help address this problem.

**Comment by torognes** [comment]
Strange. Does this happen when you compile yourself too, or is it only with the supplied binary? You are using OS X 10.8.5 (Mountain Lion). I just upgraded to OS X 10.11 (El Capitan) on the machine used to compile it on. Maybe there is a difference?

**Comment by torognes** [comment]
Thanks for reporting the issue, @colinbrislawn. I think I have found the problem and tried to fix it in the new release 1.4.3. Can you try it?

**Comment by torognes** [comment]
Oops, try with 1.4.4.

**Comment by colinbrislawn** [comment]
Version 1.4.4 works great, including on `.gz` files.

Thank you for addressing this so quickly!
