### ISSUE TITLE
add --search_exact

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#130]
USEARCHv8 includes the `--search_exact` command.
http://www.drive5.com/usearch/manual/cmd_search_exact.html

> The search_exact command searches for exact, full-length matches to a database sequence. The algorithm is faster than usearch_global, uses less memory, and is guaranteed to find all correct matches, i.e. there are no heuristics.

So it's probably a hash table lookup.

This is not commonly used, but would be helpful in specific cases, like building an abundance table of dereplicated sequences #129

Thank you!
Colin

**Comment by torognes** [comment]
Thank you for this suggestion. This is an easy and useful feature that I will add soon.

**Comment by torognes** [comment]
Added in version 1.8.0.

**Comment by colinbrislawn** [comment]
Thank you! :clap:
