### ISSUE TITLE
release vsearch on anacoda? 

### ISSUE THREAD

**Issue by gregcaporaso** [torognes/vsearch#134]
Would you guys be interested in releasing vsearch on conda, so users could ``conda install vsearch``? This is how we're starting to distribute all of our Python packages, but it supports distribution of software written in other languages as well. For example, some non-Python packages that we're distributing [here](https://anaconda.org/biocore), and the recipes that @RNAer put together for distributing those [here](https://github.com/biocore/conda-recipes). This would help users of our software to install vsearch.

**Comment by colinbrislawn** [comment]
I'm interested in this. @torognes, would you be comfortable with me attempting this or is this something you would rather do, or not do, yourself?

**Comment by torognes** [comment]
@colinbrislawn That's fine, please go ahead!

**Comment by colinbrislawn** [comment]
This can be closed! Issues can be reported at
https://github.com/biocore/conda-recipes/

**Comment by torognes** [comment]
Thanks!
