### ISSUE TITLE
fastq_convert: fastaout does not work on fastq files

### ISSUE THREAD

**Issue by VascoElbrecht** [torognes/vsearch#138]
I am using vsearch v1.8.1_osx_x86_64, 16.0GB RAM, 8 cores. 
I would like to convert a fastq file to fasta with:

vsearch --fastq_convert N_debres_r1.txt -fastaout test.txt

but I get the error;
Fatal error: No output file specified with --fastqout

converting fastq to fastq with the following command works, so i think my files are ok:

vsearch --fastq_convert N_debres_r1.txt -fastqout test.txt #(does work)

Am I missing something here or is this a bug? Thank's guys!

Best
Vasco

**Comment by torognes** [comment]
Hi @VascoElbrecht 

The fastq_convert command is for conversion between different fastq file variants (e.g. phred+33 and phred+64 formats).

To convert a FASTQ file to FASTA, please use the fastq_filter command (without any filtering):

`vsearch --fastq_filter N_debres_r1.txt -fastaout test.txt`

You may need to include the `-fastq_ascii` option if your FASTQ file is in an old variant of the format (phred+64).

- Torbjørn

**Comment by VascoElbrecht** [comment]
Dear Torbjørn,

great! Thank you very much!

Best
Vasco
