### ISSUE TITLE
Manuscript

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#14]
A manuscript describing VSEARCH should be submitted to a preprint journal.

**Comment by colinbrislawn** [comment]
Any updates on this? I have used vsearch as part of a team which is ramping up towards final analysis and publication. I'm uncertain if I should cite your software as 'personal communication', cite your upcoming preprint, or repeat my analysis using USEARCH.

Thank you!

**Comment by meren** [comment]
Of course it doesn't make the need for a pre-print any less urgent (smiley), but in my opinion, it is pretty legitimate to reference GitHub repositories as reference.

Reviewers may ask for some validation, in that case I would simply analyze a small subset of my samples with both to show how comparable the two approaches are.

My 2 cents.

**Comment by torognes** [comment]
The writing is (as usual) going more slowly than anticipated so a preprint and submission is probably still several months away. In the meantime, please cite the [GitHub repo](https://github.com/torognes/vsearch), if possible. Each release actually also has a [DOI](http://en.wikipedia.org/wiki/Digital_object_identifier) on [Zenodo](https://zenodo.org/), if that helps. The current release, version 1.1.3, has doi [10.5281/zenodo.16153](https://dx.doi.org/10.5281/zenodo.16153).

**Comment by colinbrislawn** [comment]
Any updates on this paper? I have had great success using this software, but I just had to avoid it on a project because [Science explicitly disavows unpublished methods](http://www.sciencemag.org/site/feature/contribinfo/prep/gen_info.xhtml#unpublished). 

I want to use and credit your excellent software. I look forward to a manuscript!

**Comment by torognes** [comment]
The vsearch manuscript is now published in PeerJ Preprints: 

Rognes T, Flouri T, Nichols B, Quince C, Mahé F. (2016) VSEARCH: a versatile open source tool for metagenomics. PeerJ Preprints 4:e2409v1 https://doi.org/10.7287/peerj.preprints.2409v1

**Comment by torognes** [comment]
Peer-reviewed manuscript accepted in PeerJ yesterday.

**Comment by torognes** [comment]
The VSEARCH paper was published in PeerJ today!

https://peerj.com/articles/2584/
