### ISSUE TITLE
escape tabs in fasta names writing output with --uc

### ISSUE THREAD

**Issue by ryneches** [torognes/vsearch#140]
If the names of the records read using --cluster_fast contain tabs, the output created by --uc does not escape or quote them. This results in column parsing problems.

`usearch` may have the same behavior, but perhaps this is another case to add to the "Deliberate Changes."

**Comment by torognes** [comment]
Hi @ryneches ! Thanks for your suggestion.

I've checked what usearch does in this case, and it will normally truncate the sequence identifiers in the fasta headers at the first space or tab, unless the `--notrunclabels` option is specfied, in which case the entire line is included.

There is a difference here, as vsearch only truncates at the first space and not at the first tab. That can be considered a bug or incompatibility.

I'll change vsearch to perform similar to usearch in this regard, but I am skeptical to include changes that reduces compatibility.

Using tabs within the identifiers and then using the `--notrunclabels` option to include them is perhaps not a good idea. I think it would be better to escape the tabs or replace the tabs with another character before feeding them into vsearch. Exactly how to escape the tabs may vary and I would rather leave that to the user.

**Comment by ryneches** [comment]
Yeah. The truncation behavior could be even more problematic than failing to escape or quote. 

How about throwing a warning on STDERR when it reads the fasta file (and the user has specified the --uc flag), and suggest either the usearch-like `--notrunclabels`, or some vsearch-specific options. How about, `--quotelabels`, `--replacelabeltabs` and `--escapelabeltabs`?

I know that's a lot of trouble, but that

**Comment by torognes** [comment]
I'll very soon change the behaviour of vsearch in the next release to truncate at the first space or tab by default, similar to usearch. If the `--notrunclabels` option is specified, the entire line will be read.

To include tabs in the identifiers the user will then have to include the rarely used `--notrunclabels` option. If the user does this, and includes tabs in the input and asks for output in a uc file, I think the user knows what he/she is doing. Sorry, but I do not think a warning is necessary.

Do you have a specific use case where intentionally including tabs in the identifier is useful?

The IANA standard for tab-separated value files simply forbids using tabs inside the fields, there is no standard way of escaping them.

I think users should rather use another character for separating values in the first place.

**Comment by ryneches** [comment]
Well, the reason this came up in the first place is that our pipeline for QC, demultiplexing and read merging uses tabs in the record names. A lot of other such tools do as well, and many do not give the user the option to change how records are named.

In my case, I can live without the information following the first tab. I've struggled with so many awful integration bugs that have resulted from incompatible rules imposed on record name formats that I've come around to the policy that it's best to try to respect whatever crazy names the user wants. Ideally, names should be treated as arbitrary markers that pass undigested through the software. I'm sure *someone* has a data set with a record named 啤酒酵母...

**Comment by frederic-mahe** [comment]
> I'll very soon change the behaviour of vsearch in the next release to truncate at the first space or tab by default, similar to usearch. If the --notrunclabels option is specified, the entire line will be read.

This is now covered by a [test](https://github.com/frederic-mahe/vsearch-tests/commit/43828b95ed8b0a5b0b7f55a95d49a303d64809fc) (limited to the command `--cluster_fast`).

A workaround for the "there are tabs in my records" issue would be to make use of vsearch's capacity to read and write streams. One can neutralize tabs in the input just before passing it to vsearch, and re-establish tabs in vsearch's output:
```sh
sed 's/\t/§/' input.fasta | vsearch --cluster_fast - --uc - | sed 's/§/\t/' > output.uc
```
Implementing an option to deal specifically with tabs does not seem a good idea (using tabs in fasta headers is a bad practice to start with). I'll go ahead and close that issue now.
