### ISSUE TITLE
vsearch --fastq_stats doesn't report correct values of AvgEE, Rate and RatePct

### ISSUE THREAD

**Issue by davidealbanese** [torognes/vsearch#145]
In a simple example (see test.fastq) `vsearch --fast_stats` doesn't report correct values (and so they are in disagreement `usearch` results) for AvgEE (Average Expected Errors), Rate (Average Expected Errors/L) and RatePct:

vsearch v1.8.1_osx_x86_64, 8.0GB RAM, 8 cores
vsearch --fastq_stats test.fastq --log stats_vsearch.txt 
```
    L  PctRecs  AvgQ  P(AvgQ)      AvgP  AvgEE       Rate   RatePct
-----  -------  ----  -------  --------  -----  ---------  --------
   ...
   50    50.0%  10.0  0.10000  0.100000   1.01   0.011200    1.120%
   51    50.0%  10.0  0.10000  0.100000   1.11   0.012176    1.218%
   52    50.0%  10.0  0.10000  0.100000   1.21   0.013130    1.313%
   ...
```

usearch_i86osx32 v6.1.544, 4.0Gb RAM (8.6Gb total), 8 cores
usearch61 --fastq_stats test.fastq --log stats_usearch.txt
```
    L  PctRecs  AvgQ  P(AvgQ)      AvgP  AvgEE       Rate   RatePct
-----  -------  ----  -------  --------  -----  ---------  --------
   ...
   50    50.0%  10.0      0.1       0.1   1.00   0.020080    2.008%
   51    50.0%  10.0      0.1       0.1   1.10   0.021647    2.165%
   52    50.0%  10.0      0.1       0.1   1.20   0.023154    2.315%
   ...
```
[test.fastq.txt](https://github.com/torognes/vsearch/files/35305/test.fastq.txt)

**Comment by torognes** [comment]
Thank you for reporting this, @davidealbanese ! I'll look into it. When I developed it I used a much larger set of sequences and obtained similar values as with usearch, but since these parts of usearch are not documented in detail it is difficult to find out exactly how things are computed. Based on your sets of sequences I may be able to find out in more detail what is different.

**Comment by davidealbanese** [comment]
Dear @torognes, thank you for your reply. I noticed a strange behavior on a real dataset, were I found an average expected error much higher than the read length (and by definition EE should be <= read length):
```
    L  PctRecs  AvgQ  P(AvgQ)      AvgP  AvgEE       Rate   RatePct
-----  -------  ----  -------  --------  -----  ---------  --------
...
546     0.0%  25.5  0.00282  0.006975  52265.18   0.017062    1.706%
547     0.0%  18.0  0.01585  0.015849  209060.75   0.017062    1.706%
548     0.0%  18.0  0.01585  0.015849  209060.77   0.017062    1.706%
...
```
Therefore, I tried on a simple (previously attacched) fastq:
```
@1
TGGGGAATATTGCACAATGGGGGGGAACCCTGATGCAGCAATGCCGCGTGATGCCGCGTG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII++++++++++++++++++++
@2
TGGGGAATATTGCACAATGGGGGGGAACCCTGATGCAGCA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@3
TGGGGAATATTGCACAATGGGGGGGAACCCTGATGCAGCA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@4
TGGGGAATATTGCACAATGGGGGGGAACCCTGATGCAGCAATGCCGCGTGATGCCGCGTG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII++++++++++++++++++++
```
where it is easy to see that, for example, for L=50 the average expected error (read 1 and 4 are identical) should be: 
```
[10^(-40/10)x50 + 10^(-10/10)x10] / 50 = 0.02009 and not 0.011200
```
and for L=52:
```
[10^(-40/10)x50 + 10^(-10/10)x12] / 52 = 0.02317 and not 0.013130
```
Let me know if you agree and thank you again.

**Comment by torognes** [comment]
I think it should be 
```
[10^(-40/10)x40 + 10^(-10/10)x10] / 50 = 0.02008 and not 0.011200
```
and
```
[10^(-40/10)x40 + 10^(-10/10)x12] / 52 = 0.02315 and not 0.013130
```
but otherwise I agree. (The first part should be multiplied with 40, not 50.)

I it is not trivial to understand exactly what these values are meant to represent, but I think I get it now. I'll revise vsearch to compute these values correctly.

Thank you again for reporting the problem.

**Comment by davidealbanese** [comment]
Yes, you are right (I'm sorry but I revised the math before your reply). A recent Edgar's paper defines the expected error and I think could help: http://bioinformatics.oxfordjournals.org/content/31/21/3476.full.

Thank you again!

**Comment by torognes** [comment]
This problem should be solved now in version 1.9.2.

**Comment by frederic-mahe** [comment]
@Statistic-Qin the expected error is defined as the sum of error probability for all positions in a sequence: E=∑ipi=∑i10–Qi/10. It is the sum of many [0, 1]-values, so it can be greater than one.

**Comment by Statistic-Qin** [comment]
oh，thanks!  not mean, it's sum.
