### ISSUE TITLE
Error in installing vsearch 1.9.2 from source on OS X 10.8.5

### ISSUE THREAD

**Issue by davidealbanese** [torognes/vsearch#146]
After running `./configure`, the `make` command returns the error:  `vsearch.h:69:23: error: x86intrin.h: No such file or directory`:
```
davide@tesla:~/vsearch-1.9.2$ make
make  all-recursive
Making all in src
g++ -DHAVE_CONFIG_H -I. -I..    -Wall -Wsign-compare -msse2 -g -O2 -MT libcpu_sse2_a-cpu.o -MD -MP -MF .deps/libcpu_sse2_a-cpu.Tpo -c -o libcpu_sse2_a-cpu.o `test -f 'cpu.cc' || echo './'`cpu.cc
In file included from cpu.cc:61:
vsearch.h:69:23: error: x86intrin.h: No such file or directory
cpu.cc: In function ‘void increment_counters_from_bitmap_sse2(short unsigned int*, unsigned char*, unsigned int)’:
cpu.cc:99: error: ‘__m128i’ does not name a type
cpu.cc:102: error: ‘__m128i’ does not name a type
...
```
The complete `./configure` and `make` outputs are in attachment.
[install.txt](https://github.com/torognes/vsearch/files/38799/install.txt)

**Comment by torognes** [comment]
Thanks for reporting this issue. Another user have reported a similar problem. I need some more information to diagnose this problem. Which operating system and version are you compiling on? And what type of cpu do you have?

**Comment by xflouris** [comment]
Hi @davidealbanese , could you paste us the output of `g++ --version` please?

**Comment by torognes** [comment]
Sorry, I just saw in the title that you used OS X 10.8.5.

**Comment by davidealbanese** [comment]
Hi @torognes!
g++ version:
`i686-apple-darwin11-llvm-g++-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)`
proc :  2.3 GHz Intel Core i7
mem: 8 GB 1600 MHz DDR3
grap: NVIDIA GeForce GT 650M 512 MB

**Comment by xflouris** [comment]
The x86intrin.h header has the following copyright header 

`/* Copyright (C) 2008-2014 Free Software Foundation, Inc. */`

GCC 4.2.1 seems to be from 2007 (see [here](https://gcc.gnu.org/gcc-4.2/)). 

@torognes : Perhaps a pre-processor macro for including `emmintrin.h` and `pmmintrin.h` instead of `x86intrin.h` in case GCC version is older than 4.2.4?

**Comment by torognes** [comment]
@xflouris : yes, I'll do that. Seems like x86intrin.h did not appear before gcc 4.5: https://gcc.gnu.org/gcc-4.5/changes.html

**Comment by torognes** [comment]
@davidealbanese Could you try the compiling the new version 1.9.3 that I just released? We now include some other header files (`emmintrin.h` or `tmmintrin.h`) that should be available also with older compiler versions.

**Comment by davidealbanese** [comment]
I'm sorry, I can't. I'm trying to udate XCode and the command line tools... I understand I should've waited for...

**Comment by torognes** [comment]
Okay, I've told the other user that reported the problem about the fix. Perhaps he will try to compile it.
