### ISSUE TITLE
Letter case not preserved

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#147]
A user reported that vsearch and usearch7 does not behave identical regarding the letter case of sequences when mixed case was used in the input. The output from the command below was different from that of usearch7.

`vsearch -cluster_fast in -msaout v.out -qmask none -dbmask none -id 0.96 -self -minsl 0.9 -query_cov 0.9 -target_cov 0.9 -maxaccepts 0 -maxrejects 0 -gapopen 3I/0L`

See details on the VSEARCH Forum: https://groups.google.com/d/msgid/vsearch-forum/c8d34136-2388-4e54-9e74-513f533efada%40googlegroups.com

**Comment by torognes** [comment]
Some initial observations about usearch 7:

1) It seems like cluster_fast ignores all masking options (`-qmask`, `-dbmask`, `-hardmask`). You can write whatever you want as an argument to the first two (`-qmask`, `-dbmask`) without any warning. It always behaves as if `-qmask soft` was in effect. If all input sequences are just lower case there will only be singletons, no clustering.

2) It seems like `-cluster_smallmem` takes `-qmask` into account and ignores `-dbmask` (okay). But it seems like `-qmask none` is equivalent to `-qmask soft`. If `-qmask none` or `-qmask soft` is used with input containing just lower case letters you will get no clustering at all, just singletons. Only the default `-qmask fastnucleo` (or no masking options at all) seems to work in that case.

3) The letter case is never changed in the output.

The manual seems to indicate that all masking options are available for both these clustering commands:
http://drive5.com/usearch/manual7/cluster_fast.html
http://drive5.com/usearch/manual7/cluster_smallmem.html

**Comment by torognes** [comment]
I am not sure about what to do here. We can pass the case of the letters though unmodified, that's no problem. However, the behaviour of usearch regarding masking and clustering is confusing. The actual behaviour seems to be different from the documentation and the defaults are non-standard, as described earlier. I do not know if we should try to be as similar as possible, if we should just ignore masking when clustering alltogether, or if we should try to implement it properly as a user would expect. I guess masking is rarely used intentionally when clustering. Masking is supposed just to matter when extracting indexing words. Any opinions?

**Comment by colinbrislawn** [comment]
I'm not too worried about being slightly different from usearch. Previously, you have chosen to make vsearch different, like to extend functionality (like adding `--relabel` and it's variations to more commands). You have also changed vsearch to improve performance (changing kmer selection and comparison). In the case of kmer selection, you were working with incomplete information and chose the option which worked best, instead of the option which was most similar. I like that approach. 

I've never thought of using masking for clustering. As long as our documentation is correct, I'm happy!

**Comment by nikosdarzentas** [comment]
In general, and in line with @colinbrislawn and even the introductory text of VSEARCH, I would definitely not propagate confusing or plainly wrong behaviour from USEARCH - users will appreciate that, even if they have to modify aspects of their work (unlikely in this case).

Practically then, I'd prefer (for consistency if nothing else, given that there is sequence comparison involved) to have masking available for clustering, but I'd be OK with ignoring it. What I'd definitely expect is for letter case to be preserved, which is the subject of this issue :-)

Thanks.

**Comment by torognes** [comment]
This issue relates to chimera detection and searching as well, both regarding how usearch performs masking and the letter case in the output files. I am working on the issue but I'll need to get an overview how things seem to work and how to best resolve the issue.

**Comment by torognes** [comment]
Just released version 1.9.7 to fix this problem. Sorry for taking so long. Had to investigate the behaviour of usearch under various circumstances and how to best handle upper and lower case, Ns, soft/hard masking etc to decide the best way forward.

If no masking is specified with `--qmask none` and/or `--dbmask none` the letter case of the input sequences are now unchanged in the output files, as requested. The only exception is the output files produced by the `--uchimealns` option where lower case symbols indicate alignment disagreement.

The default is to perform masking with DUST and replace masked regions with lower case letters. These are also shown in the output files.

The masking behaviour should now be as indicated in the manual, which has also been updated a bit.

Some compatibility with usearch is lost and some gained, but I think masking options are now more consistent and understandable.

Masking is performed by the commands for chimera detection, clustering, masking, pairwise alignment and searching.

**Comment by nikosdarzentas** [comment]
Great work, with the necessary attention to detail,
thank you.
