### ISSUE TITLE
Add --fastq_eestats command

### ISSUE THREAD

**Issue by davidealbanese** [torognes/vsearch#148]
Dear @torognes, I'd like to suggest to include the `--fastq_eestats` command (http://www.drive5.com/usearch/manual/cmd_fastq_eestats.html). The output is a fixed tab-delimited text and it reports Qs and EEs in terms of the mean and quartiles.

Thank you.

**Comment by torognes** [comment]
Thanks for the suggestion. I think it is a good idea and will try to implement it in the next release.

**Comment by torognes** [comment]
This issue should be solved in version 1.10.0 just released.
