### ISSUE TITLE
relabel issue duruing --derep_fulllength

### ISSUE THREAD

**Issue by lucaz88** [torognes/vsearch#150]
Hi everyone,
running the following command:
~/vsearch-1.9.3-linux-x86_64/bin/vsearch --derep_fulllength input.fasta --sizeout --fasta_width 0 --relabel denovo --output seqs_derep.fa -uc seqs_derep_uc.txt

I get this:
>denovo1;size=19918;
GCTCCTACC[....]
>denovo1;size=17984;
GCACCTACC[....]
>denovo1;size=3675;
GCACCTACC[....]

It seems that the ticker doesn't increase so I always get the same new label for each unique seq.

Thanks a lot for your support,
cheers
Luca

**Comment by torognes** [comment]
Thank you for reporting this bug. This issue is now fixed in version 1.9.4 just released.
