### ISSUE TITLE
usearch_local

### ISSUE THREAD

**Issue by annaship** [torognes/vsearch#152]
What should I use instead of usearch's option "usearch_local", which allows to avoid a global alignment when query sequences are huge (or just very uneven)? I tried to use usearch_global for contigs against a rRNA ref db. Maybe I should use another options?
Thank you.

**Comment by colinbrislawn** [comment]
Vsearch does not currently support local alignments. :-(

For for local nucleotide alignments, have you considered bwa-mem? For
proteins, have you considered diamond? Both are open source, highly cited,
and on github.

**Comment by annaship** [comment]
Thank you for the information! I'll try.
