### ISSUE TITLE
automake 1.15

### ISSUE THREAD

**Issue by felixeye** [torognes/vsearch#154]
Hi guys,

here is a really great alternative to **usearch**. Thanks a lot for this gift.
I just have a small question around the installation step, the make command seems to complain about **automake 1.15**. In my case I have **automake-1.13**, so I adapted the Makefile to the 1.13 and **vsearch** compile without any error.
My question is do you have any specific reason(s) to use the version 1.15?

/Felix

**Comment by torognes** [comment]
Hi @felixeye! We are using autoconf version 2.63 that seems to require automake 1.15. This is the earliest version that we have tested. It may work well with even earlier versions. If you are using an earlier `autoconf` and `automake`, you could try to change the fourth line with `AC_PREREQ([2.63])` in `configure.ac` to an older version number and then recompile. You should probably also run `autogen.sh` before you run `./configure` to update all files. I hope this helps.

**Comment by felixeye** [comment]
Great!
It works just fine.
Thank you very much @torognes
