### ISSUE TITLE
Avoid progress indicator if stderr is not a terminal

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#156]
Check if stderr is a terminal with (isatty(fileno(stderr)) and avoid updating the progress indicator when it is not a terminal.

**Comment by torognes** [comment]
This issue should be solved in version 1.10.0 just released.

**Comment by frederic-mahe** [comment]
In practice, `stderr` is not a `tty` when `--log` is used and is a file. Maybe the issue should be renamed "Avoid writing progress indicator to log file"? In any other situation, a progress is written to `stderr`.

Two questions:
- can vsearch know if `stderr` or `stdout` are attached to anything else than a `tty`?
- should vsearch avoid outputting progress indicator if both `stderr` and `stdout` are attached to `tty`s? It would avoid some visually mixed output. Of course, I keep in mind vsearch offers the options `--log` and `--quiet` to remove clutter.

(from this [page)](http://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout) Other tools adopt different solutions : `curl`, `wget`, and `pv` all use `stderr` to output progress, with `wget` and `pv` making it conditional on `stderr` being a `tty` and `curl` making it conditional on `stdout` not being the `tty` (presumably to avoid visual clutter).

**Comment by torognes** [comment]
Yes, it can be checked whether stdout or stderr are attached to a file, a link, a pipe, a tty, or some other device. We can use the stat and isatty system calls to determine this.

Currently, vsearch prints progress to stderr if stderr is a tty unless the `--quiet` or `--no_progress` options are specified.

For most, if not all, commands vsearch does not print anything at all to stdout, unless some type of output is directed there using "-" or "/dev/stdout" as the filename. In those cases it could often be nice to turn off progress to stderr to avoid a mix of progress and actual output. That can be achieved using the `--no_progress` or `--quiet` options.

Determining whether any of the output actually ends up at the tty together with stderr in order to automatically turn of progress could be a bit complex. I think it clearly understandably how it works now and clutter is easy to avoid. I therefore think we should keep it as it is.
