### ISSUE TITLE
Vectorization of global alignment - single query vs single target

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#16]
SIMD-vectorization of global alignment of one query vs one target sequence. Should use the striped approach of Farrar (2007) or the vertical vector approach of Rognes (2000).

**Comment by frederic-mahe** [comment]
Not sure if it relevant or not: https://github.com/CMU-SAFARI/Shouji#key-mechanism presents a pre-filtering technique to reduce the number of sequence pairwise-comparisons.

![](https://github.com/BilkentCompGen/Shoji/blob/master/Figure1-GitHub.png)
