### ISSUE TITLE
--relabel not working with --consout

### ISSUE THREAD

**Issue by f-heeger** [torognes/vsearch#160]
I am not sure if this actually a bug or "working as intended", but when I use the --relabel and --consout options together for --cluster_size, my consensus sequences are not relabeled but instead look like this: 
`centroid=intitalSequenceID;seqs=1822;size=1822;`

**Comment by torognes** [comment]
Thanks for pointing this out. I will relabel the consensus sequences in the next release.

**Comment by torognes** [comment]
This issue should be solved in version 1.10.0 just released.
