### ISSUE TITLE
Add options to filter sequences and consensus sequences

### ISSUE THREAD

**Issue by fgvieira** [torognes/vsearch#161]
Hi all,

I've only recently discovered VSEARCH but I must say, so far, I am pretty impressed... It is super fast and it seems to get the job done pretty well.

Right now I am mostly interested on the clustering algorithm but there is no way to filter sequences based on proportion/number of masked bases (as these sequences will most probably not be part of any meaningful alignment) like there is for minimum size (--minseqlength).

Regarding the consensus sequence, I've noticed that if I cluster a set sequences twice (sequentially) the two outputs are different. I guess this is because VSEARCH performs a single-pass clustering, but is there any reason why it wouldn't do more passes?
It would also be nice to have more control over the consensus output, like only doing a consensus if a minimum number of sequences are present, or filter output it by proportion of missing data.

cheers,
FGV

**Comment by torognes** [comment]
Hi @fgvieira 

Thanks for the suggestions. We will consider them for inclusion in future releases.

Adding filtering on the number of masked bases should be straightforward and an enhancement for several commands.

Regarding multiple passes and different consensus sequences. Do you mean doing multiple clusterings one after another using the output from the previous pass as input to the next pass? Or do you mean that you get different results from clustering the same dataset twice?

Regarding control over the consensus output, could you go into more detail here? Would you like to set a minimum number of bases that must be present in each position, or a minimum number of sequences in total? I guess some of this could be performed by post-processing the output data. Have you seen that there is a "--profile" option that outputs the number of the different bases for each position in the consensus?

- Torbjørn

**Comment by fgvieira** [comment]
Hi @torognes 

Regarding multiple passes, I'm referring to multiple clusterings one after another using the output from the previous pass as input for the next pass. Ideally it could go until no there are no more changes in clusters, but it could also be user-defined...

Regarding control over the consensus output, my general idea is to make it more flexible so that the user can easily control/filter the output. For example:
- define if NNNNNN are transformed into AAAAAA on the consensus
- minimum proportion/number of bases that must be present on each position (otherwise N)
- consensus with IUPAC codes
- filter out consensus that are made up of less then X number of sequences

FGV

**Comment by torognes** [comment]
A few changes were made to the consensus sequences some time ago. In some cases "AAAA" was erroneously output when the sequence should have been "NNNN".

Recently the command `--fastx_filter` was added. This command can be used to remove sequences based on length, the number of Ns etc.

I think more advanced methods for constructing consensus sequences may be performed by analysing the profile generated using the `--profile` option.

We have no plans to include clustering with multiple passes.

I will close the issue.
