### ISSUE TITLE
inconsistency with merging pairs

### ISSUE THREAD

**Issue by dereneaton** [torognes/vsearch#162]
I've been testing the `--fastq_mergepairs` function and I'm having trouble understanding why some reads are failing to merge while others are merging. Below is an example of two pairs in my data set that both match perfectly (as shown by my hand alignment below), and so are expected to merge, but vsearch only merges the second one and not the first:

Alignment by hand:
```
Pair1
TGCAGTTGGAAGGTATGGCCTTGCCTGACTTGCCATGCACAAGCAAGGTTTTATTTTGG		        R1
       GGAAGGTATGGCCTTGCCTGACTTGCCATGCACAAGCAAGGTTTTATTTTGGCACAAGC     	R2

Pair2
TGCAGGTCACCCCACGGTGGTCGAGGAGCTTGCGCTAGCAAGCGTCTC       	   R1
       CACCCCACGGTGGTCGAGGAGCTTGCGCTAGCAAGCGTCTCGAGACCA	   R2
```

I've tried toggling as many combinations of parameters as I can think of but can't seem to get the first pair to merge. Here is an example of my vsearch call:

```
vsearch-1.9.10-linux-x86_64 \
    --fastq_mergepairs test_R1.fq \
    --reverse test_R2.fq \
    --fastqout merged.fq \
    --fastqout_notmerged_fwd not_R1.fq \
    --fastqout_notmerged_rev not_R2.fq \
    --fastq_allowmergestagger \
    --fastq_truncqual 0 

Merging reads 100%  
2 read pairs total
1 pairs merged (50.0%) and 1 pairs not merged (50.0%).

```
  

The example `test_R1.fq` file is:
```
@d41732_35918_c1
TGCAGTTGGAAGGTATGGCCTTGCCTGACTTGCCATGCACAAGCAAGGTTTTATTTTGG
+
BBBBB>DFHEHGGEEHDG;EFHGIIIICHIIIHHGGIBFGGGHIBHGIFFHHIIGGGCE
@d41732_35919_c1
TGCAGGTCACCCCACGGTGGTCGAGGAGCTTGCGCTAGCAAGCGTCTC
+
BBBBBHHGHJJJJIJJJIIJHIJJJJJIIJJJJJJJJJJJIIHHCDFF
```

and the `test_R2.fq` file is:
```
@d41732_35918_c2
GGAAGGTATGGCCTTGCCTGACTTGCCATGCACAAGCAAGGTTTTATTTTGGCACAAGC
+
HIGF@DCEHHHCDBDD;GHGGEJIGFGDGFHHGGJJGGIGIIJIJIJJIHGFFA8HFDD
@d41732_35919_c2
CACCCCACGGTGGTCGAGGAGCTTGCGCTAGCAAGCGTCTCGAGACCA
+
B=FFHHAIIHBJIJJJJIHIGGJJIJJJJJJJJJJJJJJJHHHHHFDD
```

Your help is greatly appreciated. Thanks.

**Comment by dereneaton** [comment]
For what it's worth, I just tested and found that the read-merging program PEAR also only merges the second pair and not the first from my example. However, I remain baffled as to why.

**Comment by torognes** [comment]
It appears that the sequences in the second input file are not reverse complemented as the programs expect them to be. If you use the file below as `test_R2.fq` they will both be merged successfully as you indicated.

```
@d41732_35918_c2
GCTTGTGCCAAAATAAAACCTTGCTTGTGCATGGCAAGTCAGGCAAGGCCATACCTTCC
+
DDFH8AFFGHIJJIJIJIIGIGGJJGGHHFGDGFGIJEGGHG;DDBDCHHHECD@FGIH
@d41732_35919_c2
TGGTCTCGAGACGCTTGCTAGCGCAAGCTCCTCGACCACCGTGGGGTG
+
DDFHHHHHJJJJJJJJJJJJJJJIJJGGIHIJJJJIJBHIIAHHFF=B

```

The one merged sequence you anyway obtained has many mismatches and should probably have been rejected.

I am about to finish a much improved implementation of `fastq_mergepairs` both regarding speed and accuracy. It will be released shortly.

**Comment by dereneaton** [comment]
Oh, that is such an obvious solution. Thanks @torognes !!
