### ISSUE TITLE
--self doco error?

### ISSUE THREAD

**Issue by wwood** [torognes/vsearch#163]
I notice this in vsearch 0.1.10 -h
```
Searching
...
  --self                      reject if labels identical
  --selfid                    reject if sequences identical
```
Is that right or should they be switched?

**Comment by frederic-mahe** [comment]
Hi @wwood,

this is correct. vsearch behaves like usearch, and usearch's selfid is defined as [Ignore hits to identical sequence](http://drive5.com/usearch/manual/opt_selfid.html).

Here, "id" means "identity", as in sequence identity.

Best,

**Comment by wwood** [comment]
ah, ok, good good. Nothing to see here then.
