### ISSUE TITLE
Make OTU tables

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#166]
Add options to create OTU tables directly, as described [here](http://drive5.com/usearch/manual/mapreadstootus.html).

**Comment by torognes** [comment]
See also the VSEARCH Forum post:

https://groups.google.com/forum/#!topic/vsearch-forum/83tCXeQ1mEw

**Comment by davidmartinad200** [comment]
Thanks ,
Just in case it can help others on the mean time i wrote a perl script that will take the uc file and convert it to a OTU table. It requires the perl module Text::Table. Change the filename variable accroding to the name of your ucfile.

My ucfile looks like this:
```
H       185     322     99.1    +       0       0       I322M   Sample01_1 OTU_17349
H       420     283     99.3    +       0       0       283M    Sample02 OTU_21114
H       394     283     99.3    +       0       0       283M    Sample03_8 OTU_1154
H       260     322     99.4    +       0       0       322M    Sample05_3 OTU_20186
H       164     329     99.4    +       0       0       I329M   Sample06_2 OTU_6303
H       164     329     99.7    +       0       0       I329M   Sample06_4 OTU_6303
```

```
#! /usr/bin/perl -w

#Convert UC file to tab file
use warnings;
use Data::Dumper;
use Text::Table;

my $filename = 'ucfinal.txt';
open(my $fh,'<', $filename)
    or die "Could not open file '$filename' $!";

my %samples = ();
my %values;
my $nbOTUs = 0; 
while (my $row = <$fh>) {
    chomp $row;
    my @F=split("\t",$row);
    my @sample = split("_",$F[8]);  # e.g Sample01_1
    my $OTU = $F[9];
    $samples{'OTUs'}{$sample[0]}{$OTU}+=1; 
}

my $struct = $samples{OTUs};
my @cols = sort keys %{ $struct };
my @rows = sort keys %{ { map {
    my $x = $_;
    map { $_ => undef }
    keys %{ $struct->{$x} }
                          } @cols } };

my $tb = Text::Table->new('', @cols);

for my $r (@rows) {
    $tb->add($r, map $struct->{$_}{$r} // '0', @cols);
}

print $tb;
```

here is how the output will look. Otus as rows and sample as column.

```
          Sample01 Sample02 Sample05 Sample06 Sample07 Sample08 Sample01 Sample02 Sample05 Sample06 Sample07 Sample08
OTU_10017     2     7     0    1      6     5    6    3    0    0    6    7
OTU_10021    96    92     0    0     58    42    8    9    0    0    6   13
OTU_10026    22    27     0    0     26    16    3    2    0    0    1    4
OTU_10046   124   136     0    2    153   137  296  333    0    0  318  357
OTU_10055     0     4     0    0      0     0    0    0    0    0    0    0

```

**Comment by colinbrislawn** [comment]
:+1: Love it!

@torognes Which OTU table format would you support? There is the flat text format, which is common and easy, BIOM v1 which is widely used, and BIOM v2.1 which is the new qiime default.

@davidmartinad200 :smile: There has got to be 20 variations of this script. I quite like this one in python:
https://github.com/leffj/helper-code-for-uparse/blob/master/create_otu_table_from_uc_file.py

**Comment by torognes** [comment]
@colinbrislawn All of them, probably. But it will have to wait a while. Need to finish manuscript! :-)

**Comment by colinbrislawn** [comment]
Awesome!

**Comment by frederic-mahe** [comment]
On his [GitHub Gist](https://gist.github.com/gregcaporaso/f3c042e5eb806349fa18), Greg Caporaso shows how to use the python module [biom](http://biom-format.org/index.html) to convert `uc` files produced by usearch and vsearch into the `biom` format (and back to OTU tables). Indeed, there are several solutions available to make that conversion.

**Comment by torognes** [comment]
On overview of the options for this supported by newer versions of usearch:
http://drive5.com/usearch/manual/mapreadstootus.html

**Comment by torognes** [comment]
I have added the options `--otutabout`, `--biomout` and `--mothur_shared_out` to generate OTU tables with the `usearch_global` and `search_exact` commands. Sample identifiers and OTU identifiers must be [specified as with USEARCH](http://drive5.com/usearch/manual/mapreadstootus.html). This is in the master branch, but not released yet. Generating BIOM v2.1 output is somewhat more complex.

**Comment by dridk** [comment]
Why only usearch_global and search_exact ? I create my biom file from the vsearch clustering using the *.uc file. 
I excepeted to have something like : 

      vsearch --cluster_fast FILENAME --id 0.97 --centroids FILENAME --biomout otu.biom

**Comment by colinbrislawn** [comment]
@dridk has a point. Any command that makes .uc files _could_ plausibly output .biom files. 

In your example,
`vsearch --cluster_fast FILENAME --id 0.97 --centroids FILENAME --biomout otu.biom`
is `FILENAME` is dereplicated? If so, the reads would no longer have unique sampleIDs, so you could not construct a .biom file...

**Comment by torognes** [comment]
There was an error in the code that made vsearch not output OTU tables with `--mothur_shared_out` or `--biomout` unless `--otutabout` was also specified. This is now fixed.

**Comment by torognes** [comment]
As far as I know usearch will only output OTU tables with the `search_exact` and `usearch_global` commands.

I could add support in vsearch for generating OTU tables with the clustering commands, but there are some complications with the sample and OTU names.

What should be used as the OTU names? We could generate OTU names if for instance a relabel option is added to the command so that each cluster centroid would get its own consecutive OTU name.

If, as @colinbrislawn asked, the file being clustered is already dereplicated it would not contain all sample names. All data needed would then not be available to create an OTU table.

**Comment by torognes** [comment]
Added a progress indicator. The performance is not good for large OTU tables. I'll use a better data structure.

**Comment by torognes** [comment]
Fixed a bug and added OTU table support for clustering commands as well. Relabelling is supported.

**Comment by torognes** [comment]
You can now run something as simple as

`vsearch --cluster_size input.fasta --id 0.97 --relabel OTU --biomout otutable.biom`

This does not make much sense if the input file is dereplicated. The input file must include `;sample=xyz;` strings in the header, otherwise the initial part of the header will be considered the sample name.

**Comment by torognes** [comment]
Adjusted regular expressions for sample and OTU identifier extraction. Described the new options in the manual. Bumped version number to 2.2.0 and released.

Biom format 2.1 is not supported (yet). If there is demand, a new issue could be opened.

Closing issue.

**Comment by Spartanzhao** [comment]
how can I remove the singleton?
