### ISSUE TITLE
Compilation error [Fasta.c]

### ISSUE THREAD

**Issue by JehanneQuentin** [torognes/vsearch#169]
Hi! I'm trying to install Vsearch but unfortunately:

> g++ -DHAVE_CONFIG_H -I. -I..    -Wall -Wsign-compare -g -O2 -MT fasta.o -MD -MP -MF $depbase.Tpo -c -o fasta.o fasta.cc &&\
	mv -f $depbase.Tpo $depbase.Po
fasta.cc: In function ‘fasta_s* fasta_open(const char*)’:
fasta.cc:146:12: error: ‘bz2_lib’ was not declared in this scope
       if (!bz2_lib)
            ^
fasta.cc:149:17: error: ‘struct fasta_s’ has no member named ‘fp_bz’
       if (! (h->fp_bz = (*BZ2_bzReadOpen_p)(& bzError, h->fp,
                 ^
fasta.cc:149:27: error: ‘BZ2_bzReadOpen_p’ was not declared in this scope
       if (! (h->fp_bz = (*BZ2_bzReadOpen_p)(& bzError, h->fp,
                           ^
fasta.cc:150:45: error: ‘BZ_VERBOSE_0’ was not declared in this scope
                                             BZ_VERBOSE_0, BZ_MORE_MEM,
                                             ^
fasta.cc:150:59: error: ‘BZ_MORE_MEM’ was not declared in this scope
                                             BZ_VERBOSE_0, BZ_MORE_MEM,
                                                           ^
make[2]: *** [fasta.o] Erreur 1
make[1]: *** [all-recursive] Erreur 1
make: *** [all] Erreur 2

=> v1.10.1

**Comment by xflouris** [comment]
Hi @JehanneQuentin ,
there was a typo in the source code regarding a check for BZLIB. Please pull again from the repository and the code should compile fine now.

**Comment by JehanneQuentin** [comment]
Perfect! Thanks :-)
