### ISSUE TITLE
Merge pair fails when there are empty sequences

### ISSUE THREAD

**Issue by ZeweiSong** [torognes/vsearch#175]
The --fastq_mergepairs function report a fatal error:

    Merging reads

    Fatal error: Invalid line 27054 in FASTQ file: Empty sequence line

I've trimmed my sequences with cutadapt, so some sequences are left empty there as place holder.

**Comment by frederic-mahe** [comment]
Hi @ZeweiSong,

yes, vsearch doesn't like empty fastq entries. To avoid that, you can use `cutadapt` with the option:
```
cutadapt --minimum-length 32
```
I use a minimum length of 32 nucleotides, as it is also the default minimum length for downstream vsearch commands.

**Comment by torognes** [comment]
Thanks for the notice. I hope to eliminate this problem in the next release.

**Comment by torognes** [comment]
Currently VSEARCH does not allow input files in FASTQ format to have an empty sequence.

Perhaps FASTQ files with empty sequences should be considered invalid. I cannot find a clear statement in the FASTQ "standard" on this issue in [the NAR paper by Cock et al.](https://doi.org/10.1093/nar/gkp1137), but it seems reasonable to assume they the sequence and quality lines cannot be empty.

In the case above the output from cutadapt may be considered invalid and it would be correct for VSEARCH to flag it as an error.

Alternatively, we could consider empty sequences ok and accept them. What do you think?

**Comment by frederic-mahe** [comment]
If that case is not clearly defined in the standard, I think the best solution would be to simply discard empty sequences, as vsearch already discards sequences shorter than 32 nucleotides. It would avoid a `fatal error` that could be hard for users to understand and to avoid.

It is up to you, depending on the complexity of the implementation.

**Comment by torognes** [comment]
The latest version of vsearch, 2.3.0, just released, accepts zero-length sequences in FASTA and FASTQ files. The `fastq_mergepairs` command should work as expected with such sequences. Note that the `--fastq_minlen` and `--minseqlength` options still defaults to 1, so some commands may ignore them.
