### ISSUE TITLE
Compute evalues and bit scores using Karlin-Altschul statistics

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#176]
`usearch 8` now [Karlin-Altschul statistics](uses http://www.drive5.com/usearch/manual/karlin_altschul.html) to compute evalues and bit scores in search results.

**Comment by torognes** [comment]
As far as I can see usearch (version 8) does not compute e-values or bit scores for global alignments, only for local alignments. Karlin-Altschul statistics (as in Blast) are only defined for local alignments.

**Comment by frederic-mahe** [comment]
You are right. I forgot it only applies to local pairwise alignments.
