### ISSUE TITLE
uchime_denovo on very long reads

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#177]
Good morning, 

I'm interested in performing chimera checking on very long reads created using a nested dilution + PCR process (described [here](http://www.illumina.com/technology/next-generation-sequencing/long-read-sequencing-technology.html) and [here](https://pag.confex.com/pag/xxi/webprogram/Paper6752.html)). Unlike typical amplicons, which are from a single region of a single gene, these reads have undergone PCR and subassembly and can be 1-10kbp long. 

Do you think that `--uchime_denovo` would be appropriate for 1,000 bp reads? 
Do you think that `--uchime_denovo` would be appropriate for 10,000 bp reads?

Thank you for developing this excellent software. I appreciate your advice.

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn,

If I remember correctly, the uchime algorithm splits the query sequence into a fix number of chunks (5, I think), and the chunks are compared to potential parents (i.e. more abundant sequences). I guess using long chunks will decrease search's sensitivity and limit your ability to detect potential parents. I don't think there is an option in vsearch to control the number of chunks.

The abundance profile of your data could be a problem too. With long-fragment sequencing, you probably have "shallow and flat profiles" (most sequences are seen only once). This is problem for a  `--uchime_denovo` search.

That being said, uchime has been used to search for chimeras (`--uchime_ref`) in 16S reference databases (1,600 bp sequences). You can try to use it on longer sequences, but keep in mind that sensitivity will be low.

**Comment by torognes** [comment]
As @frederic-mahe writes, the query sequence is split into parts which are searched against potential parents. It is split into 4 parts (not 5) and there is no option to select this. It might be a good idea to be able to change this, but the whole algorithm should really be evaluated properly for longer sequences.

**Comment by colinbrislawn** [comment]
Good to know @torognes. Thanks for telling me more. I'll close this issue until I have a more specific issue or demonstrable error. 

Personal communication implies Robert Edgar is working on chimera checking for usearch v9. Reactivating to his new work could be a good approach. Independent improvements (#118) would also be excellent.
