### ISSUE TITLE
cluster_smallmem: "Unable to allocate enough memory" error on a very large dataset

### ISSUE THREAD

**Issue by ghbio** [torognes/vsearch#178]
I'm getting the error "Unable to allocate enough memory" trying to cluster a large sorted input file (37G) with 64713320 protein coding sequences, min 100bp, max 4998bp, avg 566bp. I'm using the release binary of `vsearch (v1.11.1_linux_x86_64)` on a 24 core 80GB RAM server. Here is my command and the standard output I get.  

```
$ vsearch --cluster_smallmem mp.cds.red.fasta \
--id 0.95 --centroids mp.cds.red.centroids.fasta \
--uc mp.cds.red.clustered.uc --threads 24 --log vsearch.log

Reading file mp.cds.red.fasta 100%
36616499055 nt in 64713320 seqs, min 100, max 4998, avg 566
Masking 100%
Counting unique k-mers 100%


Fatal error: Unable to allocate enough memory.
vsearch v1.11.1_linux_x86_64, 78.8GB RAM, 24 cores
```

A subsample with the first 150 sequences works without problems, so I don't know how to reproduce this behavior with a manageable input file that I could send you.  

I have read in the documentation that "Search and clustering might use a lot of memory, especially if run with many threads", so I have also tried with `--threads 12, 8 and 1` with the same results.  

Thanks a lot!

**Comment by colinbrislawn** [comment]
Good morning,

I don't know what steps you have taken with `mp.cds.red.fasta`, but have you considered dereplicating your reads before clustering? This preprocessing step removes duplicate reads before clustering, and could dramatically reduce your file size so that it can work the available RAM. 

You could also try renting a supercomputer from Amazon. They provide ones with [lots of RAM for a few dollars an hour](http://www.ec2instances.info/?selected=cr1.8xlarge).

**Comment by ghbio** [comment]
Hi, thanks a lot for your input.  
I have already dereplicated the dataset with the `--derep_fulllength` option and it does a good job by slimming it down some ~5GB, but apparently not enough for my available hardware. My intention here was to confirm that my problem was RAM related before taking any further steps.

**Comment by colinbrislawn** [comment]
So `mp.cds.red.fasta` is the dereplicated file, which is 5GB, right? If it still throws this memory error on a 80GB machine, feedback from the devs would be helpful. 

I often use vsearch to cluster amplicon reads in the 15GB range. I also find that clustering directly is limiting. To address this, I use this nested clustering strategy. Toy example:
```
--derep_fulllength seqs.fna --output seqs.derep.fna
--cluster_smallmem seqs.derep.fna --centroids seqs.derep.centroids.fna --id 0.95 --threads 24
--usearch_global seqs.fna --db seqs.derep.centroids.fna --id 0.95 --threads 24 --uc map.uc 
```

What's cool about this, is that the final output `map.uc` should be the same as 
`--cluster_smallmem seqs.fna --uc map.uc`
accept the nested approch uses way less RAM. 

Anyway, the nested approach may be a good fit for your data. The actual devs probably have better ideas :-)

**Comment by colinbrislawn** [comment]
>min 100bp, max 4998bp, avg 566bp

I was going to mention this too. My understanding is that VSEARCH uses a [semiglobal or "glocal" alignments](https://en.wikipedia.org/wiki/Sequence_alignment#Global_and_local_alignments), which is perfect for amplicons which come from the same gene. I'm not sure how well it works from different genes of different lengths. Just something to be aware of. 

@torognes Can you verify the alignment method for me? I'm not sure if it's true global or "glocal."

**Comment by ghbio** [comment]
Again, thanks a lot for your reply!  
I think I was misleading before: the 37GB file is the *already* dereplicated dataset. Dereplication only shaves 5GB off my file. This means that my error could still be due just to a lack of RAM. I don't know if in this case your nested approach would work either.  
You raise a good point with the alignment method. I wanted to use [cd-hit-est](http://weizhongli-lab.org/cd-hit/) for this job, using the local sequence identity and alignment coverage control for the shorter sequence, but in my setup this approach takes too long.

**Comment by colinbrislawn** [comment]
Oh thank you. I see the issue now.

Yeah, dereplication will work much better with amplicons because the ceiling of diversity is much lower; dereplication takes reduces my size by 10x, and discarding singleton reads by 100x. Probably not a good fit to protein coding genes. 

At this scale, I think [a supercomputer from Amazon for ~$5 hour](http://www.ec2instances.info/?selected=cr1.8xlarge) would absolutely worth considering.

**Comment by ghbio** [comment]
yes, that's right. Although it would be nice to get an estimation of computing time beforehand! 
Cheers

**Comment by colinbrislawn** [comment]
Yeah, clustering slows down as the number of hits in the database increases, so estimating time is hard.

Just to 'play devil's advocate', if you could pay for 37GB of DNA sequencing, why can't you pay for a super computer for processing? A full day of compute time costs $84 (24h x $3.5), which must be less than sequencing cost.

**Comment by ghbio** [comment]
Yes, I agree with you... but as sometimes happens "it's complicated". Nevertheless, it would also be interesting to be able to estimate the amount of RAM needed in order to tune the size of the computer

**Comment by colinbrislawn** [comment]
>"it's complicated"
I've been there too. 😭 

Good luck Pablo!

**Comment by frederic-mahe** [comment]
I think we can now close that issue.
