### ISSUE TITLE
Wrong values in the blast6out table

### ISSUE THREAD

**Issue by fjossandon** [torognes/vsearch#179]
Hello,
I have just noticed that the blast6out table reported coordinates diverge significantly from what would be expected from mimicking that BLAST table format. The Query and Target Start and End coordinates in the original BLAST format correspond to the Start and End of the alignment for each sequence, but this is not what appears in the Vsearch source code (results.cc, results_show_blast6out_one).

In Vsearch, there is a fixed "1" as Start for both Query and Target and the End correspond to the length of the corresponding sequence (e.g. qend = qseqlen). This is wrong because the data that is expected from this table is the details (Start/End) of the alignment itself, meaning that the only way to know the alignment coordinates is to print the alignment file with "--alnout", which uses more space and needs extra parsing. It also confuses people expecting the same kind of output than BLAST.

The last 2 columns that in BLAST represents the E-value and Score, in Vsearch have a fixed "-1" and "0", maybe because Vsearch don't use those values? It does not bother me, but it could be stated somewhere in the documentation that those 2 columns don't have a meaning in Vsearch.

Best regards.

**Comment by frederic-mahe** [comment]
Hello @fjossandon,

vsearch outputs blast6out results exactly like usearch, for compatibility reasons. As written in vsearch's documentation:
```
7. qlo: first nucleotide of the query aligned with the target. Always equal to
1 if there is an alignment, 0 otherwise.
8. qhi: last nucleotide of the query aligned with the target. Always equal to
the length of the pairwise alignment. The field is set to 0 if there is no
alignment.
9. tlo: irst nucleotide of the target aligned with the query. Always equal to 1
if there is an alignment, 0 otherwise.
10. thi: last nucleotide of the target aligned with the query. Always equal to
the length of the pairwise alignment. The field is set to 0 if there is no
alignment.
11. evalue: expectancy-value (not computed for nucleotide alignments).
Always set to -1.
12. bits: bit score (not computed for nucleotide alignments). Always set to 0.
```
We are aware that some information is missing, so we introduced new optional columns:
```
qihi Last nucleotide of the query aligned with the target (ignoring terminal gaps). Nucleo-
tide numbering starts from 1. The field is set to 0 if there is no alignment.
qilo First nucleotide of the query aligned with the target (ignoring initial gaps). Nucleotide
numbering starts from 1. The field is set to 0 if there is no alignment.
tihi Last nucleotide of the target aligned with the query (ignoring terminal gaps). Nucleo-
tide numbering starts from 1. The field is set to 0 if there is no alignment.
tilo First nucleotide of the target aligned with the query (ignoring initial gaps). Nucleotide
numbering starts from 1. The field is set to 0 if there is no alignment.
```
You can compose a custom output table, with the above columns, by using the `--userout` and the `--userfields` options.

**Comment by fjossandon** [comment]
Hello @frederic-mahe 
Thanks for the quick reply!

At the time of writing the report I only had found the http://www.drive5.com/usearch/manual/blast6out.html page referenced on results.cc source code when searching for the documentation, but now I found the PDF manual which is more detailed.

I can work with the --userout and the --userfields to create the table with the columns I was expecting for the Blast 6 table format (thanks for that tip!), but I still think is wrong and really counterintuitive to have columns that don't match what is expected by the name of the format option, specially for new users such as myself. It would be different if the argument were just called "--table" because I would expect to have its own format (after all is a different program), but calling it "--blast6out" means that it can be assumed that it will show the same values than the BLAST table (qilo, qihi, tilo, tihi), which is the source of the confusion.

My suggestion is to use the alignment coordinates and declare it in DELIBERATE CHANGES if this departs from previous Usearch behaviour, or change the argument to just "--table" to avoid confusion.

Please consider it.

**Comment by frederic-mahe** [comment]
We need to work on the output of the `bit score` and `evalue` columns (see [Issue #176](https://github.com/torognes/vsearch/issues/176)). Maybe we can use that opportunity to make the `qilo`, `qihi`, `tilo` and `tihi` the default for the `--blast6out` option.

Thanks for the suggestion.

**Comment by torognes** [comment]
Hello @fjossandon!

Thanks for your suggestions.

Regarding the `--blast6out` option: We have tried to make vsearch very similar to usearch (version 7) to make it easy for user to switch over with minimum fuss. Therefore we choose to keep the blast6out file format similar to usearch 7. I haven't checked usearch 8 in this regard.

There is also another good argument for keeping the values as they are. BLAST is a local alignment tool, so the alignments are local and consist of subsequences of the query and database sequences. The alignments produced by vsearch are global alignments. By default there are some very low terminal gap penalties that may give the impression that the alignments are local, but they are really global. And global alignments start and end at the very beginning and very end of the sequences, even if they start or end with gaps. Therefore the start and end coordinates should also be at the very beginning and end of the sequences.

We do see the need of obtaining the other positions, and therefore we chose to make it possible to get those positions by the use of the qilo, qihi, tilo and tihi user fields, as @frederic-mahe described.

In the very first versions of vsearch, the output using blast6out was actually as you suggested. However, after careful consideration we changed our mind.

Unless usearch version 8 or a later version changes this, I do not think we will change it again.

- Torbjørn

**Comment by fjossandon** [comment]
Hello @torognes ,
> Regarding the --blast6out option: We have tried to make vsearch very similar to usearch (version 7) to make it easy for user to switch over with minimum fuss.

I understand your desire to be consistent with previous releases, I love consistency, but the argument name "blast6out" imply assumptions for new users (to use blast format), specially for Blast users. So is consistent with Usearch but inconsistent with Blast.

> And global alignments start and end at the very beginning and very end of the sequences, even if they start or end with gaps. Therefore the start and end coordinates should also be at the very beginning and end of the sequences.

Hmm, in my humble opinion, the start matching always 1 is not useful because is obvious and a fixed value, and the end is just telling me the sequence length, so both could actually be summarized in one "Seq Length" column. When comparing 2 similar sequences or when searching a gene nucleotide sequence inside a genome, I think that most users will be interested in exactly where is the match is located (where the biological significance is), but the default columns will not tell it... It would be interesting to know how many people use the --blast6out table as it is versus those that have to change to a custom format to retrieve those missing values. The Global alignment approach could be stated in the command line help and documentation, not necessarily use 1-Length coordinates.

I switched to use --userfields to get the data I need as @frederic-mahe suggested, so my own problem is fixed, but it feels like an uncessary additional step.

**Comment by frederic-mahe** [comment]
As @fjossandon suggested, we can try to improve the documentation to warn users about the `--blast6out` option. I pushed a modification of the `man` page to try to make it clearer that this is a blast-like table, not a blast result. Feel free to build on that.

We have to maintain compatibility with usearch, so that's pretty much all we can do for the `blast6out` option. I suggest we close that issue.

**Comment by fjossandon** [comment]
@frederic-mahe , thanks for the documentation improvements!! Since usearch compatibility is so important and blast6out settings will be kept, I will close the report then.

Cheers,
