### ISSUE TITLE
New option for trimming the sequence based on maxEE

### ISSUE THREAD

**Issue by ZeweiSong** [torognes/vsearch#180]
Is it possible to have an option so that the sequence will be trimming from the end, base by base, to the length that its maxEE is lower than the threshold?

Thanks!

**Comment by frederic-mahe** [comment]
Hi @ZeweiSong,

I work mostly on targeted sequencing (e.g., 16S rRNA) and I perform a filtering based on the expected error **after** the merging of paired-end reads. In fact I perform the EE-filtering (i.e. discard sequences > maxEE) after clustering, at the very end of the OTU delineation pipeline. In that context, the EE-trimming you suggest does not seem necessary.

On the other hand, EE-trimming would be interesting for single-end targeted sequencing or shot-gun genomics or transcriptomics. Do you plan to use that feature on shot-gun sequencing data? Do you know a tool that offers that possibility?

**Comment by torognes** [comment]
Hi @ZeweiSong 

Thanks for your suggestion. There is currently no option to do exactly what you are asking for, neither in usearch or vsearch, as far as I know. The `fastq_filter` command with the  `fastq_truncqual` option can trim based on quality score and using `fastq_maxee` it can discard sequences with too many expected errors. Perhaps you could use these to achieve something similar to what you want? I will consider adding a "fastq_truncee" option in the future.

**Comment by nextgenusfs** [comment]
@ZeweiSong, if you want a solution in the meantime, you can do this in Python/Biopython fairly easily (of course this is much slower than it would be in vsearch/usearch):

Regular maxEE filtering can be done like this:
```
def MaxEEFilter(input, maxee):
    from Bio import SeqIO
    with open(input, 'rU') as f:
        for rec in SeqIO.parse(f, "fastq"):
            ee = 0
            for bp, Q in enumerate(rec.letter_annotations["phred_quality"]):
                P = 10**(float(-Q)/10)
                ee += P
            if ee <= float(maxee):
                rec.name = ""
                rec.description = ""
                yield rec
```

And this can be adapted to truncate the read when the maxEE is reached like this:
```
def MaxEEFilterTrunc(input, maxee):
    with open(input, 'rU') as f:
        for rec in SeqIO.parse(f, "fastq"):
            ee = 0
            len = 0
            for bp, Q in enumerate(rec.letter_annotations["phred_quality"]):
                P = 10**(float(-Q)/10)
                ee += P
                if not ee <= float(maxee):
                    len = bp
                    break
            rec.name = 'maxee='+str(ee)+';len='+str(len)
            rec.description = ''
            yield rec[:len]
```

You can run the generator from a script like:

```
import sys
from Bio import SeqIO

SeqIO.write(MaxEEFilterTrunc(input, maxEE_value), output, 'fastq')
```

**Comment by nikosdarzentas** [comment]
Dear all,

I recently found this:
https://github.com/nisheth/meeptools
...which I believe is what @ZeweiSong <https://github.com/ZeweiSong> asked
for. Indeed an interesting feature.

Best wishes.

Nikos

http://bat.infspire.org | www
nikosdarzentas | Skype

**Comment by torognes** [comment]
The --fastq_truncee option is available with fastq_filter and fastx_filter in version 2.1.0 just released. The sequences will be truncated so that their total EE is never higher than the specified value.
