### ISSUE TITLE
--query_cov and --userfield qcov

### ISSUE THREAD

**Issue by crosenth** [torognes/vsearch#182]
I am seeing hits with qcov < --query_cov in the --userout results.  Should this be?  I can supply test files if necessary.

`vsearch --usearch_global INPUT --db DB --id 0.0 --query_cov 0.95 --userfields qcov --userout OUTPUT`

**Comment by frederic-mahe** [comment]
Hi @crosenth,

I think it might depend on the iddef and the way terminal gaps are taken into account. It would be great if you could provide a minimal example triggering the problem (one input sequence and one db sequence).

**Comment by crosenth** [comment]
Attached are a couple 16s query and target sequences.  Both query sequences generate alignments to their target sequences below the --query_cov threshold but end up in --userout matches.fasta.  I would expect both query sequences to go to --notmached notmached.fasta.

`vsearch --usearch_global query.fasta --db target.fasta --query_cov 0.95 --notmatched notmached.fasta --userout matches.fasta --id 0.0 --userfields query+target+id+qcov`

[query_target.zip](https://github.com/torognes/vsearch/files/312904/query_target.zip)

Thanks for your help!

**Comment by torognes** [comment]
Hi @crosenth ! Thank you for providing the test files. I've tried it now and it seems like vsearch makes a mistake here by not excluding the matches with too low query coverage. I will look into the problem and hope to provide a fix soon.

**Comment by torognes** [comment]
I found the problem in the code. Thank you for spotting this problem!

**Comment by crosenth** [comment]
Great thanks for the update!

**Comment by torognes** [comment]
I'll leave this issue open until it is fixed and released.

**Comment by torognes** [comment]
This issue is fixed in version 1.11.2 just released.
