### ISSUE TITLE
Comparing vsearch chimera detection with uchime - denovo

### ISSUE THREAD

**Issue by mothur-westcott** [torognes/vsearch#183]
I am trying to compare the results of vsearch with uchime using the denovo method.  I am using uchime version 4.2.40 and vsearch version v2.0.0_osx_x86_64.  Uchime is identifying 43.8% chimeras in my test file, but vsearch is finding 0%.  This seems odd and I am hoping you can help me figure out what is causing the difference.  The commands I am running are:

"./vsearch"  --uchime_denovo "stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.txt" --uchimeout "stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.chimeras.out"

Reading file stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.txt 100%  
142527 nt in 564 seqs, min 250, max 255, avg 253
Masking 100%  
Sorting by abundance 100%
Counting unique k-mers 100%  
Detecting chimeras 100%  
Found 0 (0.0%) chimeras, 564 (100.0%) non-chimeras,
and 0 (0.0%) borderline sequences in 564 unique sequences.
Taking abundance information into account, this corresponds to
0 (0.0%) chimeras, 564 (100.0%) non-chimeras,
and 0 (0.0%) borderline sequences in 564 total sequences.

"./uchime"  --input "stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.txt" --uchimeout "stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.chimeras.out"

00:00 1.1Mb  100.0% Reading stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.txt
00:00 1.1Mb 564 sequences                                                                                                                       
00:02 2.1Mb  100.0% 247/563 chimeras found (43.8%)

[stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.txt](https://github.com/torognes/vsearch/files/339899/stability.miseq_sop.trim.contigs.good.unique.good.filter.unique.precluster.txt)

**Comment by astanabe** [comment]
FASTA defline format for UCHIME public domain version and VSEARCH/USEARCH is different like below.

UCHIME
>sequencename/ab=100.0/
VSEARCH/USEARCH
>sequencename;size=100;

**Comment by mothur-westcott** [comment]
Thanks!

**Comment by torognes** [comment]
After changing the file format I got these results:

```
vsearch v2.0.0_osx_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading file stability.fsa 100%  
142527 nt in 564 seqs, min 250, max 255, avg 253
Masking 100%  
Sorting by abundance 100%
Counting unique k-mers 100%  
Detecting chimeras 100%  
Found 266 (47.2%) chimeras, 285 (50.5%) non-chimeras,
and 13 (2.3%) borderline sequences in 564 unique sequences.
Taking abundance information into account, this corresponds to
416 (6.3%) chimeras, 6199 (93.5%) non-chimeras,
and 13 (0.2%) borderline sequences in 6628 total sequences.
```
