### ISSUE TITLE
--minseqlength and --maxseqlength options do not work for filtering

### ISSUE THREAD

**Issue by GreetDB** [torognes/vsearch#186]
Hello,

I'm having a problem with the general options --minseqlength and --maxseqlength.
I would like to filter my reads so that I only keep the ones having a length between 60-65. Therefore, I'm using the following command:

```
vsearch --fastq_filter merged.fastq --minseqlength 60 --maxseqlength 65 --eeout --fastqout tmp.fastq
```

My merged.fastq files look like this (one having length > 65 and one having length < 60):

```
@seq1
CACGGAGGCGACAATAGTAGTAGGCGGAAGAATCAACGGCCAGCCCCACTAGGCCACTAT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJG
@seq2
CTGGTGTCATAATCCTCGGTCTAACGTATTTCAGTGACCTAG
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJG
@seq3
CGTGGCAGTTGAGCGCGGCAATCAACCCAAGATCATGGGCTGGTCGCGGTTTCGCCACGGCGTGGCAGTTGAGCGCGGCAATCAACCCAAGATCATGGGCTGGTCGCGGTTTCGCCACGG
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJG
```

However, my output file still contains all 3 sequences and returns:

Reading fastq file 100%  
3 sequences kept (of which 0 truncated), 0 sequences discarded.

I'm using vsearch v2.0.2_osx_x86_64.

Thanks a lot for your help,
Greet

**Comment by torognes** [comment]
Hi

The general options `minseqlength` and `maxseqlength` does not apply to the `fastq_filter` command. You may use the `fastq_minlen` option to specify the minimum length to `fastq_filter`, but there is no option for specifying the maximum length. There is an option for truncation sequences though, `fastq_trunclen`. These options are made for compatibility with usearch.

Sorry for the late reply, I've been on vacation.

**Comment by GreetDB** [comment]
Thanks a lot for your reply! However, as the effect of combining fastq_minlen and fastq_trunclen is not exactly the same as specifying a minseqlength and maxseqlength, I would find it useful if we can also apply the options minseqlength and maxseqlength to the fastq_filter in the future.

**Comment by torognes** [comment]
The --fastq_minlen and --fastq_maxlen options are now available with fastx_filter and fastq_filter in version 2.1.0 just released.

**Comment by GreetDB** [comment]
thanks!
