### ISSUE TITLE
Filtering options for fastA sequences also

### ISSUE THREAD

**Issue by tobiasgf** [torognes/vsearch#190]
I would very much like to have some of the options available for fastq_filtering available also for filtering fastA sequences. 
Especially I would like to be able to filter fasta files with these options (from fastq_filter)
--fastq_maxns INT
--fastq_minlen INT
--fastq_stripleft INT
--fastq_trunclen INT

Would that be possible to implement (or maybe the options do exist, and I just can figure it out?)

Kind regards
Tobias

**Comment by torognes** [comment]
Thanks for your suggestion. You can use the `--minseqlen` option to exclude short sequences (similar to --fastq_minlen), for instance while you run a sort command. There are no equivalents of the other commands. I will try to add these in a future release.

**Comment by tobiasgf** [comment]
Great :-)

**Comment by torognes** [comment]
These options are available with the fastx_filter command available in version 2.1.0 just released.
