### ISSUE TITLE
typo in the manual

### ISSUE THREAD

**Issue by nikosdarzentas** [torognes/vsearch#191]
"--quiet Suppress all output to **stdout** and **stdout** except for warnings and fatal error messages."

...there should be "stderr" there, right?

**Comment by torognes** [comment]
Thanks! You're right. Will be fixed in next release.

**Comment by frederic-mahe** [comment]
Fixed in the repository version, waiting for an official release.

**Comment by torognes** [comment]
Fixed in vsearch version 2.0.4 just released.
