### ISSUE TITLE
Improve documentation of fastq_stats and fastq_eestats

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#192]
We need to document these options.

For usearch documentation, please see:

http://www.drive5.com/usearch/manual/cmd_fastq_stats.html
http://www.drive5.com/usearch/manual/cmd_fastq_eestats.html

**Comment by frederic-mahe** [comment]
OK. The output of `--fastq_stats` and  `--fastq_eestats` are now documented in the manual. Some concepts, like expected errors, are not explained but a man page might not be the ideal place for that.

Besides the expected typo corrections and text polishing, I think the task is done and we can now close that issue.

**Comment by colinbrislawn** [comment]
I'm interested in contributing documentation, say writing a wiki page about Expected Error filtering. If you are currently accepting submissions, I'm willing to submit a draft.

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn , if you are willing to write some documentation we could add it to vsearch's wiki and properly credit you.

Thanks for the offer.

**Comment by colinbrislawn** [comment]
I'm working on a draft, but am not sure how to share it or get your feedback, as [github wikis don't allow pull requests]( https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github).

What works for you. Maybe I could post a gist?

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn ,

what about you post it here, as a comment to that issue? If you used markdown format, things should be OK. We can discuss the draft here, edit it, and then push it in thee wiki.

I am a bit at a cross-road here. So far, vsearch is documented mostly through its man page. Man pages are meant to be very technical, quick reference documents for already-savvy people. There is also probably a need for a more user-friendly documentation. GitHub's wiki could be used for that but the wiki is a bit hard to find, and I have the feeling that few people read it.

Being a user of the GNU tools, I am tempted to add a texinfo file in `vseach/man/` that could be a sort of companion book. The texinfo syntax is easier than the groff syntax and more people should be able to submit patches and pull requests to that doc. But texinfo would add a dependency to third-party tools (`makeinfo` and `tex`), so I am open to other formats.

Nonetheless, I have to admit, this is not a priority. It is already difficult for me to keep up with vsearch's manpage: there are a lot of small defaults and missing information I've spotted in the man page that I still have to input. Writing independent tests for the different vsearch functionalities is also more important right now. With the growth of vsearch's user-base, I want to make absolutely sure that our tool behaves as expected.

**Comment by colinbrislawn** [comment]
I've posted it as a gist, that way you can comment on specific lines. It's still pretty rough... 
https://gist.github.com/colinbrislawn/278265c4a4c2247a966da969d74c7ec1 

I completely understand the challenge of supporting software used by technical and non-technical folks. Providing documentation for both audiences, in a form that works for them, is time consuming but makes the software so much better for both audiences. I think part of the success of USEARCH was that Edar provided detailed `man` pages with the executable, as well a blog-like website, discussing the program and providing example commands. Qiime and mother take this one step further, also providing tutorials and support forums.

I'm on the non-technicla side of the GNU tools: I would much rather google for a command and hope someone has answered my question on Stackexchange, than read the `man` page to find the four flags I need and divine their interaction. If you are willing to provide feedback, I would like to contribute the non-technical documentation so you can focus on technical parts.
