### ISSUE TITLE
Add option to write non-chosen subsamples to a separate file

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#193]
A user asked: When doing subsampling, is there a way to take those samples not chosen in the random subsample and write those to a separate file?

**Comment by frederic-mahe** [comment]
Provided that we understand correctly what the user asked, I think it could be useful if a user wants to split a dataset in two non-overlapping subsets. The two subsets can be even in size (`--sample_pct 50.0`) or uneven in all other cases.

**Comment by torognes** [comment]
I guess it is partly explained in this qiime forum post and the figure.

https://groups.google.com/forum/#!searchin/qiime-forum/vsearch$20equivalent$20to$20pick_open_reference_otus%7Csort:relevance/qiime-forum/4Wymjmfgdw8/YO4nvMyLCwAJ

**Comment by ConstantinoSchillebeeckx** [comment]
@frederic-mahe that's right; it could be convenient to write the subsampled reads into one file, and all the remaining reads into another.

**Comment by torognes** [comment]
This feature is now available in vsearch version 2.0.5, just released. The options `--fastaout_discarded` and `--fastqout_discarded` are available to specify the file names to which the non-chosen sequences are written. Abundances are taken into account if `--sizein` is specified.
