### ISSUE TITLE
--fastq_stats fails on fastq files with an offset of +64?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#194]
Hi,

using the fastq test suite, I observe that
```sh
vsearch --fastq_chars illumina_full_range_original_illumina.fastq
```
works OK (guess: `--fastq_ascii 64`), while 
```sh
vsearch --fastq_stats illumina_full_range_original_illumina.fastq
vsearch --fastq_stats illumina_full_range_original_illumina.fastq --fastq_ascii 64
vsearch --fastq_stats illumina_full_range_original_illumina.fastq --fastq_ascii 33
```
fails with an error message:
```
vsearch v2.0.0_linux_x86_64, 15.6GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading fastq file 0%

Fatal error: FASTQ quality value out of range
```
Maybe a bug in `--fastq_stats` when working with fastq+64 files?

**Comment by torognes** [comment]
This is not a bug, but a feature. The quality value range in these files are wider than usual. You therefore have to specify the option `--fastq_qmax 62`. This is indicated when you run the fastq_chars command:

```
box:data torognes$ vsearch --fastq_chars illumina_full_range_original_illumina.fastq 
vsearch v2.0.3_osx_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading fastq file 100%  
Read 2 sequences.
Qmin 64, QMax 126, Range 63
Guess: -fastq_qmin 0 -fastq_qmax 62 -fastq_ascii 64
Guess: Illumina 1.3+ format (phred+64)
```

Usually the quality values are in the range 0 to 41, but in some cases (full range), the values may be higher. You then have to adjust the upper end of the range with the `--fastq_qmax` option. This is similar to usearch. We could increase the default value, but these higher values are rarely used in ordinary files. Increasing the value would also make it more difficult to detect whether the file was really a +33 or +64 type of FASTQ file.

**Comment by torognes** [comment]
The error message could be more informative though.

**Comment by frederic-mahe** [comment]
Thanks for the clarification. How would you change the error message? like that?
```
Fatal error: FASTQ quality value out of range
(qmax is 62 instead of 41. For a complete diagnosis, please try vsearch --fastq_chars file)
```

**Comment by torognes** [comment]
Something like that, yes. But vsearch stops at the first quality value found outside the range, and there might be even higher values later in the file. Also, this error message may occur if a wrong --fastq_ascii values has been specified, so the message may have to be more open.

Perhaps like this?

```
Fatal error: FASTQ quality value (62) out of range (0-41). Please adjust the FASTQ quality
base character and range with the --fastq_ascii, --fastq_qmin and --fastq_qmax options.
For a complete diagnosis with suggested values, please run vsearch --fastq_chars file.
```

**Comment by frederic-mahe** [comment]
That's very good! I would have known what to do Yesterday if I'd received that message.

To be extra-picky, shouldn't the fatal error message and the information message be on two separated lines?

**Comment by torognes** [comment]
Fine, then it could be like this:

```
Fatal error: FASTQ quality value (62) out of range (0-41).
Please adjust the FASTQ quality base character or range with the
--fastq_ascii, --fastq_qmin or --fastq_qmax options. For a complete
diagnosis with suggested values, please run vsearch --fastq_chars file.
```

**Comment by frederic-mahe** [comment]
That would solve issue #174 too.

**Comment by torognes** [comment]
Error message improved in vsearch version 2.0.4 just released.
