### ISSUE TITLE
redundancy in read searching

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [torognes/vsearch#195]
If I understood things correctly, in a 16S pipeline I might to the following:

1.  sort input reads
2. derep input reads (keep size annotation)
3. search against a reference database (e.g. Green Genes) to define OTU clusters
4. use the original input reads (not dereplicated) against my OTU clusters from step 3 to generate a .uc file
5. use `biom from-uc` to generate an OTU table

I'm confused about the need for step 4; since the input of step 3 already contains size annotation data, isn't step 4 redundant?  I mean, if a particular read derepilcates to size X, and matches a Green Genes read Y, doesn't that mean OTU Y has X reads?  Wouldn't it be more efficient to take the size-annotation data of step3 and count those as the abundance of a particular read?

For reference, I'm using `vsearch` to duplicate the [`pick_open_reference_otus`](http://qiime.org/scripts/pick_open_reference_otus.html) steps of QIIME (see [Gist](https://gist.github.com/ConstantinoSchillebeeckx/cc04cd8d9fb13a9fa01323153089513c)); this final search step requires the majority of my computational time.

**Comment by colinbrislawn** [comment]
Great question @ConstantinoSchillebeeckx,

> isn't step 4 redundant?

Nope. I makes up for data _lost_ in step 2. 

>I mean, if a particular read derepilcates to size X, and matches a Green Genes read Y, doesn't that mean OTU Y has X reads? 

That is correct, but how many of those X reads are in each sample? If your input seqs.fna file comes from only one sample, then the size annotations from step 2. are indeed the abundance of reads in that one sample. However, most data sets consistent of many samples, and the size annotation in step 2 refers to the abundance of that read _across_ samples. During step 4, you map your seqs.fna reads that are demultiplexed with (qiime) labels, and this gives you the abundance of OTUs in individual samples, while dereplication gives you abundance of OTUs in the full study.

**Comment by ConstantinoSchillebeeckx** [comment]
> and the size annotation in step 2 refers to the abundance of that read across samples

Ah yes, that's the part I was missing - that makes perfect sense.  Thanks Colin!
