### ISSUE TITLE
Document the UC format in the manpage

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#196]
The `--uc` option is available for clustering, dereplication and searching. Writing a definition for each command should make it easier to understand for end-users. As of now, the definition looks like that:
```
--uc filename
Output searching results in filename using a uclust-like format. For a description of the
format, see <http://www.drive5.com/usearch/manual/ucout.html>. Output order may
vary when using multiple threads.
```

**Comment by frederic-mahe** [comment]
Done for clustering. The uc output for other commands is a bit more complicated. I will need a few more days to document it properly.

**Comment by torognes** [comment]
The output is basically the same for the other commands, but the cluster number in the second column is the target number (i.e. the sequential sequence number in the file, zero-based) instead of the cluster number. Think of each sequence as a separate cluster.

**Comment by frederic-mahe** [comment]
Thanks, it makes sense. I pushed the last commits. uc output is now documented.
