### ISSUE TITLE
Extend --fastx_subsample to support FASTQ files

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#197]
The `fastx_subsample` command only accepts fasta files. Usearch can subsample fasta and fastq files.

**Comment by torognes** [comment]
It does accept fastq files, but information about it is lacking in the manual. The following relevant options are supported: `--fastqout`, `--fastq_qmin`, `--fastq_qmax`, `--fastq_ascii`. Sorry for not making this clear earlier.

**Comment by frederic-mahe** [comment]
Good! I just have to update the manual then.

**Comment by torognes** [comment]
Fixed in version 2.1.0 just released.
