### ISSUE TITLE
--top_hits_only limited to --matched instead of also --dbmatched

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [torognes/vsearch#199]
I'm running a `--usearch_global` with `--maxaccepts 50 --maxrejects 0` at `--id 97`; I'm interested in only the top hits and am outputting `--dbmatched` for further downstream steps.  

With the current settings, I'm getting more reads in the output `--dbmatched` than are in my input reads - I'm assuming this comes from the fact that the `--top_hits_only` flag only applies to the `--matched` output instead of the `--dbmatched`? 

When I also output `--matched` I can confirm that there are only as many reads in the output as there are in the input (1:1 number of reads since only outputting top hit).

Does it makes sense to have the `--top_hits_only` flag also apply to the `--dbmatched`?  

Documentation could be a bit more precise about this as well.  Thanks!

**Comment by torognes** [comment]
You are right. The `--top_hits_only` option does not apply to `--dbmatched`. It applies to the other output options, `--alnout`, `--samout`, `--userout`, `--blast6out`, `--uc`, `--fastapairs`, `--matched` and `--notmatched`, but not to `--dbmatched` and `--dbnotmatched`. This behaviour seems to be similar to usearch version 7. In contrast, usearch version 8 seems to ignore the `--top_hits_only` option.

I agree that it would be more logical that it applied to all output. However, we also aim for compatibility with usearch. Therefore, I am not sure if we should change it.

We could anyway improve the documentation of the `--top_hits_only` option.

**Comment by torognes** [comment]
What the `--top_hits_only`option does is to only output (to the files specified above) the hit with the highest similarity to the query (in terms of percent identity, given the chosen definition) as well as the other hits that have exactly the same similarity. Only the accepted hits are considered so the `--maxaccepts` option must be specified with an argument larger than 1. If the top hit is 100% identical, all other accepted hits with 100% similarity will be shown as well. Any accepted hit with e.g. 99.7% identity will not be included.

**Comment by frederic-mahe** [comment]
Hi,

I updated the documentation:
```
              --top_hits_only
                       Only  the  top  hits  between  the  query  and database
                       sequence sets are written to the output specified  with
                       the options --alnout, --samout, --userout, --blast6out,
                       --uc, --fastapairs, --matched or --notmatched (but  not
                       --dbmatched  and  --dbnotmatched).  For each query, the
                       top hit is the one presenting the highest percentage of
                       identity  (see  the  --iddef  option  to change the way
                       identity is measured). For a given  query,  if  several
                       top  hits  present exactly the same percentage of iden‐
                       tity, the number of hits reported is controlled by  the
                       --maxaccepts value (1 by default).
```
What do you think?

**Comment by torognes** [comment]
Sound good. Unfortunately I just released a new version with the first half of this text included.

**Comment by frederic-mahe** [comment]
No problem, I pushed a new commit.

**Comment by ConstantinoSchillebeeckx** [comment]
Thanks for all the info everyone - I suppose a quick workaround for me would be to dereplicate the `--dbmatched` output.

**Comment by torognes** [comment]
As a workaround you could get the identifiers of the target sequences using the `--userout` and `--userfields target` options and then extract those sequences from the database. Another alternative would be to use the `--fastapairs` option, remove the query sequence(s) (every odd-numbered sequence) and then dereplicate it.

Ideally, there should be a new option to change the behaviour to the more sensible kind here and drop compatibility.
