### ISSUE TITLE
--fastq_trunclen and discarded sequences

### ISSUE THREAD

**Issue by nikosdarzentas** [torognes/vsearch#203]
Hello all,

I used --fastq_trunclen to ...truncate FASTQ files, and it works as advertised, but the discarding of shorter sequences can be an issue downstream, since e.g. R1 and R2 files may end up unbalanced. You can save discarded sequences, but then putting them back in in the right order is 1-2 extra steps.

Firstly, is there a way that I missed to control this discarding? If not, I believe it'd be useful.

Thank you for VSEARCH.

**Comment by torognes** [comment]
I think I understand your problem, but I am not quite sure. You would like to truncate sequences to a specific length, right? But then you would like an option to keep the sequences that are too short instead of discarding them? I do not think the is possible now, but I see the use for it.

**Comment by nikosdarzentas** [comment]
Yes, you got it.

I used awk in the end, and as I implied it's even relatively easy to save and append the discarded (although you need to reorder/sync the FASTQs for most purposes), but it'd be great if it was internally controlled.  Just my two pence for this very useful tool.

Many thanks.

**Comment by torognes** [comment]
I've added a `--fastq_trunclen_keep` option that works like `--fastq_trunclen` except that it does not discard shorter sequences. It is available in vsearch version 2.3.0 just released.

**Comment by nikosdarzentas** [comment]
Great, thanks.

**Comment by frederic-mahe** [comment]
Hi @torognes, the `--fastq_trunclen_keep` option is documented in the manpage, but not in `vsearch -h`.

**Comment by torognes** [comment]
Fixed.
