### ISSUE TITLE
Fatal error when reading ncbi-nr

### ISSUE THREAD

**Issue by dturaev** [torognes/vsearch#206]
Problem description: Reading in the nr-database for an exact search, vsearch stops at 99% with the message "Fatal error: illegal character '-' on line 579257666 in fasta file".

**Comment by torognes** [comment]
VSEARCH does not allow the character "-" in the sequences. You need to remove that symbol from the sequence.

Please note that VSEARCH does not work with amino acid sequences. The NCBI nr database usually refers to the NCBI non-redundant protein database (usually called nr), but it may in some cases (at least earlier) refer to the NCBI non-redundant nucleotide database (usually called nt).

**Comment by dturaev** [comment]
Thanks. Sorry, I didn't realize vsearch doesn't work with amino acids.
