### ISSUE TITLE
dereplication option suggestion 

### ISSUE THREAD

**Issue by dridk** [torognes/vsearch#208]
I would like to dereplicate/rereplicate reads using sample information. For instance we can merge sample name like this : 

```
> sample=A
ACGTTT 
>sample=B
ACGTTT
```

Become : 

```
> sample=A,B;size=2
ACGTTT
```

Or maybe create an output file which contains all the necessary to rereplicate. 

```
vsearch dereplicate file.fa --sample sample.txt 

vsearch rereplicate file.fa --sample sample.txt
```

**Comment by frederic-mahe** [comment]
Hi @dridk,

If I may suggest a different approach. On each individual sample file, you can use `vsearch` to dereplicate and relabel the sequences `--relabel_md5`. Something like:
```sh
for f in *.fasta ; do
vsearch \
    --derep_fulllength "${f}" \
    --relabel_md5 \
    --sizeout \
    --fasta_width 0 \
    --output "${f}_dereplicated"
done
```
Then, you can dereplicate globally:
```sh
vsearch \
    --derep_fulllength <(cat *.fasta_dereplicated) \
    --sizein \
    --sizeout \
    --fasta_width 0 \
    --output all_samples.fasta
```
and you can build a mapping file (amplicon - sample relation):
```sh
grep "^>" *.fasta_dereplicated | \
    sed 's/.fasta_dereplicated:>/\t/ ; s/;size=/\t/ ; s/;$//' > mapping.table
```
After clustering, it is now trivial---with some python or perl mapping---to find out in which samples your amplicons occur (identical reads always get the same hash value). In general, replacing sequencer-produced read names with sequence hash values (md5 or sha1) makes a lot of sense and allows for quick sample comparisons across studies and for very efficient OTU mapping.

**Comment by dridk** [comment]
Ok! I think I understood ! It's not really trivial, but it seems the best approch to do dereplication with many sample. 
Thanks!

**Comment by frederic-mahe** [comment]
Well, maybe I exaggerated when I wrote "trivial". Let's say that if you are familiar with perl arrays or python dict, it is rather straightforward to parse the `mapping.table`.
