### ISSUE TITLE
An error when running v2.30

### ISSUE THREAD

**Issue by ZeweiSong** [torognes/vsearch#209]
I got an error when running VSEARCH v2.30
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

However, V2.10 is running fine. Do I missing anything in my environment?

Thanks!

**Comment by xflouris** [comment]
Hi @ZeweiSong , thanks for the report.
I have the same problem with the pre-compiled binary. It seems vsearch links to a newer c++ library than the v3.4 that is available on most systems. One solution before this is fixed, is to compile vsearch from source by following the instructions in the [README](https://github.com/torognes/vsearch/blob/master/README.md)

@torognes : perhaps a `-static` will fix the issue?

**Comment by torognes** [comment]
Thanks for reporting the problem. I have compiled vsearch again with gcc version 4.9.2 and updated the vsearch 2.3.0 linux release. The error message should be gone. I will compile with this version of gcc when I make new releases in the future.
