### ISSUE TITLE
gapopen and gapext - effect as expected?

### ISSUE THREAD

**Issue by tobiasgf** [torognes/vsearch#211]
Hello

I have two sequences (see below). They are identical except a large gap in the first.

I do a usearch_global with the ungapped as reference database.
`vsearch --usearch_global gapped.fasta --db ungapped.fasta --gapopen 2 --gapext 30 --id .40 --iddef 1 --userout out.txt -userfields query+target+id --query_cov .6
`

It seems that no matter what I set the "gapext" to (e.g. 1,2,200 or 20000) , I get the same id% in the output. I get a slight variation by changing "gapopen", but less than I would expect. 
Am I doing something wrong?

-Tobias
(using vsearch v2.1.2_linux_x86_64)

>gapped
TGCAGAATCCCGTGAATCATCGAGTCTTTGAACGCAAGTTGCGCCCGACGCCATTCGGCCGAGGGCACGTCTGCCTGGGTGTCACGCACCGTTGCCCCCAAACGCCCCCGCCTCGCAAGGGGCCCACGAGAGCGCCACGACAATCGGTGGTTGATTAGACCTCGGTCCCCGTCGTGCGTGTCTGGTCGCCACAAGGTGTGACTCGTCGACCCTAACGCGTCGTACCCACGTCGCTCCCAACGCGACCCCAGGTCAGGCGGGACTACCCGCTGAGTTTAA

>ungapped
TGCAGAATCCCGTGAATCATCGAGTCTTTGAACGCAAGTTGCGCCCGACGCCATTCGGCCGAGGGCACGTCTGCCTGGGTGTCACGCACCGTTGCCCCCAAACGCCCCCGCCTCGCAAGGGGCGCGGGATCTCGTTTGGTGGCGGAAGTTGGCCTCCCGTGGGCTTGTGCTCGCGGTTAGCCTAAAAAGGAGTCCTCGGCGACGAGCGCCACGAGAGCGCCACGACAATCGGTGGTTGATTAGACCTCGGTCCCCGTCGTGCGTGTCTGGTCGCCACAAGGTGTGACTCGTCGACCCTAACGCGTCGTACCCACGTCGCTCCCAACGCGACCCCAGGTCAGGCGGGACTACCCGCTGAGTTTAA

**Comment by torognes** [comment]
I think you need to adjust the gap opening penalty to change the alignment. The inserted bases have to be somewhere in the alignment, so adjusting only the gap extension penalty does not make much difference, as the total number of inserted bases is fixed. When you increase the gap open penalty however, the gaps will be fewer and longer.

The identity percentage will stay at 76.6% anyway. The long sequence is 364bp long and the short one is 279bp long. There will always be 85 gap symbols and the rest will match perfectly. The similarity will therefore be 100%*279/364=76.6%.

You can see the alignment if you use the `--alnout FILENAME` option.
