### ISSUE TITLE
forbidden internal gap

### ISSUE THREAD

**Issue by zmaya** [torognes/vsearch#212]
I run vsearch (last ver) with this parameters:

./vsearch --id 0.053 --usersort --cluster_smallmem INPUTFILENAME --minseqlength 3 --gapopen *I/0E --gapext *I/12E --msaout OUTPUTFILENAME

The program does open internal gaps although it should be forbidden (by stating '*I'). I attach the example files in which you can see this phenomenon.

Hope for prompt fixing the bug.

Thank you.

 
[TDP43_hg19_iCLIP_Kmers_M5_id0.553_vcl.txt](https://github.com/torognes/vsearch/files/589993/TDP43_hg19_iCLIP_Kmers_M5_id0.553_vcl.txt)

[TDP43_hg19_iCLIP_Kmers_M5_id0.553_fasta.txt](https://github.com/torognes/vsearch/files/589998/TDP43_hg19_iCLIP_Kmers_M5_id0.553_fasta.txt)

**Comment by zmaya** [comment]
I run vsearch (last ver) with this parameters:

./vsearch --id 0.053 --usersort --cluster_smallmem INPUTFILENAME --minseqlength 3 --gapopen *I/0E --gapext *I/12E --msaout OUTPUTFILENAME

If input sequences for clustering (my kmers) has length 8, 9 and longer, no matter what parameter of vsearch I change ( gaps or id ), the result stays the same and each sequence (kmer) is clustered separately.

Hope for prompt fixing the bug.

Thank you.

[TDP43_hg19_iCLIP_Kmers_M8_id0.646_vcl.txt](https://github.com/torognes/vsearch/files/590012/TDP43_hg19_iCLIP_Kmers_M8_id0.646_vcl.txt)
[LIN28A_hg19_PARCLIP_Kmers_M10_id0.684_vcl.txt](https://github.com/torognes/vsearch/files/590013/LIN28A_hg19_PARCLIP_Kmers_M10_id0.684_vcl.txt)
[TDP43_hg19_iCLIP_Kmers_M8_id0.646_fasta.txt](https://github.com/torognes/vsearch/files/590015/TDP43_hg19_iCLIP_Kmers_M8_id0.646_fasta.txt)
[LIN28A_hg19_PARCLIP_Kmers_M10_id0.684_fasta.txt](https://github.com/torognes/vsearch/files/590016/LIN28A_hg19_PARCLIP_Kmers_M10_id0.684_fasta.txt)

**Comment by zmaya** [comment]
I run vsearch (last ver) with this parameters:

./vsearch --id X --usersort --cluster_smallmem INPUTFILENAME --minseqlength 3 --gapopen *I/0E --gapext *I/12E --msaout OUTPUTFILENAME

Descriptions of input fasta file looks different in result files after clustering. Part of information is missing. For example in input .fasta file description of the sequence >ATTTT 630 989
In output result file just >ATTTT

[TDP43_hg19_iCLIP_Kmers_M8_id0.646_fasta.txt](https://github.com/torognes/vsearch/files/590057/TDP43_hg19_iCLIP_Kmers_M8_id0.646_fasta.txt)
[TDP43_hg19_iCLIP_Kmers_M8_id0.646_vcl.txt](https://github.com/torognes/vsearch/files/590061/TDP43_hg19_iCLIP_Kmers_M8_id0.646_vcl.txt)

**Comment by torognes** [comment]
I have opened separate issues #213 and #214 for the first two problems.

The last problem can be solved by specifiying the `--notrunclabels` option.
