### ISSUE TITLE
--top_hits_only reports only one top hit

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#215]
Good morning,

The [manual for --top_hits_only says](https://github.com/torognes/vsearch/blob/master/man/vsearch.1#L1882-L1884) 

>For a given query, if several top hits
present exactly the same percentage of identity, the number of hits
reported is controlled by the \-\-maxaccepts value (1 by default).

When I run this command, only one hit is returned. 
```
vsearch -usearch_global $otus -db $ref -uc $out/map.70.uc \
-strand both -id 0.70 -top_hits_only --maxaccepts 8 
```

When I replace `-top_hits_only` with `-uc_allhits`, I get all 8 hits and I can see that some have exactly the same percentage identity, but are not being returned.

I'm trying to get all hits that are tried for first place, just like it says in the manual.

**Comment by colinbrislawn** [comment]
Looks like @frederic-mahe [has had this issue too](https://github.com/torognes/vsearch/issues/34):

>the idea of using `top_hits_only` and `--maxaccepts 0` is to be sure to find all best matches: if there are 250 target sequences 100% identical to my query sequence, I want to get all of them in the output.

**Comment by torognes** [comment]
Thanks for reporting this problem.

VSEARCH seems to work as intended in my hands.

You may have to set a high value for `--maxrejects` as well, perhaps 1000. Or 0 to consider all.

Please note that If one sequence is 99.14% identical and the other is 99.06% identical only the first will be shown, even if both are shown as 99.1% identical.

Could you provide some example data if it still does not work correctly?

**Comment by colinbrislawn** [comment]
Thank you for the feedback. This command works for me: 

>vsearch -usearch_global query.fna -db db.fna \
-strand both -id 0.90 -threads 1 --maxaccepts 0 --maxrejects 0 \
**-top_hits_only -uc_allhits** \
-output_no_hits -uc map_top.uc

When writing this, I did not know both `--top_hits_only` and `--uc_allhits` could be passed at the same time. I now understand that `--uc_allhits` will show more than just the top hit, and `--top_hits_only` will only show those tied with the top hit.

Thank you for your time!
Colin
