### ISSUE TITLE
Use "=" in column 8 of uc files with perfect alignment also when ignoring terminal gaps

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#216]
USEARCH 6 and 7 uses a "=" in column 8 on H-lines of UC files with perfect alignments, also when ignoring terminal gaps. USEARCH 8 seems to only use "=" when the alignment is perfect and does not ignore terminal gaps. VSEARCH 2.3.2 seems to be similar to USEARCH 8. VSEARCH should probably be similar to USEARCH 7.

**Comment by frederic-mahe** [comment]
Hi @torognes,

the 3rd test of `test/unclassified.sh` was designed precisely to check that. As of now, it fails: terminal gaps should be ignored, but vsearch takes them into account.

**Comment by frederic-mahe** [comment]
That's related to issue #229

**Comment by torognes** [comment]
It seems like it is only for `cluster_fast` that usearch 6 and 7 puts a `=` in the UC file for identical sequence, ignoring terminal gaps. Other clustering or search commands takes terminal gaps into account and requires the sequences to be absolutely identical over their entire length.

**Comment by torognes** [comment]
Fixed in version 2.10.4, just released.
