### ISSUE TITLE
Ideas for potential improvement in accuracy or speed

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#217]
Instead of just counting the shared kmers between the query and each target sequence, one could possibly score them differently based on the overall frequency of the kmer in the set of target sequences. Rare kmers could get a higher score than frequent kmers. They could be scored on a scale from 1 to 8 or 1 to 16, for instance. Other classifiers based on word occurences usually do something like that.

**Comment by frederic-mahe** [comment]
It looks like an attempt to introduce a measure of entropy in our filtering. That sounds interesting.

The kmer frequencies are not evenly distributed, we might need to come up with a formula to convert frequencies and associated entropy values into a small set of integer values (0-255 ? a byte ?)

**Comment by torognes** [comment]
Yes, it is common to use the negative logarithm of the relative frequency, perhaps subject to some affine function.

Today we are only counting the number of matching kmers in each target sequence. We are using a 16-bit unsigned integer for this. This means that we are restricted to a maximum of 65535 matching kmers. That restricts the sequence length to about 65k or the wordlength (k) to 8.

But the storage could be increased to 32 bits, allowing longer sequences, longer wordlengths or a variable score for the different kmers.

**Comment by torognes** [comment]
Another possibility would be to allow one mismatch in the k-mers. A single kmer would then correspond to 1+3*k kmers with one mismatch, i.e. 25 if k=8. We might need to use longer kmers, e.g. k=9 or k=10. It might increase running time slightly, but should also boost accuracy.

**Comment by torognes** [comment]
I have investigated a bit the idea of using kmers with one mismatch. It seems not to be a good idea. Even though the total number of kmers is reduced when going from perfect kmers of length 8 to kmers of length 12 with one mismatch, the speed is also greatly reduced. I think this is due to memory/cache issues because we need to look up the kmer index in many more different regions, although the total amount of memory read is less. Also, the accuracy may actually decrease, because the perfect kmers and the near-perfect kmers are given the same weight or score, even though a perfect match is clearly much better than a match with one mismatch. Kmers of length 8 are already quite short.

**Comment by torognes** [comment]
OK!
