### ISSUE TITLE
clustering: profiles do not make sense

### ISSUE THREAD

**Issue by fgvieira** [torognes/vsearch#220]
Dear all,

What is the format of the -profiles output? According to the manual it is a TSV with:
> The columns are: position (1-based), consensus nucleotide, number of As, number of Cs, number of Gs, number of Ts or Us, and finally the number of gaps. If ambiguous nucleotide symbols are present, the numbers may be floating point numbers, otherwise they are integers. For instance, an ’R’ counts 0.5 towards an A and 0.5 towards a G.

I tried to run a small example with ten almost identical sequences (no gaps) but the output doesn't quite match. For example, for the first 10 bases the MSA is:
> TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
TGCAGGAGGG
>consensus
TGCAGGAGGG

but the profile is:
>centroid=SN767:466:C992GACXX:8:1101:10108:15697;seqs=10;size=10;
0       T       0       0       0       0.83    9.17
1       G       0       0       0       0       10
2       C       0.83    0       0       0       9.17
3       A       0       0.83    0       0       9.17
4       G       0       0       0.83    0       9.17
5       G       0       0       0       0       10
6       A       0       0       0.83    0       9.17
7       G       0       0       0       0       10
8       G       0.83    0       0       0       9.17
9       G       0.83    0       0       0       9.17
10      C       0       0       0       0       10

The consensus sequence is correct, but I cannot understand what the columns stand for.
thanks,

**Comment by torognes** [comment]
This looks really strange. I'll look into it soon. Thanks for reporting the issue.

**Comment by torognes** [comment]
Fixed code and documentation in version 2.3.4, just released.

The manual now reads:

> --profile filename
> Output a sequence profile to a text file with the frequency of each
> nucleotide in each position in the multiple alignment for each
> cluster. There is a FASTA-like header line for each cluster, followed
> by the profile information in a tab-separated format. The eight
> columns are: position (0-based), consensus nucleotide, number of As,
> number of Cs, number of Gs, number of Ts or Us, number of gap symbols,
> and finally the total number of ambiguous nucleotide symbols (B, D, H,
> K, M, N, R, S, Y, V or W). All numbers are integers.

Thanks again for reporting this bug.
