### ISSUE TITLE
Port VSEARCH to the POWER8 architecture

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#222]
We have received a request to port VSEARCH to the [POWER8](https://en.wikipedia.org/wiki/POWER8) architecture. This will include adding AltiVec replacements for the SIMD intrinsics.

**Comment by torognes** [comment]
The following issues must be fixed:
* SIMD code in cpu.cc
* SIMD code in align_simd.cc
* CPUID instruction in vsearch.cc
* Segfault in ps2pdf when converting manual to PDF

**Comment by frederic-mahe** [comment]
Hi @torognes, do you have access to a POWER8 computer to run tests?

**Comment by torognes** [comment]
Yes, I and Tomas have got access to a system at Center for Genome Research and Biocomputing at Oregon State University, USA. It can be used for development and testing. I have already been able to port nearly half of the relevant code.

**Comment by torognes** [comment]
Fixed in version 2.4.0 just released.
