### ISSUE TITLE
Qiime open reference does not work ?

### ISSUE THREAD

**Issue by ptranvan** [torognes/vsearch#224]
Hi I am trying to use Qiime open reference with `pick_open_reference_otus.py`.

But it fails at some step because it needs a fasta file with reads that doesn't match a reference sequence (failures.fasta).
My failures.fasta file is empty... is that a problem with vsearch ?

**Comment by colinbrislawn** [comment]
Hello Patrick,

I think this question could best be addressed on the [Qiime forums](https://groups.google.com/forum/#!forum/qiime-forum) or on the [Vsearch forums](https://groups.google.com/forum/#!forum/vsearch-forum). Have you considered posting your question over there?

Colin
