### ISSUE TITLE
fastq_eestats2 feature

### ISSUE THREAD

**Issue by vmikk** [torognes/vsearch#226]
Dear @torognes, 
It would be great if you could implement  [--fastq_eestats2](http://drive5.com/usearch/manual/cmd_fastq_eestats2.html) command in VSEARCH.
It’s very useful when one will want to determine how many reads will pass an expected error filter at different length thresholds.

Thank you,
Vladimir

**Comment by torognes** [comment]
Thank you for the suggestion. I'll try to add this command in the next release.

**Comment by torognes** [comment]
The `--fastq_eestats` command with the options `--ee_cutoffs` and `--length_cutoffs` has been added in the latest commit.

**Comment by torognes** [comment]
Fixed in version 2.5.0.
