### ISSUE TITLE
Overflow in fastq_stats with large FASTQ files

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#228]
It seems like an overflow may occur in fastq_stats and possibly related commands with large FASTQ files.

**Comment by torognes** [comment]
Files with more than 4G nucleotides or sequences may give incorrect results.

**Comment by torognes** [comment]
Fixed in version 2.4.1 just released.

**Comment by frederic-mahe** [comment]
Hi @torognes,

I've been trying to trigger an overflow on vsearch 2.4.0, at least with a number of nucleotides greater than 2^32, but the output is correct: `4731.5M  Bases`. Any advice on writing a test for that bug?
