### ISSUE TITLE
Using Vsearch to produce a consensus OTU table from non-overlapping reads

### ISSUE THREAD

**Issue by slvrshot** [torognes/vsearch#230]
Hi @torognes I was wondering if it was possible to use Vsearch in such a way as to generate a consensus OTU table from non-overlapping reads. A little background...We have HiSeq data for a microbial based project and instead of using one read or the other we would like to generate an OTU table that only makes counts if both Reads have sequences for a particular OTU. If only one Read detects an OTU we would like to discard that data. Is this possible? Thanks!

**Comment by torognes** [comment]
I am sorry, but I do not think this is possible with vsearch now.
