### ISSUE TITLE
Recording query reads that fail to cluster as "N" or "No hit"

### ISSUE THREAD

**Issue by walterst** [torognes/vsearch#232]
Hello,

Should vsearch be recording sequences that fail to match the reference at the given identity specified with --id X as a "N" sequence in the output .uc file?

Example command (tried with 2.4.2 and older, v1.8.1 vsearch):
vsearch --usearch_global query_fasta -db reference_fasta --uc uc_file_output --id 0.97

This was attempted with the usearch61 software, with this command on the same files:
usearch6.1.544_i86linux32 --usearch_global abundance_sorted.fna -db /ebio/abt3_projects/Georg_animal_feces/data/SILVA_128/SILVA_128_QIIME_release/rep_set/rep_set_all/90/90_otus.fasta --uc test_usearch61hits.uc --id 0.97 --strand plus

In the output .uc file, the reads that fail to match look something like this:
N	*	*	*	.	*	*	*	416.White.Rhinoceros_6670652;size=3;	*
But these appear to not be written to the vsearch output.

QIIME parses out the failures by looking for "N" lines, so it fails to detect the clustering failures.

**Comment by torognes** [comment]
Hi @walterst 

You are right, vsearch by default does not write N-lines to the uc file when there are no hits. It should. If you add the `--output_no_hits` option to vsearch it will write those lines. But it should not be necessary, as described here:

http://drive5.com/usearch/manual/opt_output_no_hits.html

Thanks for reporting this bug. I will fix it asap and release a new version.

**Comment by torognes** [comment]
The issue has been fixed in version 2.4.3 just released.
