### ISSUE TITLE
Can we have a function of write to standard output and error

### ISSUE THREAD

**Issue by ZeweiSong** [torognes/vsearch#235]
Hi, 

I was trying to use ">" and ">>" to put the output report to a text file, but vsearch still output everything on screen.

I noticed that there is an "--log" option, but it does not include any report information.

Is it possible to have a "--report" option so we can save the report in a file instead of on screen?

Thanks!

**Comment by frederic-mahe** [comment]
Hi @ZeweiSong , have you try `vsearch [-options] 2> output.err` to capture the standard error?

**Comment by ZeweiSong** [comment]
Not yet. I’ll give it a try! Thanks!

--
Zewei Song
Postdoctoral Associate
University of Minnesota, Twin Cities
Department of Plant Pathology

Email: songzewei@outlook.com
Tel: 612-840-0267
Website: www.songzewei.org

**Comment by frederic-mahe** [comment]
some vsearch commands can write results to `--log file` or `--output file`, instead of `stderr`. For the other commands, use `2> file` to capture the `stderr` to a file.

I'll assume that solves the issue.
