### ISSUE TITLE
should --log capture the output of --fastq_chars?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#237]
Hi,
according to Torbjørn's comment, [when [--quiet] is in effect only errors or warnings should be printed to stderr.](https://github.com/torognes/vsearch/issues/50#issuecomment-67014924)

This is not the case for `--fastq_chars`:
```sh
vsearch --fastq_chars <(printf "@s\nAA\n+\nII\n") --quiet --log tmp
```
Results are still written to `stderr`, only version number and memory usage are written to the log file. The different versions of usearch write to both `stderr` and to the log file when `--log` is used, and only to the log file when `--quiet` is added.

If the goal is to avoid anything but errors on `stderr`, maybe the correct behavior should be as follows, at least for `--fastq_chars`:
```
 output/options  none              --log             --log & --quiet  
----------------------------------------------------------------------
 stderr          version & tables  version           -                
 log file        -                 version & tables  version & tables 
----------------------------------------------------------------------
```
What do you think?

**Comment by torognes** [comment]
I agree. As far as I remember, USEARCH used to do it the same way, but it has been corrected. I'll change it in VSEARCH.

**Comment by torognes** [comment]
Fixed. VSEARCH now prints to stderr unless the `--quiet` option is in effect, and to the log file if the `--log` option is used. It may write to both. This is similar to the other commands.

The special thing with this command is that it does not print anything to stdout or any dedicated output file.
