### ISSUE TITLE
Typo in warning message

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#240]
The `--shuffle` command reads fasta (and not fastq, for now). If given a fasta sequence with invalid characters, the command returns an error message:
```sh
vsearch --shuffle <(printf ">s\nAAAA;size=12") --output /dev/null --quiet
```
returns
```
WARNING: invalid characters stripped from fastq file: 1(1) 2(1) ;(1) =(1) e(1) i(1) z(1)
```
The message should say `fasta` instead of `fastq`.

**Comment by torognes** [comment]
Fixed.
