### ISSUE TITLE
what should average cluster size be when there are no clusters?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#241]
The toy example shows that `vsearch` currently returns `-nan`, where `nan` probably stands for not-a-number:
```sh
printf ">s1\nA\n" | vsearch --derep_fulllength - --output - 
vsearch v2.4.0_linux_x86_64, 62.8GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading file /dev/stdin 100%
0 nt in 0 seqs
WARNING: 1 sequences shorter than 32 nucleotides discarded.
Dereplicating 100%
Sorting 100%
0 unique sequences, avg cluster -nan, median 0, max 0
Writing output file 100%
```
Maybe `nan` instead of `-nan`? or could it be more explicit?

**Comment by torognes** [comment]
Perhaps it should just stop when there are no sequences to cluster and report "No sequences left to cluster.".

**Comment by frederic-mahe** [comment]
Sounds like a good idea.

**Comment by torognes** [comment]
I have chosen to just output "0 unique sequences" in this case and not report average, median or max.

A similar change is made to the clustering commands.
