### ISSUE TITLE
Add --relabel_ids option

### ISSUE THREAD

**Issue by fgvieira** [torognes/vsearch#242]
When dereplicating/clustering, it would be nice to have an option to relabel sequences with the concatenated IDs of all original sequences. If not as a sequence ID (list might be too long), at least as the sequence description.

For example, with an input:
>11
aaaaa
>12
aaaaa

give an output (e.g.):
>11:12
aaaaa

cheers,

**Comment by frederic-mahe** [comment]
In large datasets, certain sequences can be present more than a million times. What happens if a fasta header contains several million symbols?

**Comment by fgvieira** [comment]
Well, I guess that is up to the user.... After all, it is not a default option and needs to be specifically set.
And vsearch could output a warning message...

**Comment by torognes** [comment]
I do not think this is a feature that we will implement. Please not however the newly added `derep_id` command that may be helpful in some related circumstances.
