### ISSUE TITLE
link broken in README

### ISSUE THREAD

**Issue by rrohwer** [torognes/vsearch#246]
Hi, this is very minor but the "man page" link in the README is broken. It leads to a 404 page does not exist.

**Comment by colinbrislawn** [comment]
Good find! I think I've fixed it.

I wish they would post the PDF manual on the site as well. Do you think the devs would be OK with dropping [PDF from the gitignore](https://github.com/torognes/vsearch/blob/master/.gitignore#L3)?

**Comment by frederic-mahe** [comment]
thanks for reporting that dead link @rrohwer.

The PDF version of the manual is a binary object. So far, we've kept PDFs out of git's scope to avoid adding a new file-size binary blob to the repository each time the man page is modified. The idea is to keep vsearch's repository small by tracking only source files.

**Comment by torognes** [comment]
You can find the PDF of the manual in the releases:

https://github.com/torognes/vsearch/releases

For the latest version, you'll find it here:

https://github.com/torognes/vsearch/releases/download/v2.4.3/vsearch_manual.pdf
