### ISSUE TITLE
fastx_subsample: wrong error message when omiting --sample_pct or --sample_size

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#248]
The command `--fastx_subsample` expects either the option `--sample_pct` or the option `--sample_size`.
```sh
printf "@s1\nA\n+\nG\n@s2\nAA\n+\nHH\n@s3\nAA\n+\nII\n@s4\nGG\n+\nII" | \
    vsearch --fastx_subsample - --fastqout -
```
The error message is `Fatal error: Specify either --sample_pct or --sample_size, not both` where it should be `Fatal error: Specify either --sample_pct or --sample_size`.

**Comment by torognes** [comment]
Fixed.
