### ISSUE TITLE
change the warning message for discarded sequences?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#249]
```sh
printf '>a\nAA\n>b\nA\n' | vsearch --shuffle - --minseqlength 2 --output -                                  
```
```
vsearch v2.4.0_linux_x86_64, 62.8GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading file /dev/stdin 100%
2 nt in 1 seqs, min 2, max 2, avg 2
WARNING: 1 sequences shorter than 2 nucleotides discarded.
```
(bonus enhancement: if the number of sequence is 1, then print `sequence`, else print `sequences`)

Instead of using `WARNING`, the message could be `minseqlength 2: 1 sequence discarded`. It has the advantage to indicate to the user that a length-based filtering is applied by default by clustering, dereplication and searching commands (`--minseqlength 32`) when the option `--minseqlength` is not explicitly used.

**Comment by torognes** [comment]
Fixed. With bonus enhancement!
