### ISSUE TITLE
Implement --cons_truncate clustering output option

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#25]

**Comment by torognes** [comment]
Uncertain what the cons_truncate option really do. Closing issue.

**Comment by torognes** [comment]
See https://www.drive5.com/usearch/manual7/opt_consout.html

**Comment by torognes** [comment]
Indicates that terminal gaps should be taken into account when computing consensus sequences. By default, usearch does not, meaning that these gaps are ignored and the consensus is built from the other symbols in the columns. VSEARCH currently never handles terminal gaps differently from other gaps when computing the consensus. A user have asked for an option to choose the behaviour (see issue #86). Perhaps this should be updated.

**Comment by frederic-mahe** [comment]
I suggest to close the issue for now. `PotentialFuture` tag allows us to find and revisit that issue if need be.
