### ISSUE TITLE
vsearch help or version should return the latest vsearch publication

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#250]
Not every user is aware that there is a published reference for `vsearch`. To spread the message, the citation could be printed when using the options `-v` or `-h`. 
```sh
vsearch -v
```
should return
```
vsearch v2.4.3_linux_x86_64, 62.8GB RAM, 8 cores
https://github.com/torognes/vsearch

Rognes T, Flouri T, Nichols B, Quince C, Mahe F. (2016) VSEARCH: 
a versatile open source tool for metagenomics.  PeerJ 4:e2584
doi: 10.7717/peerj.2584 <https://doi.org/10.7717/peerj.2584>
```

**Comment by torognes** [comment]
Fixed.

**Comment by boopsboops** [comment]
At the moment, vsearch is not fully outputting `--version` to stderr. See:
`vsearch --version > file` 
`cat file`

The following text is missing from file:
"vsearch v2.14.2_linux_x86_64, 15.6GB RAM, 8 cores" 

Is it possible to add this in, so I can dump version numbers of pipeline software to disk and make a summary report.

Many thanks!
