### ISSUE TITLE
fastq_stats reports 4 possible truncation lengths for a read of length 3

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#251]
Hi @torognes, Etienne and I continue to write tests for the different vsearch commands. Could you please have a look at this one?
```sh
printf "@s1\nAAA\n+\n('&\n" | vsearch --fastq_stats - --log - 
```

```
vsearch v2.4.2_linux_x86_64, 7.7GB RAM, 8 cores
...
    L   1.0000   0.5000   0.2500   0.1000   1.0000   0.5000   0.2500   0.1000
-----  -------  -------  -------  -------  -------  -------  -------  -------
    4        1        0        0        0  100.00%    0.00%    0.00%    0.00%
    3        1        1        0        0  100.00%  100.00%    0.00%    0.00%
    2        1        1        1        0  100.00%  100.00%  100.00%    0.00%
    1        1        1        1        1  100.00%  100.00%  100.00%  100.00%
...
```
It does not seem useful to report truncation stats for lengths greater than the maximum read length. Maybe an offset error?

**Comment by torognes** [comment]
The lengths in the first column should be one smaller than indicated, and the last line is nonsense.

However, this is exactly how usearch presents it.

In this case it seems to make sense to fix a bug rather than keeping compatibility with usearch.

**Comment by torognes** [comment]
Fixed.
