### ISSUE TITLE
fastq_eestats computation of quartiles and median for even number of records?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#252]
Hi,

According to [Wikipedia](https://en.wikipedia.org/wiki/Median): "If there are an even number of observations, then there is no single middle value; the median is then usually defined to be the mean of the two middle values. [...] A median can be worked out for ranked but not numerical classes (e.g. working out a median grade when students are graded from A to F), although the result might be halfway between grades if there are an even number of cases."

The descriptive statistics produced by the `--fastq_eestats` command seem to follow the idea that quality values are like grades. No half grade values are computed for the the lower, median, and higher quartiles, but half grades can be returned for the mean. However, the behavior is not consistent between Q, Pe, and EE.

```sh
printf '@s1\nA\n+\n!\n@s2\nA\n+\n!\n@s3\nA\n+\n"\n@s4\nA\n+\n"\n' | \
    vsearch --fastq_eestats - --output - 2> /dev/null
```
In the example above, the four records (1-nucleotide long) have quality values of 0, 1, 2, and 3, corresponding to error probabilities of 1.0, 0.79, 0.63, 0.5.
```
Pos	Recs	PctRecs	Min_Q	Low_Q	Med_Q	Mean_Q	Hi_Q	Max_Q	Min_Pe	Low_Pe	Med_Pe	Mean_Pe	Hi_Pe	Max_Pe	Min_EE	Low_EE	Med_EE	Mean_EE	Hi_EE	Max_EE
1	4	100.0	0.0	0.0	1.0	1.5	2.0	3.0	0.5	0.63	0.79	0.73	1	1	0.50	0.50	0.63	0.73	0.79	1.00
```
Re-arranged:
```
     min   Qlo   Med   Qhi  max 
--------------------------------
 Q     0     0     1     2    3 
 Pe  0.5  0.63  0.79     1    1 
 EE  0.5   0.5  0.63  0.79    1 
```

Note that the `Med_Pe` and `Med_EE` values are not the same. Of the different methods available to compute quartiles (https://en.wikipedia.org/wiki/Quartile), which one is used here? It seems that the same method is used for both `Q` and `EE`, but not for `Pe`.

Once things will be clearer, and possibly harmonized, my plan is to add a sentence such as this one to the man page: "lower, median, and higher quartiles contain at most 25%, 50%, and 75% of ordered data points, respectively."

**Comment by torognes** [comment]
Actually none of the methods listed on the Wikipedia page is used.

VSEARCH first counts the number of nucleotides with the different quality scores at the different positions.

To find the different quartiles for `Q` at any specific position it starts at the lowest quality and then increases the quality until it has counted at least 25%, 50% or 75% of the nucleotides in that position.

A similar approach as with `Q` is used to find the `EE` value, but then with accumulated errors before and including the given position.

The value for Pe is found by just converting the found `Q` value to a probability.

This is a heuristic approach that should fairly accurate unless there are very few sequences. We do not take the average if there are two equally large groups and we do not split the set into two and then into four as described on Wikipedia.

USEARCH seems to do a similar thing but seems to require more than 25%, 50% and 75% of the nucleotides. Equal is not enough. Hence, values may be slightly higher, except for Pe which seems to be the same.

Perhaps the way the `Pe` is found should be changed to be similar to the others.

I am not sure if the sentence will be correct, perhaps "lower, median, and higher quartiles contain at least 25%, 50%, and 75% of the lowest data points, respectively" would be better.

**Comment by torognes** [comment]
Actually the method for computing the lower quartile, median and upper quartile of `Q` and `EE` in VSEARCH is similar to the way the 25%, 50% and 75% percentile is computed in the [nearest-rank method](https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method) described in the Wikipedia article about Percentile.

I can change the way the `Pe` value is computed to be consistent with this.

**Comment by torognes** [comment]
For the `EE` computations, VSEARCH also uses an approximation where the `EE` values are binned into 1000 bins and then counted. This is because the number of different possible `EE` values is so large. To avoid sorting them, they are just binned. The number of different `Q` or `Pe` values is rather small, usually just 42 possible values. This makes VSEARCH faster.

**Comment by torognes** [comment]
I have now changed the way the `Pe` values are computed, to be consistent with the other.
