### ISSUE TITLE
command allpairs_global should accept the output option fastapairs

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#255]
The example below fails with a non-informative error message:
```sh
printf '>seq1\nAAAAA\n>seq2\nAAAAA\n' | \
    vsearch --allpairs_global - --fastapairs - --id 0.5
```
```
Fatal error: No output files specified
```
`--fastapairs` is recognized as a valid option, but the commands `--allpairs_global` and `--search_exact` does not seem to recognize it. The man page says it should be recognized.

**Comment by torognes** [comment]
Fixed for allpairs_global, usearch_global and search_exact.
