### ISSUE TITLE
iddef, wrong definition for BLAST similarity?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#257]
The documentation says:

> --iddef 4: BLAST definition, equivalent to --iddef 2 in a context of global pairwise alignment.

in `searchcore.cc`, `--iddef 4` is coded as `--iddef 1`, not `--iddef 2`:
```cpp
  /* all diffs */
  hit->id1 = hit->nwalignmentlength > 0 ?
    100.0 * hit->matches / hit->nwalignmentlength : 0.0;
  /* internal diffs */
  hit->id2 = hit->internal_alignmentlength > 0 ?
    100.0 * hit->matches / hit->internal_alignmentlength : 0.0;
  /* BLAST */
  hit->id4 = hit->nwalignmentlength > 0 ?
    100.0 * hit->matches / hit->nwalignmentlength : 0.0;
```

**Comment by torognes** [comment]
The code is correct and the documentation is wrong. In the code, the `--iddef 4` and `--iddef 1` are equivalent. This is similar to USEARCH version 5.

**Comment by torognes** [comment]
Updated manual.
