### ISSUE TITLE
iddef, clarify the Marine Biological Lab definition

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#258]
Documentation says:

> Marine Biological Lab definition counting each extended gap (internal or terminal) as a single difference: 1.0 - [(mismatches + gaps)/(longest sequence length)]

It seems to me that the definition should read:

> Marine Biological Lab definition counting each gap opening (internal or terminal) as a single mismatch, whether or not the gap was extended: 1.0 - [(mismatches + gap openings)/(longest sequence length)]

**Comment by torognes** [comment]
Updated manual.
