### ISSUE TITLE
SAM format: wrong edit distance in optional tags

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#260]
```
     Optional tags AS, XN, XM, XO, XG, NM, MD and YT used in usearch8.
     
     AS:i:? alignment score (i.e percent identity)
     XN:i:? next best alignment score (always 0?)
     XM:i:? number of mismatches
     XO:i:? number of gap opens (excluding terminal gaps)
     XG:i:? number of gap extensions (excluding terminal gaps)
     NM:i:? edit distance (sum of XM and XG)
     MD:Z:? variant string
     YT:Z:UU string representing alignment type
```
`NM` (edit distance) is defined as the sum of mismatches `XM` and gap extensions `XG`, where it should be the sum of mismatches `XM`, gap extensions `XG` **and** gap opens `XO`, shouldn't it? Unless gap opens are included in mismatches, which does not seem to be the case.
```bash
vsearch \
    --usearch_global <(printf '>q1\nGGGGGGGGGGGG\n') \
    --db <(printf '>r1\nGGGGGCCCCGGGGGGG\n') \
    --id 0.1 \
    --quiet \
    --minseqlength 1 \
    --samout - \
    --alnout -
```
```
Qry  1 + ggggg----ggggggg 12
         |||||    |||||||
Tgt  1 + GGGGGCCCCGGGGGGG 16

16 cols, 12 ids (75.0%), 4 gaps (25.0%)
AS:i:75	XN:i:0	XM:i:0	XO:i:1	XG:i:4	NM:i:4	MD:Z:5^CCCC7	YT:Z:UU
```

**Comment by torognes** [comment]
I disagree. I think the edit distance should just include the number of mismatches and the number of alignment positions with a gap symbol. In the example there are 0 mismatches and 4 gap positions, so the total edit distance is 4. The edit distance is usually defined as the number of simple operations necessary to transform one string into another, where the operations usually allowed are single nucleotide substitutions, single nucleotide deletions, and single nucleotide insertions.

The edit distance (4 in this example) will usually be identical to the total alignment length (16 in this example) minus the number of matches (12 in this example).
