### ISSUE TITLE
consensus sequence as clustering centroids 

### ISSUE THREAD

**Issue by fgvieira** [torognes/vsearch#262]
Dear all,

As I understand it, on VSEARCH clustering, once the centroid is defined it does not change again. This can lead to centroids not being the best representative of a cluster or to presence of more divergent sequences.
So, I was wondering if it would be possible to have VSEARCH use the non-truncated consensus sequence of a cluster as its centroid. That is, after a sequence is added to a cluster, VSEARCH would calculate the non-truncated consensus sequence and use that as the centroid.

Would there be any drawbacks?
best,

**Comment by frederic-mahe** [comment]
one drawback is that consensus sequences are not always accurate:
> Output a multiple sequence alignment and a consensus sequence for each cluster to file-
name, in fasta format. Be warned that vsearch computes center star multiple sequence
alignments using a fast method whose accuracy can decrease significantly when using
low pairwise identity thresholds. The consensus sequence is constructed by taking the
majority symbol (nucleotide or gap) from each column of the alignment. Columns con-
taining a majority of gaps are skipped, except for terminal gaps.

but let's wait for @torognes to chime in.

**Comment by torognes** [comment]
This would result in a completely different clustering algorithm. I do not know how well it will perform; it needs to be studied. The current clustering algorithms in vsearch (as based on usearch) selects either the longest or the most abundant sequence as the centroid. I think choosing the most abundant sequence makes a lot of sense.

**Comment by colinbrislawn** [comment]
>This can lead to centroids not being the best representative of a cluster or to presence of more divergent sequences.

This was also the case with USEARCH, and a process called ['recentering'](http://drive5.com/usearch/manual7/recenter.html) was added to allow a different sequence from the cluster to be selected as the centroid.

However, the maker of usearch no longer suggests this method. He suggests that the consensus sequence may be misleading, for the same reasons listed here by the vsearch devs.

Here's the consensus: don't use use the consensus sequence. 😉

**Comment by fgvieira** [comment]
I agree that it would result on a different algorithm, but do not quite see what could be the problem; as I see it, the consensus sequence can be seen as come kind of theoretical "average" sequence of your alignment, no?

@colinbrislawn, could you elaborate a bit more why the use of "the consensus sequence may be misleading"?

**Comment by colinbrislawn** [comment]
Sure!

>consensus sequence can be seen as some kind of theoretical "average" sequence

Well said! So it this 'average' biologically accurate? Is it useful?

In the best-case scenario, the cluster would contain an accurate amplicon, and other similar amplicons that include a few sequencing errors. The 'average' sequence would correct these sequencing errors.

This is a good use-case, but it's not needed on Illumina data; the accurate amplicon is usually 10x more abundant than the ones with errors. We can find the 'true' centroid simply by sorting by abundance, which is fast and easy.

In the worst-case scenario, the cluster would contain TWO accurate, real amplicons from two different organisms. In this case, the 'average' sequence would artificially combine these two animals into a single chimeric read. The consensus sequence would be a read that was **never actually observed**.

If an OTU contained two real amplicons, a simple abundance sort would report one read accurately. A consensus sequence would lose both true reads, and also introduce a false read! 😱 

---

I'm mostly thinking about making OTUs from Illumina PCR amplicons. Maybe for other use-cases, consensus sequences are much more helpful. How do you use consensus sequences?

**Comment by fgvieira** [comment]
If you are dealing with Illumina sequence I can see that the most abundant one is probably the "true" one and that this approach might actually help to remove erroneous sequences since they will be way less abundant. But in practice, when you mean "sort by abundance", that means you dereplicate first (to get abundances) and then cluster with `--cluster-size`, no?

However, what if we are dealing with a more generic dataset? That is, where there is no correlation between "quality" and abundance. In this case, as I see it, the consensus (updated every time a new sequence is added to the cluster) would make more sense since it would actually represent the current cluster better, no?

**Comment by colinbrislawn** [comment]
> But in practice, when you mean "sort by abundance", that means you dereplicate first (to get abundances) and then cluster with --cluster-size, no?

Correct. An alternative might be to dereplicate, then do some sort of 'denoising' like unoise or dada2 or swarm.

>However, what if we are dealing with a more generic dataset? That is, where there is no correlation between "quality" and abundance. In this case, as I see it, the consensus (updated every time a new sequence is added to the cluster) would make more sense since it would actually represent the current cluster better, no?

Well, I guess so. But in this data set, why are you clustering at all? Wouldn't you want to keep all these SNPs (if they are true). If these differences are false, I guess the consensus option would serve to remove these errors... so I guess it's a use case. But in this case, I would use swarm! 🐝
