### ISSUE TITLE
chimera.vsearch.

### ISSUE THREAD

**Issue by chloelulu** [torognes/vsearch#264]
Hi, I am using mothur. However, I face the problem as below depicted. I do not know why. Could you do me a favor. 
Thanks in advance.

mothur >
chimera.vsearch(fasta=Undetermined_S0_L001_R1_001.trim.contigs.good.unique.good.filter.unique.precluster.fasta,count=Undetermined_S0_L001_R1_001.trim.contigs.good.unique.good.filter.unique.precluster.count_table,dereplicate=t)

Using 1 processors.
/sw/cs400_centos7.3_acfsoftware/mothur/1.39.5/centos7.3_intel17.2.174/mothur-1.39.5/mothurvsearch file does not exist. Checking path... 
[ERROR]:  file does not exist. mothur requires the vsearch executable.
[ERROR]: did not complete chimera.vsearch.

**Comment by pschloss** [comment]
It sounds like you don't have the executable installed. Since this isn't a vsearch bug, could you post your question to the mothur forum or mothur.bugs@gmail.com instead?

**Comment by chloelulu** [comment]
Sure, I will send it to the Gmail immediately.

**Comment by frederic-mahe** [comment]
Hi, as it concerns Mothur I will close that issue. Thanks,
