### ISSUE TITLE
Segmentation fault with certain characters in FASTQ files

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#267]
VSEARCH terminates with a segmentation fault when certain unusual characters appear in FASTQ files. Characters with code > 127 may trigger this problem.

**Comment by torognes** [comment]
Fixed.

**Comment by frederic-mahe** [comment]
Here is an example that used to make `vsearch` crash:
```sh
vsearch --fastq_chars <(printf "@\n\n+\n\351\n")
```
The header is empty, the sequence line is empty and the quality line contains an extended ascii character (here in octal notation). Interestingly, all these conditions are covered by independent unit tests but the segmentation fault is triggered only when conditions are combined. That case was discovered by [afl-fuzz](http://lcamtuf.coredump.cx/afl/) (2.47b). I've added a new unit test in [vsearch-tests](https://github.com/frederic-mahe/vsearch-tests/commit/6551e15a18a6ac269e141f6df559077870158315) to cover for that case.
