### ISSUE TITLE
Rereplicate alignment files

### ISSUE THREAD

**Issue by fgvieira** [torognes/vsearch#268]
Dear all,

I've been trying to use VSEARCH for some clustering and, so far, my idea is to dereplicate the dataset, and then cluster based on abundance. However, I'd like to reconstruct the original alignment but, apparently, VSEARCH rereplication does not allow for gaps. Any particular reason why?
```
vsearch v2.4.3_linux_x86_64, 70.8GB RAM, 16 cores
https://github.com/torognes/vsearch

Rereplicating 0%

Fatal error: illegal character '-' on line 2 in fasta file
```
I understand it is not super useful (specially since original sequence IDs are lost when dereplicating), but sometimes it is nice to be able to reconstruct the original alignment (e.g visualize or make a dendrogram).
If nothing else, gaps are valid characters on fasta files, no? :smile:

**Comment by torognes** [comment]
First, a warning: As you may be aware of, the `rereplicate` command will not reconstruct your original dataset. It will simply make a fasta file with a certain number of copies of the same sequence as indicated by the abundance in the input file. An example is shown below:

```
$ cat abc.fasta 
>abc;size=2
ACGT

$ vsearch --rereplicate abc.fasta --output out.fasta
vsearch v2.4.4_osx_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch

Rereplicating 100%  
Rereplicated 2 reads from 1 amplicons

$ cat out.fasta 
>abc
ACGT
>abc
ACGT
```

Some programs accept gaps (`-`) in fasta files, some do not. VSEARCH generally does not. It is common to just ignore gap symbols in input files, but VSEARCH will stop with a fatal error.

I do not understand what you are trying to do exactly and how it would help if VSEARCH accepted gap symbols. How does the input file look like in your example?

**Comment by fgvieira** [comment]
Right now, I think it would be nice to able to do it in case you want to visualize your clustering and have a more accurate idea of how your data is distributed (right now can be difficult since after dereplicating, each sequence may represent 1 or thousands of sequences).

As long as original sequence IDs are lost when dereplicating, then the application is limited; but maybe in the future it will be possible to keep that information and to completely reconstruct the original dataset...

**Comment by torognes** [comment]
As far as I understand, you want to reconstruct the original dataset with information about the clustering and abundance. The information that is lost during dereplication or clustering can be saved to an UC file (using the `--uc`) option. With a custom script, it is possible to annotate the original fasta file with the clustering or dereplication information based on the information in the UC file. I see that this may be useful.
