### ISSUE TITLE
utax reference dataset vsearch

### ISSUE THREAD

**Issue by iadamo1** [torognes/vsearch#274]
Hi, I am using vsearch (new user) and I would like to know if there is a command equal to the one in usearch, I did not find it in the manual but I was hoping you could give me an extra help.

usearch9 -usearch_global CPotus.fa -db utax_reference_dataset_10.10.2017.fasta -id 0.7 -blast6out CR97otus2017.m8 -strand both -maxaccepts 1 -maxrejects 256

thanks a lot!

**Comment by torognes** [comment]
Yes, the `usearch_global` command and all the options indicated is supported in vsearch. You can run the exact same command using vsearch. Just replace `usearch9` with `vsearch`.

**Comment by iadamo1** [comment]
thanks a lot for your answer!
