### ISSUE TITLE
missing option `--xee`

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#276]
In `vsearch`, two annotations can be added to sequence headers: `;size=INT` (abundance) and  `;ee=FLOAT` (expected error). The options `--sizeout` and `--xsize`, add and remove abundance annotations, but there is only a `--eeout` option, and no `--xee`.

**Comment by torognes** [comment]
Finally! Added in 2.11.0.

**Comment by torognes** [comment]
Reopening until all tests pass successfully.

**Comment by torognes** [comment]
Added in version 2.12.0 just released.
