### ISSUE TITLE
Windows only: Using "-" as filename meaning stdin or stdout does not work

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#277]
If `-` is specified as an input or output file name, vsearch should read or write to stdin or stdout. This does not work on Windows due to the way it is implemented because "/dev/stdin" and "/dev/stdout" does not exist. Implementation should be changed.

**Comment by frederic-mahe** [comment]
Hi @torognes 

if you use [cstdio](http://www.cplusplus.com/reference/cstdio/) `stdio.h`, it seems that `stdin`, `stdout` and `stderr` are automatically available, including on Windows.

**Comment by torognes** [comment]
Stdin and stdout are available. However, the problem is that when "-" is given as a file name on the command line, VSEARCH tries to read or write to the devices "/dev/stdin" or "/dev/stdout". But these devices do not exist on Windows.

**Comment by torognes** [comment]
Fixed in VSEARCH 2.7.1 just released.
