### ISSUE TITLE
How to download the executable chimera.vsearch file for windows?

### ISSUE THREAD

**Issue by bioinformaticsgeek** [torognes/vsearch#278]
How to download the executable chimera.vsearch file for windows?
Alternative is the uchime.exe file.  Which one is better?  What's the difference?

**Comment by torognes** [comment]
The latest version of the vsearch executable for windows, `vsearch.exe`, can be found inside the file [vsearch-2.6.1-win-x86_64.zip](https://github.com/torognes/vsearch/releases/download/2.6.1/vsearch-2.6.1-win-x86_64.zip) under releases.

It seem like `chimera.vsearch` is a command in mothur to run chimera detection. I do not think this is a vsearch executable. You'll probably need to install the above mentioned vsearch executable to run this in mothur. For more details, please contact mothur support.
