### ISSUE TITLE
Support for long database or query sequences?

### ISSUE THREAD

**Issue by flopezo** [torognes/vsearch#279]
Hello,

I was wondering if `vsearch` supports long database/query sequences, such as contigs or scaffolds? In the `vsearch` paper it is mentioned that local alignment commands (e.g., ublast) have not been prioritized, and therefore I'm assuming long sequences are not supported. Is this still the case in the latest version? Thank you!

**Comment by torognes** [comment]
VSEARCH still does not support long sequences in the sense that it becomes very slow when sequences are longer than a couple of thousand basepairs.

**Comment by flopezo** [comment]
Thank you for the prompt reply.
