### ISSUE TITLE
Port VSEARCH to Linux on the ARM architecture

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#285]
ARM cpus seems to become a cost-effective platform for bioinformatics. I have access to such a system at UiO.

Porting VSEARCH to this platform requires rewriting of the SIMD code using [ARM's Advanced SIMD (NEON) technology](https://developer.arm.com/technologies/neon). There is an [intrinsics reference manual](https://developer.arm.com/technologies/neon/intrinsics).

Otherwise it appears to be rather easy.

**Comment by colinbrislawn** [comment]
Wow! I didn't know ARM servers were commercially available. But they totally are, and you can [rent](https://www.packet.net/bare-metal/servers/type-2a/) them for [cheap](https://www.scaleway.com/armv8-cloud-servers/).

I appreciate your commitment to porting vsearch to many architectures, even underdogs like ARM and POWER8.

**Comment by torognes** [comment]
No, we haven't started porting it to ARM yet. No definite plans yet, but increasingly interesting.

**Comment by torognes** [comment]
ARM Neon Programmer's guide:

https://static.docs.arm.com/den0018/a/DEN0018A_neon_programmers_guide_en.pdf

**Comment by GenomicaMicrob** [comment]
Eagerly waiting for the ARM version of vsearch!

**Comment by torognes** [comment]
I am working on porting it to ARM now.

**Comment by torognes** [comment]
64-bit ARMv8 support is ready! Available in vsearch 2.10.3 just released. Enjoy!

**Comment by frederic-mahe** [comment]
Awesome work! @GenomicaMicrob could you please confirm that this port works on your new server?

**Comment by torognes** [comment]
There is something wrong with version 2.10.3. It produces wrong alignments. Do not use. I discovered this today despite a lot of testing before the release after changing the alignment code.

**Comment by GenomicaMicrob** [comment]
Sorry I haven’t been able to test it since the server is down because of the holidays, next Monday I’ll test it, can’t wait to do it.

Bruno Gomez-Gil
CIAD, Mazatlán Unit
AP 711 Mazatlán, Sinaloa
México 82000
+(52)669 9898700 ext 245
https://www.researchgate.net/profile/Bruno_Gomez-Gil

**Comment by GenomicaMicrob** [comment]
So far I have tested --cluster_fast, --usearch_global, --uchime_ref without any problems! Great work, thanks. I'll keep testing it.
Our ARM (2 ThunderX_CP 64-bit ARMv8 48 cores ea.) server has more or least the same benchmarking as our Dell PowerEdge R810 (4 AMD Opteron Processor 6272 x 16 cores ea.), but this is just a preliminary appreciation.

**Comment by torognes** [comment]
It seems to be working fine, so I am closing this issue.
