### ISSUE TITLE
vsearch --usearch_global always leads to Fatal error: File type not recognized.

### ISSUE THREAD

**Issue by antonkulaga** [torognes/vsearch#286]
I am constantly getting `Fatal error: File type not recognized.` error whenever I try to use --usearch_global, here is an example of the command:
```
vsearch --usearch_global /cromwell-executions/vsearch/c65a63a4-1623-4ba5-a7d2-45b2d45adbeb/call-global_search/inputs/pipelines/indexes/genage/human_mouse_fly_worm_genage.fsa --db /cromwell-executions/vsearch/c65a63a4-1623-4ba5-a7d2-45b2d45adbeb/call-global_search/inputs/pipelines/whales/graywhale/Trin_Mitya.Trinity.fsa --threads 0 --id 0.7 --alnout alnout.txt
```
I also tried many other alternatives (including using udb for database) but it never worked.
Here is an example of fasta file I used for the query: (I also tried renaming it to fsa but it had some problem)
http://agingkills.westeurope.cloudapp.azure.com/pipelines/indexes/genage/human_mouse_fly_worm_genage.fasta
And here is an example of the database (basically it is a trinity transcriptome):
http://agingkills.westeurope.cloudapp.azure.com/pipelines/whales/graywhale/Trin_Mitya.Trinity.fasta
I also tried to use udb version of it http://agingkills.westeurope.cloudapp.azure.com/pipelines/indexes/vsearch/graywhale_mitya.udb but it also did not work (although the conversion worked well).

here is stderr that I ussually get:
```
vsearch v2.6.2_linux_x86_64, 31.4GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading file /cromwell-executions/vsearch/c65a63a4-1623-4ba5-a7d2-45b2d45adbeb/call-global_search/inputs/pipelines/whales/graywhale/Trin_Mitya.Trinity.fsa 100%
79386154 nt in 114233 seqs, min 201, max 14060, avg 695
Masking 100%
Counting k-mers 100%
Creating k-mer index 100%


Fatal error: File type not recognized.
```

**Comment by torognes** [comment]
Your query file `human_mouse_fly_worm_genage.fsa` is not in a proper FASTA format. The first 19 lines looks like some kind of scripting language, they should be removed.

**Comment by antonkulaga** [comment]
Indeed, I am surprised how ammonite scala script managed to get there
