### ISSUE TITLE
Loosing OTUs when clustering

### ISSUE THREAD

**Issue by Felipealbornoz** [torognes/vsearch#293]
Hi, when I try to cluster OTUs at 100% ID from my dereplicated sequence files, I get less number of OTUs than sequences from my dereplicated file. I used the following command:

vsearch -cluster_fast derep.fasta --sizein --xsize --id 1.0 --relabel OTU_ --centroids OTU.100.fasta --threads 0

For what I understand, at 100% ID, I should have gotten the same number of OTUs as number of sequenced from my depreplicated fie. Is this a bug or am I doing something wrong?

**Comment by colinbrislawn** [comment]
During dereplication, the total length of both reads is considered. During clustering, only the area of overlap is scored. So these two reads would not be dereplicated, but they would be clustered together at `--id 1`

```
>read1
ACGTAGTCATTTACTGTACTGTACGTTATACGATATGTCTATGCT
>read2
ACGTAGTCATTTACTGTACTGTACGTTATACGATATGTCTATGCTA
```

Let me know if this helps answer your question. If it does, feel free to close this issue.

**Comment by Felipealbornoz** [comment]
Thank you! that explains it
