### ISSUE TITLE
relabel OTU table IDs question

### ISSUE THREAD

**Issue by jack1120** [torognes/vsearch#296]
I have an OTU table in which each OTU is labelled with a sha1 label from a previous step in a pipeline. I also have a taxonomy table that contains all of, but more than, these sha1 labels and the top hits to the corresponding sequences. I would like to replace the sha1 labels with the taxonomy names in my final OTU table. Is there a way to do this using vsearch? It does not seem like the current relabel options can achieve this, but it also seems like it would be fairly common to want to do so.

**Comment by colinbrislawn** [comment]
Can you post a few lines from each of these files, along with the desired output file? I'm not sure if this is a simple removal or if this is a database lookup situation, and examples really help me understand the goal.

Thanks!

**Comment by jack1120** [comment]
Here is an example of the OTU table:
[OTU_Table_Example.txt](https://github.com/torognes/vsearch/files/1750201/OTU_Table_Example.txt)

Here is an example of the taxonomy table:
[Taxonomy_Table_Example.txt](https://github.com/torognes/vsearch/files/1750203/Taxonomy_Table_Example.txt)

Thus, my OTU_IDs are named for the qseqid (the sha1 label), whereas I would like to relabel them by the ssciname.

Thank you!

**Comment by colinbrislawn** [comment]
Thank you. Those are _fantastic_ examples.

Yep, I know what you are trying to do. Nope, I don't know how to do that in linux.

This looks like a classic merge (R) / vlookup (excel) / INNER JOIN (sql). In my own projects, I would do this sort of thing in [R](https://www.biostars.org/p/131688/#131718), but I'm not sure if that fits into your workflow. I know that the vsearch devs could do this in linux using [awk](https://www.biostars.org/p/131688/#131715), but I don't use it much and don't want to give you poor advice.

**Comment by jack1120** [comment]
Thanks! A colleague helped me with a perl script to accomplish this. I started going down the awk rabbit hole yesterday and quickly realized that I was in over my head. Although my skills are pathetic in comparison to many others, I am more comfortable in R and will try to use the dplyr package for similar tasks in the future.

**Comment by colinbrislawn** [comment]
I'm glad you got this working! For reference, here is how I might do this in R.

```R
library("dplyr")

otu <- read.table("~/Downloads/OTU_Table_Example.txt", header = 1)
tax <- read.table("~/Downloads/Taxonomy_Table_Example.txt", header = 1, sep = "\t")

# rename the column of otu so it matches the column of tax, then merge()
full.merge <- otu %>% mutate(qseqid = OTU_ID) %>% merge(tax)

# select() just the columns you want for your final table
full.merge %>% select(OTU_ID = ssciname, 3:5)

```


Colin
