### ISSUE TITLE
ECCN for VSEARCH 

### ISSUE THREAD

**Issue by kkabhi** [torognes/vsearch#299]
If you have already classified VSEARCH software with ECCN, please confirm the applicable number. 
 
If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-assess:
 
1, Does the Software perform any encryption or utilize any encryption processes?  Y/N
2. If the answer is YES to question 1, please indicate if the encryption is coded into the application or separately called (such as using SSL)
3. If the answer is YES to question 1, please indicate what function(s) the cryptography/encryption serves 
 
A, Copyright protection purposes (Includes using a license key/code)
B, User authentication purposes
C, A core part of the functionality such as to encrypt databases
D, To encrypt communications between the software and a host system.

**Comment by colinbrislawn** [comment]
This question seems very similar to these issues on other repos:
https://github.com/Microsoft/nodejstools/issues/1608 
https://github.com/twbs/bootstrap/issues/25766 
https://github.com/zloirock/core-js/issues/349 
https://github.com/google/protobuf/issues/376

Looks like this question is often raised if a commercial product is being developed with intent to export.

@kkabhi, how are you planning to use VSEARCH? What product are you developing? Are you going to use the BSD 2-clause or the GPLv3 [license](https://github.com/torognes/vsearch/blob/master/LICENSE.txt)?

**Comment by kkabhi** [comment]
VSEARCH is used for research and using SD 2-clause or the GPLv3 license.
Please let us know ECCN for VSEARCH

**Comment by colinbrislawn** [comment]
This might be helpful: https://www.fossology.org/ 
>FOSSology is a open source license compliance software system and toolkit. As a toolkit you can run license, copyright and export control scans from the command line. As a system, a database and web ui are provided to give you a compliance workflow. License, copyright and export scanners are tools available to help with your compliance activities.

**Comment by torognes** [comment]
VSEARCH has not been classified with ECCN. Below is some information for your self-assessment.

VSEARCH does not perform any encryption and does not utilise any encryption processes, neither in its own code or in any separate libraries.

However, VSEARCH does implement and use the MD5 (128 bits) and SHA-1 (160 bits) hash functions that are considered weak cryptographic hash functions, but they do not perform encryption as such. They are only used as a kind of digital signature for each sequence or as a data integrity check. VSEARCH includes public domain code for these functions (in md5.c and sha1.c).
