### ISSUE TITLE
Add the fastx_getseqs command

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#303]
https://www.drive5.com/usearch/manual/cmd_fastx_getseqs.html

**Comment by colinbrislawn** [comment]
Very cool. I would love to see more sequence utilities like [esl-sfetch](https://cryptogenomicon.org/2011/05/03/extracting-hmmer-results-to-sequence-files-easel-miniapplications/) in vsearch.

**Comment by torognes** [comment]
Added in commit b896446f0ace2af567d8965eaee4e5a81e5bb54b.

**Comment by torognes** [comment]
It's currently rather slow when there are many labels. Could be speeded up at least when matching the entire header and not a substring.

**Comment by torognes** [comment]
Fixed in vsearch version 2.13.0, just released.
