### ISSUE TITLE
should vsearch support fast5 files?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#305]
Oxford Nanopore sequencers output data in FAST5 format, which seems to be a dialect of [HDF5](https://support.hdfgroup.org/HDF5/whatishdf5.html). There are [generic tools](https://support.hdfgroup.org/HDF5/doc/RM/Tools.html) to work with `HDF5`, and tools specific to the output of Nanopore sequencers (e.g.; [poretools](https://github.com/arq5x/poretools)).

`poretools` is a python tool that offers several commands to read, query or write `fast5` files, including exporting to `fastq`. To do so, `poretools` relies on external libraries (`HDF5` and `h5py`).

Nanopore sequencers are used mainly to produce long reads of genomics/transcriptomics data, which is not vsearch's *forte*. Nonetheless, if `fast5` becomes popular, it might be interesting for vsearch to at least be able to read `fast5` files as it reads `fastq` files (provided that it is feasible without creating new dependencies for vsearch). In the meantime, we can recommend `poretools` to users with fast5 files.

**Comment by colinbrislawn** [comment]
>it might be interesting for vsearch to at least be able to read `fast5` files as it reads `fastq` files

Sure! Why not!

>Nanopore sequencers are used mainly to produce long reads of genomics/transcriptomics data, which is not vsearch's _forte_.

I agree. Vsearch isn't trying to be a [long read aligner](https://github.com/lh3/minimap2). That being said, the Nanopore sequencer does [amplicon sequencing](https://nanoporetech.com/analyse/16s) and that's squarely within the prevue of vsearch.
