### ISSUE TITLE
Unable to install vsearch on MacOS High Sierra

### ISSUE THREAD

**Issue by AnniBerlin** [torognes/vsearch#306]
Hello,

I was trying to install vsearch on MacOS High Sierra. I downloaded vsearch-2.8.0-macos-x86_64 and now I don't know how to install vsearch completely.

Because I have no experience to work with command lines in the terminal app it is really hard to understand what I am doing there.

**Comment by colinbrislawn** [comment]
Hello AnniBerlin,

Thanks for downloading vsearch! Let's start here:
>Because I have no experience to work with command lines in the terminal app it is really hard to understand what I am doing there.

I've been there! Command line apps feel very different than normal desktop applications and it takes a little while to get comfortable. I think this guide on the [unix shell](http://swcarpentry.github.io/shell-novice/) is a great place to start. Once you get a feel for using the shell (called Terminal on OSX), then we can set up vsearch and you can start running it.

While I have had a great experience using vsearch, it doesn't really have tutorials aimed at first time users. May I ask about your research project? If you are analyzing 16S data, software like [Qiime2](https://qiime2.org/) might be a better place to start because it's built for beginners and pros alike.

Thanks for telling me more!
Colin

**Comment by AnniBerlin** [comment]
Hello Colin,

I downloaded vsearch and unzip the folder without command line. When I type 'ls' into command line I see 'vsearch' but when I want to look for chimeric sequence and type vsearch --uchime ...and so...I get the message 'vsearch command not found'.
I wonder if I have forgot anything or missed one step so I can't use vsearch.

In the moment I had to start working with Qiime1 and when I get a little experience it ist planed to learn as well working with Qiime2.

Anne

**Comment by colinbrislawn** [comment]
> When I type 'ls' into command line I see 'vsearch' but when I want to look for chimeric sequence and type vsearch --uchime ...and so...I get the message 'vsearch command not found'.

Ah OK. To run vsearch directly, you have to list a folder path first.
`./vsearch` works
`vsearch` does not.

If you want to be able to run `vsearch` from anywhere, you can [add it to your path](https://apple.stackexchange.com/questions/41542/adding-a-new-executable-to-the-path-environment-variable).

I've had a great experience working with Qiime 2, and people on [the forums](https://forum.qiime2.org/c/user-support) are really helpful. Not many people are on the Qiime 1 forums anymore.

**Comment by AnniBerlin** [comment]
Now I type: 
./vsearch --uchime_ref'User/anni/Downloads/combined_seqs.fna' --nonchimeras non_chimera_out.fna --chimeras chimera_out.fna --db '/Users/anni/Downloads/uchime/uchime.fna'
then I get:
vsearch: unrecognized option `--uchime_refUser/anni/Downloads/combined_seqs.fna'...I assume thats because I downloaded the wrong file for uchime?? I want to check for chimera with vsearch with reference database chime_gold.fna

**Comment by AnniBerlin** [comment]
Do you know how I can transfer uchime_gold.fna.txt file to uchime_gold.fna? I didn't find the place were I can download an uchime_gold.fna file

**Comment by colinbrislawn** [comment]
Try, leaving a space between the argument and the file, and don't use `''` quotes. Like this:

`./vsearch --uchime_ref /User/anni/Downloads/combined_seqs.fna --nonchimeras non_chimera_out.fna --chimeras chimera_out.fna --db /Users/anni/Downloads/uchime/uchime.fna`

**Comment by AnniBerlin** [comment]
To type:
./vsearch --uchime_ref /User/anni/Downloads/combined_seqs.fna --nonchimeras non_chimera_out.fna --chimeras chimera_out.fna --db /Users/anni/Downloads/uchime/uchime.fna
...seem so that it could work.
But in response I get:
Unable to open file for reading (/Users/anni/Downloads/uchime/uchime_gold.fna/)

I'm wondering why it is not possible to open the file 'uchime_gold.fna' for reading. It is probably because this fna-file is actually just a text file. Is there any way to convert the text-file to a fasta or anything like that?

**Comment by AnniBerlin** [comment]
Yeah finally it works!!!!!!

:DDDDDDD

Thank you so much!!!!
