### ISSUE TITLE
Unable to sort centroids by abundance

### ISSUE THREAD

**Issue by MaestSi** [torognes/vsearch#308]
Dear Vsearch developer,
I'd like to have centroids sorted by abundance of respective cluster.
As suggested by help, --clusterout_sort (which is meant to order msaout, consout, profile by decr abundance, but not centroids) doesn't do the job.
Is there a way to obtain sorting of centroids?
Thanks

**Comment by MaestSi** [comment]
Ok, thanks!

**Comment by torognes** [comment]
Commit f289a1ea5178f8dee0affc8188550b09cddd11ff fixes this issue. When `--clusterout_sort` is specified, the `--centroids` output as well as the centroids part of the `--uc` file will be sorted by abundance too.
