### ISSUE TITLE
Missing progress during clustering

### ISSUE THREAD

**Issue by ne1s0n** [torognes/vsearch#311]
Clustering (-cluster_fast) does not show the progress percentage. I've started more than 24 hours ago and in this kind of long elaboration it would be very useful to be able to estimate the completion time.

**Comment by torognes** [comment]
The command should normally indicate the progress. Could you please provide the command line used and indicate the size of the dataset?

**Comment by torognes** [comment]
If you are reading from a pipe the progress is not indicated (it stays at 0% until finished), because vsearch is unable to determine the input size.
