### ISSUE TITLE
derep_fulllength

### ISSUE THREAD

**Issue by danchurch** [torognes/vsearch#320]
Hi! I get a default minseqlength of 32 if I don't specify otherwise on the the `vsearch --derep_fulllength ` command. I am using v2.8.0_linux_x86_64.  

I don't know that this is a bug or intentional. It is very easy for me to change the settings, but I thought I'd bring it up, in case you didn't know.

**Comment by torognes** [comment]
Yes, the default `minseqlength` is 32 for some commands and 1 for others. This is intentional and was done for compatibility with usearch (version 7).
