### ISSUE TITLE
Add the fastq_join Command

### ISSUE THREAD

**Issue by BennettRand** [torognes/vsearch#337]
Please add an alternative to the [fastq_join](http://www.drive5.com/usearch/manual/cmd_fastq_join.html) command.

Example:
`usearch -fastq_join fwd.fastq -reverse rev.fastq -fastqout join.fastq -join_padgap NNNN -join_padgapq EEEE`

**Comment by torognes** [comment]
I'll probably implement this command soon, as others have also asked for it.

**Comment by torognes** [comment]
The fastq_join command has been added in vsearch version 2.9.0, just released.

**Comment by BennettRand** [comment]
Many thanks :tada:
