### ISSUE TITLE
Speed-up searching when using the --top_hits_only option

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#34]
During a search, the target sequences are sorted by decreasing k-mer composition similarity with the query sequence. The target sequences that are the most likely to get a high similarity score with the query are the first to be treated (i.e. pairwise aligned).

In a taxonomic assignment context (with `--maxaccepts 0 --maxrejects 0 --id 0.5`), and when using the option `--top_hits_only`, `vsearch` ends up comparing all the targets to the query, which is inefficient. The search process could stop once the query-target similarities start to drop. In practice, the algorithm could count the number of blocks (a block contains 16 targets if I am correct) where observed similarities are all lower than the best obtained so far. After two blocks of decreasing similarity values, the search can safely stop and start working on the next query.

**Comment by frederic-mahe** [comment]
What do you think @torognes? the idea of using `top_hits_only` and `--maxaccepts 0` is to be sure to find all best matches: if there are 250 target sequences 100% identical to my query sequence, I want to get all of them in the output.

Or did I misunderstand the process? If the target sequences are pre-sorted by k-mer profile similarity first, can I safely set `--maxrejects 32` to implement the speed up process I described above?

**Comment by torognes** [comment]
In this scenario I think it would make sense to set a reasonable maxrejects value (e.g. 32 or even 1000). I think this will be a good heuristic that would capture all the top hits in almost all cases.
