### ISSUE TITLE
individual manpages for each vsearch command

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#340]
The `--rereplicate` command would be a good starting point as it accepts only a limited number of options. The manpage could be accessed as such:
```sh
man vsearch
man vsearch-rereplicate
```
Alternatively, per-command help messages (`-h` or `--help`) could be easier to find for users not familiar with manpages:
```sh
vsearch --help
vsearch --rereplicate --help
```

**Comment by colinbrislawn** [comment]
I really like the idea of per-command help messages with `-h`. This just-in-time teaching really helps new users.

How does this synergize or conflict with #280 Online linkable manual? Could we work on both of these at the same time? I am being way to optimistic?

**Comment by frederic-mahe** [comment]
hi @colinbrislawn 

ideally `vsearch` users should have access to all three sources of information (help commands, manpages, and online manual), and I appreciate the virtues (or defaults) of each method. Nonetheless, writing a manpage is easy so I think I'll experiment with that first, just to see if that works and what level of redundancy it implies.

**Comment by hafizmtalha** [comment]
> The `--rereplicate` command would be a good starting point as it accepts only a limited number of options. The manpage could be accessed as such:
> 
> ```shell
> man vsearch
> man vsearch-rereplicate
> ```
> 
> Alternatively, per-command help messages (`-h` or `--help`) could be easier to find for users not familiar with manpages:
> 
> ```shell
> vsearch --help
> vsearch --rereplicate --help
> ```

vsearch --rereplicate --help
gives me following
vsearch v2.22.1_linux_x86_64, 15.5GB RAM, 6 cores
https://github.com/torognes/vsearch



Fatal error: FASTA output file for rereplicate must be specified with --output

and for man comand its gives following
man vsearch-rereplicate
No manual entry for vsearch-rereplicate

**Comment by frederic-mahe** [comment]
> vsearch --rereplicate --help

Per-command manpages are not yet implemented.

**Comment by frederic-mahe** [comment]
I am pleased to announce that a first, very incomplete set of per-command `vsearch` manpages is available on the `dev` branch. A mechanism to generate and install these pages will be added to the compilation process. In future vsearch releases, these per-command manpages will replace the current monolithic page.

The idea of per-command help messages is not abandoned.
