### ISSUE TITLE
sha1 hash differs from the one optained in r

### ISSUE THREAD

**Issue by tobiasgf** [torognes/vsearch#343]
I wish to use the sha1 hash label universally across different pipelines. But when I apply the sha1 relabelling option of vsearch I get a different sha1 hash compared to what I get using the sha1 function of the r-package digest.

For example for this sequence "CAACCCTCAAGCTCTCTTGCTTGGTGTTGGGGCTTCTGCGGCTTCGGCCGCAGGCCCTGAAAAACAGTGGCGGGCTCGCTATAACTCCGAGCGTAGTAATCTCTCTCGCTTTGGAAGTGTAGCGGTTCCCGGCCGTTAAACCCCCCAATTTCTGAAA"
I get the sha1 hash `33f304a3cd9a922247cab0a3dd36c809abc9000d` when I apply the --relabel_sha1 option in vsearch, whereas I get the sha1 hash `1eae7a3449bf459b5e7105b36a3d138c790a0f15` when I use the sha1 function in r.

Any idea what causes this difference?

edit: I have an idea that it must be something about the start and end of the string. But I would love to hear ideas how to derive the same sha1 for the sequence in r as that derived from vsearch

-tobiasgf

**Comment by tobiasgf** [comment]
I found a solution!
Using this command and options in R, will give the same sha1 hash as vsearch!
`digest("CAACCCTCAAGCTCTCTTGCTTGGTGTTGGGGCTTCTGCGGCTTCGGCCGCAGGCCCTGAAAAACAGTGGCGGGCTCGCTATAACTCCGAGCGTAGTAATCTCTCTCGCTTTGGAAGTGTAGCGGTTCCCGGCCGTTAAACCCCCCAATTTCTGAAA", algo="sha1", serialize=F)`

**Comment by torognes** [comment]
It seems like the R sha1 function computes the hash on a binary serialized version of the string that differs from the plain ascii string. If you instead run `digest(string, algo="sha1", serialize=FALSE)` you get the correct result:

```
>sha1("CAACCCTCAAGCTCTCTTGCTTGGTGTTGGGGCTTCTGCGGCTTCGGCCGCAGGCCCTGAAAAACAGTGGCGGGCTCGCTATAACTCCGAGCGTAGTAATCTCTCTCGCTTTGGAAGTGTAGCGGTTCCCGGCCGTTAAACCCCCCAATTTCTGAAA")
[1] "1eae7a3449bf459b5e7105b36a3d138c790a0f15"
>digest("CAACCCTCAAGCTCTCTTGCTTGGTGTTGGGGCTTCTGCGGCTTCGGCCGCAGGCCCTGAAAAACAGTGGCGGGCTCGCTATAACTCCGAGCGTAGTAATCTCTCTCGCTTTGGAAGTGTAGCGGTTCCCGGCCGTTAAACCCCCCAATTTCTGAAA", algo="sha1", serialize=FALSE)
[1] "33f304a3cd9a922247cab0a3dd36c809abc9000d"
```

See https://www.rdocumentation.org/packages/digest/versions/0.6.18/topics/digest for details.
