### ISSUE TITLE
dereplication question

### ISSUE THREAD

**Issue by devonorourke** [torognes/vsearch#344]
I'm hoping to take a database of arthropod COI reads and "bin" at 100% identity. `vsearch` seemed like the logical starting point with this command:

```
vsearch --derep_fulllength cleaned.extracted.fa \
--output vsearch-COIderep.fna --uc vsearch-COIderep.uc \
--relabel_keep --threads 24
```

I couldn't find anywhere in the manual about how the program handles taxonomic information when processing through situations where two identical sequences contain distinct taxonomies. Consider the following two scenarios:

```
>seq1;k__Animalia;p__Arthropoda;c__Insecta;o__Lepidoptera;f__;g__;s__
AATTCCGG
>seq2;k__Animalia;p__Arthropoda;c__Insecta;o__Lepidoptera;f__Oecophoridae;g__Chezala;s__
AATTCCGG
>seq3;Animalia;p__Arthropoda;c__Insecta;o__Coleoptera;f__Carabidae;g__Pterostichus;s__Pterostichus tristis
TAGTAGTA
>seq4;k__Animalia;p__Arthropoda;c__Insecta;o__Coleoptera;f__Carabidae;g__Heteropaussus;s__ Heteropaussus hastatus
TAGTAGTA
```

I would expect two sequence records in the output, but I'm unclear whether `vsearch` does anything other than retain the header from the initial record with which all other matches align, or if there are more considerations that take place.

In the example above, the third and fourth sequences contain identical sequences, both contain complete taxonomic information, but these taxonomies differ. In a perfect world, I'd like for the taxonomic information to revert back to the lowest common ancestor. Is this possible in `vsearch`?

I can appreciate that there is no perfect solution. In the first and second example, there are two identical sequences, yet the first record contains incomplete information, while the second record contains full taxonomic identity. In this situation I'd like to retain the most amount of taxonomic information, thus retaining the full record. However I can appreciate that it could be argued that in my previous example, keeping identical information would actually require breaking this record back to taxonomic order.

Thank you for any information you can provide

**Comment by torognes** [comment]
Sorry, but vsearch considers only the the sequences when dereplicating. It will use the first header encountered among those with identical seqeunces. The dereplication command ignores taxonomic information in the header. There is not simple solution in vsearch to your request as far as I can see.

**Comment by devonorourke** [comment]
Good to know - thank you for the quick reply!
