### ISSUE TITLE
gist for map.pl

### ISSUE THREAD

**Issue by GeoMicroSoares** [torognes/vsearch#345]
Just in case anyone needs it, I created a gist of [map.pl](https://gist.github.com/GeoMicroSoares/29ca37f321d03b0e2325d4ed80c81fd5).

Needed it to clone for a singularity image. Hope it's ok with the developers, let me know if there's an issue or if you prefer to create your own gist.

Thanks so much for all your work!

**Comment by frederic-mahe** [comment]
hi @GeoMicroSoares I am not sure what this `map.pl` does. Is it something you apply to vsearch results?

**Comment by GeoMicroSoares** [comment]
Used right here --> https://github.com/torognes/vsearch/wiki/VSEARCH-pipeline
