### ISSUE TITLE
Support for the legacy sff format?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#346]
Should `vsearch` be able to convert legacy formats (`sff`, `fasta+qual`) into `fastq`?

There are scripts available on the web doing just that, but long term support and exactness are not guaranteed. That bothers me once in a while when I encounter a `sff` or `fasta+qual` dataset.

**Comment by colinbrislawn** [comment]
I value vsearch as a swiss army knife; this one program can do everything!

Having a successful piece of open source software that can convert legacy formats into modern formats would be very helpful. And there are new formats like fast5 #305 coming along every day...

**Comment by frederic-mahe** [comment]
> I should be relatively easy to read the sff format and use it as an alternative to fastq as input for many commands.

Given that vsearch can read and write to stdin and stdout, I imagine that a simple and robust approach would be to isolate the `sff` to `fastq`conversion in a command (`--sff_convert`?). The produced fastq file could be piped and further processed by other commands:
```sh
vsearch \
    --sff_convert sfffile \
    --fastqout - | \
    vsearch \
        --fastx_filter - ...
```
Another advantage is that the `sff` to `fastq`conversion can be more thoroughly tested if the number of options is limited to:
- `--fastq_ascii` (33 by default),
- `--fastq_qminout` (0)
- `--fastq_qmaxout` (41)
- `--log`
- `--quiet`

and eventually a `--clip` or `--noclip` option (In my experience with mixing Illumina and 454 datasets, there is no need to trim the sff reads, so I'd prefer `--noclip` to be the default). Untrimmed reads should use lowercase nucleotides for the regions marked as "I would clip that" by the 454 basecaller.

If we were to offer users full control, we would need to have more precise trimming options for quality and adapters, and for 5' or 3' ends: (clip_qual_left, clip_qual_right, clip_adapter_left, clip_adapter_right).

I'll send you sff files to test.

**Comment by frederic-mahe** [comment]
Hi @torognes 

[here](https://www.ebi.ac.uk/ena/data/view/PRJEB9943) you will find public `sff` files alongside their `fastq` conversions (check the columns "Submitted files (FTP)" and "FASTQ files (FTP)" for links).

**Comment by frederic-mahe** [comment]
[Another interesting source](https://contig.wordpress.com/2010/10/28/newbler-input-i-the-sff-file/) of info on the sff format.

Some values would be interesting to report on stderr or a log file: instrument model, number of flow cycles, flow chars, key sequence (the library building protocol can be deduced from that).

**Comment by frederic-mahe** [comment]
I'll change the title of this issue to focus on the sff format. Other formats can be discussed in their dedicated issues.

**Comment by frederic-mahe** [comment]
A common problem with sff files seems to be `Your SFF file is technically invalid as it is missing a terminal 4 byte null padding region` (biopython's sff parser warning). So, an hypothetical vsearch support for sff files should tolerate incomplete padding regions to a certain extent.

**Comment by torognes** [comment]
The `sff_convert` command has been implemented in vsearch 2.10.0. The options `--fastq_asciiout`, `--fastq_qminout`, `--fastq_qmaxout`, `--sff_clip`, `--log` and `--quiet` are supported. I have tested it with a few of the SFF files on the EBI ENA site, but perhaps SFF files from other instruments/chemistries etc should be used as well. By default it does not clip the sequences, but just lowercases the would be clipped ends.

**Comment by frederic-mahe** [comment]
Awesome! I've tested a couple hundred `sff` files, and so far so good. `vsearch` does great and is quite fast. 

I've been trying to collect more test files though. One option is to look at biopython's [sources](https://biopython.org/wiki/Download). There is a `Tests/Roche/`folder with a few good and bad `.sff` files, and a README file to explain the nature of each `.sff` file.
```
Created with Roche tools from E3MFGYR02.sff, extracting 10 random reads:

* E3MFGYR02_random_10_reads.sff - has an .mft1.00 style index and manifest
* E3MFGYR02_no_manifest.sff - has an .srt1.00 style index and no manifest
```
vsearch outputs the same results for each file, good.
```
Modified with a dummy index block in various positions, SFF software
should ignore an unknown index block gracefully. The Roche tools are
happy to read these files:

* E3MFGYR02_alt_index_at_start.sff
* E3MFGYR02_alt_index_in_middle.sff
* E3MFGYR02_alt_index_at_end.sff
```
vsearch fails at soon as it hits the dummy index block, where it should ignore it gracefully.
```
Modified to move the ".mft1.00" index block. The Roche tools do not
like these files, and Roche told me in an email exchange that their
(undocumented) index blocks should only be at the end of the file.
However, I still found these useful for testing:

* E3MFGYR02_index_at_start.sff
* E3MFGYR02_index_in_middle.sff
```
vsearch fails when it encounters the misplaced index block, good. (I am not 100% sure how it is different from the previous case)
```
Additional SFF files modified from real data to rename the reads. The
Roche tools are happy to read these files. They make excellent tests
for parsing the index block since the read names are different lengths:

* greek.sff  - has an .srt1.00 style index
* paired.sff - has an .mft1.00 style index and manifest
```
vsearch converts successfully. 
```
Finally these file are concatenations of the greek.sff and paired.sff
files with E3MFGYR02_no_manifest.sff (for testing this as a special
error condition):

* invalid_greek_E3MFGYR02.sff - Concatenating SFF files together
* invalid_paired_E3MFGYR02.sff - Concatenating without 8 byte alignment
```
vsearch converts successfully, ignoring the concatenated part apparently. Maybe a message warning the user that the file contains extra-data?

**Comment by torognes** [comment]
Version 2.10.1 now reads all the SFF files in the biopython set and warns when appropriate, as requested. It now also supports reading from a pipe and should be a tiny bit faster and less memory demanding. Error messages have been improved slightly.

**Comment by frederic-mahe** [comment]
Thanks @torognes ! The conversion log is very informative, that's perfect.
```
Number of reads: 10
Flows per read:  400
Key sequence:    TCAG
Converting SFF:  100%  
WARNING: Index at unusual position in file
Index type:      .diy1.00
```

**Comment by frederic-mahe** [comment]
There are still a few unit tests I would like to write for the `--sff_convert` command, but I wanted to test the command against **real** datasets too. I've listed the 60,011 sff files publicly available in ENA (2019-01-22):
```sh
curl \
    --request GET \
    --header 'Accept: application/json' \
    --output ENA_public_sff_runs.tsv \
    'https://www.ebi.ac.uk/ena/portal/api/search?result=read_run&query=submitted_format="SFF"&fields=study_accession,sample_accession,instrument_platform,instrument_model,submitted_md5,submitted_ftp,read_count&limit=0'
```
There is a certain level of redundancy (duplicated samples) and some missing metadata, but `vsearch --sff_convert` was able to read and process all these files, yielding the expected number of reads.

Nice job, vsearch's sff reader is robust and can deal with most sff files available in the wild!
