### ISSUE TITLE
implement the command --fastx_uniques?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#348]
usearch has a `--fastx_uniques` command that can dereplicate fastq and fasta files, whereas vsearch can only dereplicate fasta files with `--derep_fulllength`.

I get the appeal of uniformity, the same command can apply to both fasta and fastq files, but I have doubts about this one. Should quality values taken into account when dereplicating? Should the quality values be combined as if they were independent observations of the same sequence?

**Comment by scharch** [comment]
As a user, yes I want this feature, please.

In answer to your questions about implementation:
1. I could see an option to treat bases below a certain quality as `N`s. But otherwise I would not take quality values into account.
2. As far as output, usearch apparently just averages the p(error) at each position for the sequences being collapsed, which I don't really understand. I do think it makes sense to treat the sequences being collapsed as independent observations.

**Comment by torognes** [comment]
Seems like [`fastx_uniques`](http://drive5.com/usearch/manual/cmd_fastx_uniques.html) is quite similar to [`derep_fulllength`](http://drive5.com/usearch/manual8.1/cmd_derep_fulllength.html) in usearch, except for the handling of quality scores and the additional `tabbedout` and `fastqout` options.

**Comment by frederic-mahe** [comment]
There are many different ways to handle quality values when dereplicating fastq files. I am not entirely sure which one is the best:

- ignore, and output a quality line with default values,
- retain the first quality line for each set of identical sequences,
- retain the last,
- retain a pseudo-randomly chosen line,
- using the global EE (expected error):
  - retain the highest EE,
  - retain the average EE (??),
- using per-position quality values:
  - retain the highest value for each position,
  - retain the average value for each position (?),
  - treat each observation of the same sequence as an update, and recompute quality values for each position

That last option could behave like the `--fastq_mergepairs` command, which uses a formula to compute new quality values from two independent observations ([Edgar and Flyvbjerg, 2015](https://doi.org/10.1093/bioinformatics/btv401)). It is likely to produce dereplicated sequences with nearly-perfect quality values (40 or 41), at least for sequences observed a great many number of times.

**Comment by torognes** [comment]
Thanks for the summary, @frederic-mahe.

This issue has also been raised in the forum:

https://groups.google.com/g/vsearch-forum/c/U6tJQow4XX8

**Comment by torognes** [comment]
Yes, the Edgar & Flyvbjerg approach quickly gives very high scores. In practice the scores are approximately equal to the sum of the quality scores + 5. So if you have one base with quality score 20 (corresponding to an error prob. of 0.01) and one base with quality score 30 (corresponding to 0.001), the resulting score is 55 (corresponding to 0.000003), which is truncated to 41.

I guess the appropriate value depends to the circumstances and the application.

USEARCH seems to take the average of the error probabilities (not documented). I find it hard to find a good justification for this choice. Taking the maximum of the quality scores appears more natural.

I am implementing this command now. I'll probably go for the USEARCH choice for compatibility reasons, but could add an option to choose an alternative, for instance the best quality score in each position.

**Comment by torognes** [comment]
The `fastx_uniques` command is available in commit d881fa85f0abebc75eb848360358af616b498f89.

**Comment by torognes** [comment]
Added the `fastq_qout_max` option to use the best quality instead of the default in commit 935c8f3666e7adef6230aa3846cf83aee1f7d1f1.

**Comment by torognes** [comment]
It is now available in the new [release 2.20.0](https://github.com/torognes/vsearch/releases/tag/v2.20.0).

**Comment by frederic-mahe** [comment]
Awesome! I am going to close that issue then.

**Comment by DorienAertarctica** [comment]
Hi, 

I wanted to apply --fastx_uniques today, but got the error:

vsearch: unrecognized option '--fastx_uniques'

This is my vsearch version:
vsearch v2.15.2_linux_x86_64, 31.3GB RAM, 4 cores
https://github.com/torognes/vsearch

Rognes T, Flouri T, Nichols B, Quince C, Mahe F (2016)
VSEARCH: a versatile open source tool for metagenomics
PeerJ 4:e2584 doi: 10.7717/peerj.2584 https://doi.org/10.7717/peerj.2584

Compiled with support for gzip-compressed files, and the library is loaded.
zlib version 1.2.12, compile flags a9
Compiled with support for bzip2-compressed files, and the library is loaded.

Is there a new updatet command for this specific function?

**Comment by torognes** [comment]
Hi @DorienAertarctica, you need at least version 2.20.0 to use the `fastx_unqiues` command.
