### ISSUE TITLE
Minimal valid SFF files and where to find them?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#352]
Hi,

to stress-test the new `sff_convert` command, I have been trying to build a minimal valid sff file. The smallest sff file I have found so far is 73 kilobytes (from biopython's tests). Fuzzing strategies would run much faster if I could find smaller files.

So far I've tried [454sim](https://bmcresnotes.biomedcentral.com/articles/10.1186/1756-0500-4-449) to produce a sff file with only one read and one flow cycle (i.e. one nucleotide). The resulting sff file is tiny (only 72 bytes!), but it seems that `454sim` produces invalid files with incorrect `clip_qual_left` values according to `vsearch` (the value is probably missing).
```sh
./454sim -a 1 -n 1 -o test.sff <(printf ">s\nA\n") ; vsearch --sff_convert test.sff --fastqout -
```
I'd welcome any suggestion on how to produce or where to find tiny sff files.

**Comment by torognes** [comment]
I could manually create a valid single-nucleotide minimal SFF-file if that would help.

**Comment by frederic-mahe** [comment]
If that's not to much tedious or time consuming to do, that would be great for fuzzing and for unit testing, thanks.

**Comment by torognes** [comment]
Here is a minimal SFF file of 72 bytes (gzipped due to GitHub restrictions): [minimal.sff.gz](https://github.com/torognes/vsearch/files/2727933/minimal.sff.gz)

And here is the perl code used to generate it:

```pl
#!/usr/bin/perl -w

# Generate a valid minimalistic SFF file

open(my $out, '>:raw', 'minimal.sff') or die "Unable to open: $!";

## main header

# .sff magic
print $out pack('A4', ".sff");

# version 1
print $out pack('L>', 1);

# no index
print $out pack('Q>', 0);
print $out pack('L>', 0);

# 1 read
print $out pack('L>', 1);

# header length 40
print $out pack('S>', 40);

# key length 4
print $out pack('S>', 4);

# flows per read 1
print $out pack('S>', 1);

# flowgram format code (1)
print $out pack('C', 1);

# flows: T
print $out pack('A1', "T");

# key: TCAG
print $out pack('A4', "TCAG");

# padding: 4 bytes
print $out pack('a4', "");


## read header

# read header length: 24
print $out pack('S>', 24);

# name length: 1
print $out pack('S>', 1);

# number of bases: 1
print $out pack('L>', 1);

# clip qual left: 1
print $out pack('S>', 1);

# clip qual right: 1
print $out pack('S>', 1);

# clip adapter left: 0
print $out pack('S>', 0);

# clip adapter right: 0
print $out pack('S>', 0);

# name: "1"
print $out pack('a', "1");

# padding: 7 bytes
print $out pack('a7', "");


# flowgram 100 (1.00)
print $out pack('S>', 100);

## flow indices: 1
print $out pack('C', 1);

## sequence: T
print $out pack('a', "T");

## quality scores: 40
print $out pack('C', 40);

# padding: 3 bytes
print $out pack('a3', "");

close($out);
```

**Comment by frederic-mahe** [comment]
Awesome! I've launched [afl-fuzz](http://lcamtuf.coredump.cx/afl/) on the `--sff_convert` command. No crash case so far, and the exploration of all execution paths seems to be over.

By the way, shouldn't `clip qual left` be 0, and `clip adapter right` be 1?

**Comment by frederic-mahe** [comment]
I've used that minimal SFF file for fuzzing tests (no crash generated), and to write basic tests for the `sff_convert` command.

To understand how the minimal SFF file is structured, I recreated it using `printf` commands in a bash script. Do you mind @torognes if I keep only the bash version and do not include your perl script in the vsearch-tests repository? I like the idea of using only bash commands and GNU tools to write the tests.

**Comment by torognes** [comment]
Of course, no problem!
