### ISSUE TITLE
VSEARCH 2.10.3 produces wrong alignments - Do not use

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#356]
I discovered today that version 2.10.3 produces wrong alignments. It should not be used.

**Comment by torognes** [comment]
Version 2.10.2 is ok.

**Comment by frederic-mahe** [comment]
@torognes if you happen to have an example of input resulting in a bad alignment (v2.10.3) vs. a good alignment (v2.10.2), maybe we could use it as a regression test for future vsearch releases?

**Comment by torognes** [comment]
Many of the tests of allpairs_global, uchime_denovo, and usearch_global failed, as well as the Flouri 2015 pairwise alignment correctness tests. For instance the test described as `--usearch_global --blast6out finds the correct target`.

I ran all the tests several times during development and before the release, and compared them to previous results, exactly to avoid this incident, but I must have mixed up some of the executables and compared the wrong versions.

I hope to find the bug today.

**Comment by frederic-mahe** [comment]
It happens, don't worry. I am not sure the latest vsearch version was installed and used by many people during the holidays anyway.

We could modify the test scripts so they accept an optional argument (`/path/to/dev/vsearch` for example). That would make it easier to test different vsearch binaries.

**Comment by torognes** [comment]
I was also thinking about adding that optional argument, but I found a different solution.

I have a wrapper script to automate the test process. It first adds the directory with the development binary into the beginning of the `$PATH`. It then runs `run_all_tests.sh` and writes the output to a log file with the current date and time in the filename. Finally it compares the log file to a baseline log file with diff.

This makes it easy to see if there were any (negative) changes.

**Comment by torognes** [comment]
I have found the bug. It was just a set of missing parentheses.

**Comment by torognes** [comment]
Fixed in version 2.10.4, just released.
