### ISSUE TITLE
Make fastq_filter operate on pairs of fastq files

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#359]
When filtering fastq files with the `fastq_filter` or `fastx_filter` commands it would be beneficial to be able to filter out reads from both the forward (R1) and the reverse (R2) read files at the same time, if at least one of the reads is bad. Perhaps the reverse read file could  be specified with the `--reverse` option as with `fastq_mergepairs`. An option for specifying the name of the output file of reverse reads would be needed too (e.g. `--fastqout_rev`).

**Comment by frederic-mahe** [comment]
usearch11 has a somewhat related option [--fastx_syncpairs](https://www.drive5.com/usearch/manual/cmd_fastx_syncpairs.html):
> sorts paired reads so that the reads appear in the same order in both files. If a read label appears in one file and not the other, it is discarded. The input files can be in FASTA or FASTQ format.

usearch also has commands that could be **options** of our `--fastx_filter` command:
>  fastx_getseq  Extract sequence(s) matching label
>  fastx_getseqs  Extract sequence(s) matching labels
>  fastx_getsubseq  Extract subsequence given label, start, stop

**Comment by frederic-mahe** [comment]
As of now, here are the options accepted by `--fastx_filter`:
```
Filtering
  --fastx_filter FILENAME     filter and truncate sequences in FASTA/FASTQ file
  --fastq_filter FILENAME     filter and truncate sequences in FASTQ file
 Parameters
  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)
  --fastq_maxee REAL          maximum expected error value for filter
  --fastq_maxee_rate REAL     maximum expected error rate for filter
  --fastq_maxlen INT          maximum length of sequence for filter
  --fastq_maxns INT           maximum number of N's for filter
  --fastq_minlen INT          minimum length of sequence for filter
  --fastq_qmax INT            maximum base quality value for FASTQ input (41)
  --fastq_qmin INT            minimum base quality value for FASTQ input (0)
  --fastq_stripleft INT       bases on the left to delete
  --fastq_stripright INT      bases on the right to delete
  --fastq_truncee REAL        maximum total expected error for truncation
  --fastq_trunclen INT        truncate reads to length INT (discard if shorter)
  --fastq_trunclen_keep INT   truncate reads to length INT (keep if shorter)
  --fastq_truncqual INT       minimum base quality value for truncation
  --maxsize INT               maximum abundance
  --minsize INT               minimum abundance
 Output
  --eeout                     include expected errors in output
  --fastaout FILENAME         FASTA output filename for passed sequences
  --fastaout_discarded FNAME  FASTA filename for discarded sequences
  --fastqout FILENAME         FASTQ output filename for passed sequences
  --fastqout_discarded FNAME  FASTQ filename for discarded sequences
  --relabel STRING            relabel filtered sequences with given prefix
  --relabel_keep              keep the old label after the new when relabelling
  --relabel_md5               relabel filtered sequences with md5 digest
  --relabel_sha1              relabel filtered sequences with sha1 digest
  --sizeout                   include abundance information when relabelling
  --xsize                     strip abundance information in output
```
Given that some options *truncate*, the section title could be `Filtering and truncate`.

`--fastq_filter` could be marked as deprecated, with a warning indicating to use `--fastx_filter`.

filters would apply to both R1 and R2 reads

All output file options would need to be doubled with a `_reverse` version.

`--relabel` options could be confusing, as R1 and R2 reads would end up with different names.  

`--xee` is missing to mirror the `--sizeout, --xsize` options (issue #276).

**Comment by torognes** [comment]
Filtering of paired reads with `fastx_filter` and `fastq_filter` is added in version 2.11.0 just released. Reverse sequences specified with `--reverse`. Both R1 and R2 must pass the requirements for both to be kept, otherwise they will both be discarded. Output files for R2 sequences specified with `fastaout_rev`, `fastqout_rev`, `fastaout_discarded_rev`, `fastqout_discarded_rev`.

The `-xee` option is added too.

**Comment by ZeweiSong** [comment]
It would help if you can clarify whether the output of _rev is reverse complimented.

Thanks!

**Comment by torognes** [comment]
Yes, you are right. It is a bug. VSEARCH currently writes the R1 reads to the file specified with the `--fastaout_rev` option. It seems like the other similar options work as they should. 

Thank you for spotting this bug and reporting it.

I see you have opened a new issue for the bug. Thanks. I will respond to the bug there. I have already found the error in the code.
