### ISSUE TITLE
Is there a way of outputting % id to centroid?

### ISSUE THREAD

**Issue by vinisalazar** [torognes/vsearch#360]
Hello,

I'm trying to cluster same-length sequences. Is there a way for me to know the percentage ID of each sequence to the centroid it is attributed? e.g.: Cluster threshold is 0.95, I want to know if an input sequence is 0.98, 0.99 or 1 similar to the output centroid. I did my best reading the help menus and documentation but could not find an answer.

Thank you for any assistance you can provide, and also for this package as a whole, it is awesome.

Bw,
V

**Comment by colinbrislawn** [comment]
Good afternoon.

I think you could find this by outputting a .uc file. 
`vsearch --cluster_size file.derep.fna --id 0.90 --uc file.derep.90.uc`
The .uc file has several columns with the information you need.
```text
S	0	251	*	*	*	*	*	M03018:112:000000000-C4H3L:1:1101:10418:25550	*
H	0	251	99.6	+	0	0	251M	M03018:112:000000000-C4H3L:1:1101:10456:5885	M03018:112:000000000-C4H3L:1:1101:10418:25550
H	0	251	99.2	+	0	0	251M	M03018:112:000000000-C4H3L:1:1101:10702:11100	M03018:112:000000000-C4H3L:1:1101:10418:25550
H	0	251	99.2	+	0	0	251M	M03018:112:000000000-C4H3L:1:1101:10881:2539	M03018:112:000000000-C4H3L:1:1101:10418:25550
H	0	251	99.2	+	0	0	251M	M03018:112:000000000-C4H3L:1:1101:10885:2244	M03018:112:000000000-C4H3L:1:1101:10418:25550
H	0	251	99.6	+	0	0	251M	M03018:112:000000000-C4H3L:1:1101:11060:12216	M03018:112:000000000-C4H3L:1:1101:10418:25550
```

Centroids have an S in the first column, while hits to a centroid have an H. The 4th column shows the global alignment similarity to the centroid listed above.

Let me know if this helps, and if it does, feel free to close this issue.

**Comment by vinisalazar** [comment]
This definitely helps. Thank you very much.

**Comment by vinisalazar** [comment]
@colinbrislawn would you know the content of the other columns?

**Comment by vinisalazar** [comment]
Never mind. I found it here: http://www.drive5.com/uclust/uclust_userguide_1_1_579.html#_Toc257997702

Thank you for your help, @colinbrislawn

**Comment by colinbrislawn** [comment]
Glad you found it so fast 👍 

These are also listed in the vsearch manual, on page 10. 
https://github.com/torognes/vsearch/releases/download/v2.11.0/vsearch_manual.pdf
