### ISSUE TITLE
Could cluster_fast build consensus based on abundances?

### ISSUE THREAD

**Issue by dgg32** [torognes/vsearch#363]
Dear developer. For example, take the following three nearly identical sequences, the seq_2 and the seq_3 are the same and they differ from seq_1 in their fifth base, the abundances are seq_1: 10, seq_2: 1 and seq_3: 1:

[test.txt](https://github.com/torognes/vsearch/files/2900921/test.txt)

Now I run cluster_fast like this:

`vsearch --quiet --cluster_fast test.txt --id 0.995 --gapext 5I --gapopen 5I --minseqlength 1200 --centroids test.txt_vsearch_cluster_fast_0.995_centroid.fna --uc test.txt_vsearch_cluster_fast_0.995_centroid_uc.txt --iddef 0 --msaout test.txt_vsearch_cluster_fast_0.995_msa_1.fasta --consout test.txt_vsearch_cluster_fast_0.995_cons.fasta --sizein --sizeout`

I got the my seq_2 / seq_3 as the consensus sequence, even though sequence seq_1 has an abundance of 10.

I wonder if it is possible to build the consensus based on the sequence abundances? Thank you!

**Comment by dgg32** [comment]
It seems cluster_size fits the bill. Thanks!

**Comment by dgg32** [comment]
After some tests, it is clear that cluster_size didn't build the consensus based on "size=" either. Therefore I would like to reopen the issue. Thanks!

**Comment by torognes** [comment]
The `cluster_size` command should always use the most abundant sequence in the cluster as the centroid. The consensus sequence is created from the most abundant bases in each position after a simple multiple sequence alignment. Remember to use the `--sizein` option.

Could you present a small example showing how the results deviate from what you expected?

**Comment by dgg32** [comment]
@torognes Thanks for the reply.

I have the following test.txt
[test.txt](https://github.com/torognes/vsearch/files/2915052/test.txt)

The two sequences are nearly identical except the 4th base, the first one with a size of 2 has a G and the second one with a size of 21734 has a T.

then I run:

vsearch --quiet --cluster_size 'test.txt' --id 0.999 --gapext 5I --gapopen 10I --minseqlength 1200 --consout 'test_uc.txt' --iddef 0  --sizein --sizeorder --sizeout

I got 
[test_uc.txt](https://github.com/torognes/vsearch/files/2915064/test_uc.txt)

In this consensus, the 4th base is G (from the size=2) instead of the expected T (from the size=21736). In fact, we have discovered that in the 50/50 situation, it doesn't matter what the sizes are, vsearch picks the consensus base the along alphabetic order, so A>C>G>T.

Thank you.

**Comment by torognes** [comment]
Ah, now I see the problem: vsearch fails to take the sequence abundances into account when computing the consensus sequence.

Thanks for reporting this problem. I'll try to fix it soon.

**Comment by torognes** [comment]
Here is a small example illustrating the problem.

Input (`input.fasta`):

```
>1;size=10
TAAAAAAAAAA
>2;size=1
GAAAAAAAAAA
>3;size=1
GAAAAAAAAAA
```

Command:

```
vsearch --cluster_size input.fasta --consout consensus.fasta --id 0.9 --minseqlength 1
```

Output (`consensus.fasta`):

```
>centroid=1;size=10;seqs=3
GAAAAAAAAAA
```

Expected output (since `T` has abundance 10, while `G` has abundance 2):

```
>centroid=1;size=10;seqs=3
TAAAAAAAAAA
```

**Comment by frederic-mahe** [comment]
This issue is now covered by a test (https://github.com/frederic-mahe/vsearch-tests/commit/82d7ecd6403d03d15951d0cd74ebd2456a88e6db).

**Comment by torognes** [comment]
Fixed in commit 5d7091e2584ba0c9593c8b087f045cef13ca479d

**Comment by torognes** [comment]
The code was changed in commit 14e7baf68ab1913ce5d5d14379ec195e0aaa2624 to only take abundances into account when the `sizein` option was specified. This was included in order to be consistent with other clustering behaviour.

**Comment by frederic-mahe** [comment]
Test updated (add the `--sizein` option).
