### ISSUE TITLE
fatal error when running unoise

### ISSUE THREAD

**Issue by dcastaneda5** [torognes/vsearch#364]
Hi!
I am currently having a problem whenever I try to remove the chimeras from a .fasta file. First, I have a .fastq file that I converted to .fasta in order to remove the chimeras with the 'unoise3' command (I understand that vsearch has a similar command, which I ran). The following shows what appears on my terminal:

usearch v11.0.667_i86osx32, 4.0Gb RAM (8.6Gb total), 4 cores
(C) Copyright 2013-18 Robert C. Edgar, all rights reserved.
https://drive5.com/usearch

License: daniel.castanedamogo@ucalgary.ca

00:00 50Mb    100.0% Reading msp_project/fastq_files/filtered/s1trim_S1_L001_R1_001.fastq

```

./usearch -unoise3 msp_project/fastq_files/filtered/s1trim_S1_L001_R1_001.fastq -zotus msp_project/fastq_files/filtered/zotus.fa -tabbedout msp_project/fastq_files/filtered/unoise3.txt

---Fatal error---
Missing size= in >M01716:90:000000000-D3KL4:1:1101:18368:1710 1:N:0:TAAGGCGA+TCGACTAG
Daniels-MacBook-Pro-3:Seagate Danniel$ 
```

A similar thing happens when I ran 'cluster_unoise'. Maybe I'm missing something... The file I am trying to remove the chimeras from is also attached as .fasta and .fastq 
[s1trim_S1_L001_R1_001.fastq.gz](https://github.com/torognes/vsearch/files/2908023/s1trim_S1_L001_R1_001.fastq.gz)
[sample1_trim_forw.fasta.gz](https://github.com/torognes/vsearch/files/2908028/sample1_trim_forw.fasta.gz)

Thank you!!

**Comment by torognes** [comment]
Hi @dcastaneda5 !

First, this site is for the program `vsearch`. For support regarding `usearch`, please see [drive5.com/usearch](http://drive5.com/usearch) or contact the author Robert Edgar.

It seems like the input file you are using (`s1trim_S1_L001_R1_001.fastq`) is a FASTQ file, not a FASTA file. It needs to be converted first.

You could do that with vsearch with the following command:

```
vsearch --fastx_filter input.fastq --fastaout converted.fasta
```

As the error message indicates (`Missing size= in `...), an abundance value (size) is required for each sequence. You need to dereplicate (and possibly cluster) your sequences with the `--sizeout` option before detecting chimeras. Abundance values will then be added to the sequence headers (e.g. `;size=123`). It can be performed like this:

```
vsearch --derep_fulllength converted.fasta --sizeout --output dereplicated.fasta 
```

Note that vsearch can read compressed files (.gz) directly. I do not think usearch supports this.

There is also a difference between how the `unoise3` command in usearch works on how it works in vsearch. In vsearch you need to run `cluster_unoise` first and then `uchime3_denovo`. Please see the manual for details.

**Comment by torognes** [comment]
@dcastaneda5, did my suggestions help?

**Comment by dcastaneda5** [comment]
Hi @torognes !, Sorry for my late response. In fact it did! Apologies, I thought you guys were also the developers of usearch! Thanks a lot!
