### ISSUE TITLE
Handling of empty input files

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#366]
A user reported that vsearch terminated with a fatal error when running the `fastq_mergepairs` command on an empty input file.

It may be more appropriate to issue a warning and generate empty output in such cases, instead of terminating with an error. It probably applies to other commands as well.

When used in a pipeline, some input files may be empty because all sequences have been filtered away earlier. It could then be an advantage that vsearch handles these cases well.

**Comment by frederic-mahe** [comment]
```sh
vsearch --fastq_mergepairs <(printf "") --reverse <(printf "") --fastqout -
```
indeed, vsearch terminates with an error:
```
vsearch v2.11.1_linux_x86_64, 62.8GB RAM, 8 cores
https://github.com/torognes/vsearch

Fatal error: File too small
```

Check if an output file is created:
```sh
vsearch --fastq_mergepairs <(printf "") --reverse <(printf "") --fastqout tmp.fastq
cat tmp.fastq
```
The declared output file is not created:
```
vsearch v2.11.1_linux_x86_64, 62.8GB RAM, 8 cores
https://github.com/torognes/vsearch

Fatal error: File too small
cat: tmp.fastq: No such file or directory
```

I agree with changing that fatal error into a warning, to avoid disrupting pipelines potentially handling hundreds of samples.

**Comment by frederic-mahe** [comment]
And swarm already behaves like that (it happily accepts an empty input file and creates empty output files if need be, see commit https://github.com/frederic-mahe/swarm-tests/commit/b7cd799f105686f3f19a25fac6eb8e5fe2153daa).

**Comment by frederic-mahe** [comment]
I've written preliminary tests to cover this issue (see commits https://github.com/frederic-mahe/vsearch-tests/commit/578337eeb6eff137e51e3efebf04a101b79c4a9c and https://github.com/frederic-mahe/vsearch-tests/commit/231f21b0b0936be109aba80c260344f63aca5301).

**Comment by mrmrwinter** [comment]
Hi,

Has there been any progress on this?
Or does anyone have a tidy workaround?

Cheers

**Comment by torognes** [comment]
Sorry, not yet.

**Comment by frederic-mahe** [comment]
I've stumbled on that issue again. I use named pipes to connect the different steps of my pipeline, and on certain data sets the pipeline stalls, waiting for `vsearch` to create and close its output stream, which `vsearch` does not do when input files are empty.

As a workaround, I pre-filter my gziped R1 and R2 fastq files to process only pairs of non-empty files. That works but I'd prefer `vsearch` to handle empty input files gracefully, like `swarm` does.

**Comment by torognes** [comment]
Empty input files should now be handled well. Commit d43d37d03fb5f64f475b4e33c7d6aba6d57f205d.

**Comment by torognes** [comment]
It seems like this issue may still be present with dereplication and clustering. Reopening.

**Comment by torognes** [comment]
Fixed.
