### ISSUE TITLE
FreeBSD port committed

### ISSUE THREAD

**Issue by outpaddling** [torognes/vsearch#372]
FYI:

vsearch has been committed to the FreeBSD ports collection.
It might be helpful to users if you could post a message like
the following on your website:

Regards,

    Jason

vsearch can be installed on FreeBSD via the FreeBSD ports system.

To install via the binary package, simply run:

    pkg install vsearch

This will very quickly install a binary using only highly-portable
optimizations, much like apt-get, yum, etc.

FreeBSD ports can just as easily be built and installed from source,
although it will take longer (for the computer, not for you):

    cd /usr/ports/biology/vsearch
    make install

Building from source allows installing to a different prefix, compiling with
native optimizations, and in some cases, building with non-default options
such as different compilers or dependencies, e.g.:

    make CFLAGS+=-march=native install

To report issues with a FreeBSD port, please submit a PR at:

    https://www.freebsd.org/support/bugreports.html

For more information, visit https://www.freebsd.org/ports/index.html.

**Comment by torognes** [comment]
Thanks!

Would it be sufficient if I add the following text to the `README.md` file, under "Plugins, packages, and wrappers"?

**FreeBSD ports package** Thanks to [Jason Bacon](https://github.com/outpaddling), a [vsearch](https://www.freebsd.org/cgi/ports.cgi?query=vsearch&stype=all) [FreeBSD ports](https://www.freebsd.org/ports/) package is available. Install the binary package with `pkg install vsearch`.

**Comment by outpaddling** [comment]
Whatever you're comfortable with.  The main thing is to make visitors aware that it can be easily installed on FreeBSD.  I would suggest mentioning building from source with additional optimizations, even though the binary always contains SSE code.  It may not help much with vsearch right now, but it's a good thing to know about in general.  Thanks!

**Comment by torognes** [comment]
I have added the information to the README file now.

**Comment by outpaddling** [comment]
Standard notification for pkgsrc package below.  I imagine you'll distill it similar to the FreeBSD announcement for your README.

Cheers,

    Jason

===

FYI:

vsearch has been committed to the pkgsrc package collection.
It might be helpful to users if you could post a message like
the following on your website:

Regards,

    Jason

vsearch can be installed on most POSIX platforms using the pkgsrc
package manager.

Binary packages are available for Mac OS X, NetBSD, RHEL/CentOS,
and SmartOS. To install via the binary package, simply run:

    pkgin install vsearch

This will very quickly install a binary using only highly-portable
optimizations, much like apt-get, yum, etc.

Pkgsrc packages can just as easily be built and installed from source,
although this will take more time:

    cd /usr/pkgsrc/category/vsearch
    [b]make install

Building from source allows installing on virtually any POSIX platform,
installing to a different prefix, compiling with additional options, and in
some cases, building with non-default options such as different compilers
or dependencies, e.g.:

    [b]make CFLAGS=-march=native install

To report any issues, please submit a PR at:

    https://www.netbsd.org/support/send-pr.html

For more information, visit https://www.pkgsrc.org.

**Comment by torognes** [comment]
Thanks, I've added information about the pkgsrc package to the README.

**Comment by outpaddling** [comment]
Fabulous, thanks!
