### ISSUE TITLE
Big endian PPC?

### ISSUE THREAD

**Issue by outpaddling** [torognes/vsearch#373]
How hard would it be to make the code endian-agnostic?

As I'm sure you're aware, many operating systems run in big-endian mode on powerpc.

I could run tests on my G5 under FreeBSD if you're interested in pursuing this.  Not that I do real genomics work on this machine, but a working port would be useful to people with power8/9 servers.

Cheers,

    Jason

**Comment by torognes** [comment]
As far as I remember, some of the vector intrinsics used in the alignment are dependent on the endianness. I am sure it's possible to make big-endian code as well, but it seems like the market for big-endian Power8 with the necessary vector extensions is rather small. I do not have access to any such systems either. It has therefore not been a priority.

**Comment by outpaddling** [comment]
Yeah, we're probably talking about ~0.1% of vsearch users.  If anything, I would maybe replace the instances of "#error Unknown architecture" with some generic, portable C code.  Then at least everyone could run vsearch, if not optimally.  Not a high priority, just a thought.
