### ISSUE TITLE
Suspected incorrect cluster results

### ISSUE THREAD

**Issue by chaibenl** [torognes/vsearch#375]
My installed version of VESEARCH2.13.0 clustered two very different sequences into one cluster. Is it a correct behavior ?  USEARCH clustered them into two separate clusters. Thank you.   --Benli Chai

I used the command:
vsearch --cluster_fast test.fasta --sizein --sizeout --id 1.00 --uc test.uc --centroid test_centroid.fasta

Input file:
>CP000255.1_1;size=2-------------------------------------------------------------------------------------------                                                           GAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGCAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGATGTGCGAAAGCGTGGGGATCAAACAGGATTAGATACCCTGGTAG                                     
>CP000255.1_2;size=2                                                                                                                                                                       
TCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAGTGCTAAGTGTTAGGGGGTTTCCGCCCCTTAGTGCTGCAGCTAACGCATTAAGCACTCCGCCTGGGGAGTACGACCGCAAGGTTGAAACTCAAAGGAATTGACGG

Output uc file content
S>--0>--150>*>--*>--*>--*>--*>--CP000255.1_1;size=2>*                                                                                                                                      
H>--0>--150>100.0>--+>--0>--0>--124I26M124D>CP000255.1_2;size=2>CP000255.1_1;size=2                                                                                                        
C>--0>--4>--*>--*>--*>--*>--*>--CP000255.1_1;size=2>*

**Comment by colinbrislawn** [comment]
I think an important clue is that both these sequences are 100% identical in a section. I've highlighted that section here.
<img width="831" alt="Screen Shot 2019-05-17 at 3 14 26 PM" src="https://user-images.githubusercontent.com/10355152/57958961-7ee79d00-78b6-11e9-9eae-a47445127460.png">

In the context of 'glocal' alignments (global alignment that ignore terminal gaps), this section might be enough to group these reads together. After all, they _are_ 100% identical (if you ignore the terminal gaps!).

Don't want that to happen? Try changing the `--target_cov` setting to force more of the reads to overlap, or use `--iddef 1` to include terminal gaps in the alignment scoring.

**Comment by chaibenl** [comment]
Hi, Colin,

Great! '--iddef 1' is the option I need. Thank you so much for quick help.

Benli

**Comment by frederic-mahe** [comment]
This is now covered by a regression test (https://github.com/frederic-mahe/vsearch-tests/commit/59fdb6439a46bba29821a365df82475b60e2077d).
