### ISSUE TITLE
unrecognized function '--cluster_smallmen'

### ISSUE THREAD

**Issue by henganl2** [torognes/vsearch#376]
Hi, 

I was trying to use vsearch to precluster the reads and produce a consensus sequence for each cluster.  The vsearch version is 2.4.3.

here is my code: 

`vsearch --cluster_smallmen input.fasta --msaout output.fasta --id 0.99`

And I get an error: 
`vsearch: unrecognized option '--cluster_smallen`

Did I miss something in the code? 
It will be appreciated if you can help me out!
Thanks in advance.

**Comment by torognes** [comment]
Hi, the name of the command is `cluster_smallmem` with an `m` at the end (for small memory).

**Comment by henganl2** [comment]
Thanks so much!

**Comment by frederic-mahe** [comment]
Just in case, I checked if `smallmem` was not written correctly somewhere in our documentation (readme, help and manpage). All good.
