### ISSUE TITLE
How to trim paired fastq files that got out-of-sync?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#377]
(issue title could be improved)

Lucio Marcello asked what to do when vsearch fails to merge paired fastq files because one file contains more reads than the other.

Each file can be viewed as a unique set of reads. Both files can contain exactly the same set of reads (normal situation), or one file can be truncated (set B is a subset of set A), or both files can have specific reads (intersection of sets contains less reads than the smallest set).

In paired fastq files, reads are normally in the same order. If that is the case, finding and extracting common reads is easy with shell commands. If read order is shuffled, then read sets must be sorted first, which can be computationally intensive.

Let's see how the situation can be fixed.

**1 - read order is preserved**
```sh
cd /tmp/

## R1 and R2 have read s2 in common
printf "@s1 1\nA\n+\nI\n@s2 1\nC\n+\nI\n" > R1.fq
printf "@s2 2\nG\n+\nI\n@s3 2\nA\n+\nI\n" > R2.fq

## find reads common to R1 and R2, output new fastq files
join \
    -t " " \
    -o 0,1.2,0,2.2 \
    <(paste - - - - < R1.fq) \
    <(paste - - - - < R2.fq) | \
    tee >(cut -d " " -f 3,4 | tr "\t" "\n" > R2_trim.fq) | \
    cut -d " " -f 1,2 | tr "\t" "\n" > R1_trim.fq

## non-common reads have been removed
cat R1_trim.fq ; echo ; cat R2_trim.fq
rm R{1,2}{,_trim}.fq
```

**2 - read order is shuffled**
```sh
cd /tmp/

## R1 and R2 have common reads, but not in the same order
printf "@s1 1\nA\n+\nI\n@s2 1\nC\n+\nI\n" > R1.fq
printf "@s2 2\nG\n+\nI\n@s1 2\nT\n+\nI\n" > R2.fq

## sort R1 and R2, find common reads, output new fastq files
join \
    -t " " \
    -o 0,1.2,0,2.2 \
    <(paste - - - - < R1.fq | sort -k1,1d) \
    <(paste - - - - < R2.fq | sort -k1,1d) | \
    tee >(cut -d " " -f 3,4 | tr "\t" "\n" > R2_trim.fq) | \
    cut -d " " -f 1,2 | tr "\t" "\n" > R1_trim.fq

## common reads have been reordered
cat R1_trim.fq ; echo ; cat R2_trim.fq
rm R{1,2}{,_trim}.fq
```

**Comment by colinbrislawn** [comment]
>If read order is shuffled, then read sets must be ordered first, which can be computationally intensive.

The [bbtools suit](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/repair-guide/) includes the repair.sh script for reordering reads. This functionality could be built into vsearch as an extra option, or we could simply point people to the bbtools package.

**Comment by torognes** [comment]
There is also a tool called FASTQ PAIR, but I haven't tested it.

https://github.com/linsalrob/fastq-pair

I do not think it will be difficult to implement it, but is it worth prioritizing?

**Comment by frederic-mahe** [comment]
My intent is to offer solutions written in shell. A mix of `paste`, `sort`, `join` should be enough to fix mangled paired fastq files. I don't think a dedicated `vsearch` function is necessary.

**Comment by frederic-mahe** [comment]
That's it. The shell code demonstrated above should be efficient enough to deal with gigabyte-sized fastq files.
