### ISSUE TITLE
Reverse complement sequences during clustering

### ISSUE THREAD

**Issue by saanasum** [torognes/vsearch#379]
Is there an option to define that sequences are also treated as reverse complementary during clustering. As far as I can see, it currently only takes sequences as they are provided for clustering, and they are not treated reverse complementary. 

This can be useful to create only one sequence cluster per genomic locus and not two clusters (both representing bot DNA strands, respectively).

**Comment by torognes** [comment]
Yes, you may use the option `--strand both` to cluster sequences from both strands (forward and reverse-complemented). The default is `--stand plus` which uses only the forward strand. This should work with the `--cluster_size`, `--cluster_fast`, `--cluster_smallmem` and `--cluster_unoise` commands.

Sorry for the late reply.

**Comment by saanasum** [comment]
Thank you :)
