### ISSUE TITLE
Having difficulty using evalue in vsearch 2.4.3

### ISSUE THREAD

**Issue by slvrshot** [torognes/vsearch#380]
I have been using usearch for a long time to blast search my sequence data for candidate sequences. For a while this was okay, especially several years ago, but now datasets have ballooned exponentially and usearch doesn't seem like the best option anymore especially considering how its closed-sourced and limited in functionality if you don't pay for it. Anyway here is my original code:

`ls *.fa | parallel --gnu "usearch -ublast {} -db /Users/macbook/Training/BacMet2_EXP_database.fasta -evalue 1e-5 -accel 0.5 -blast6out {/.}.ublast_output_file.txt -threads 4"`

I adapted this to vsearch by changing a few things:

`ls *.fa | parallel --gnu "vsearch -usearch_global {} -db /Users/macbook/Training/BacMet2_EXP_database.fasta -evalue 1e-5 -blast6out {/.}.ublast_output_file.txt -threads 4"`

It doesn't appear to like the evalue command. Is this not supported or is there an equivalent feature for my version of vsearch?

**Comment by colinbrislawn** [comment]
Welcome to vsearch! I also switched over to vsearch and have really liked it!

Vsearch uses identity scores not evalues to set cutoffs. 🤷‍♂ 
>**evalue** E-value (not computed for nucleotide alignments). Always set to -1.

So... do you want evalues or id values? evalues can vary based on the size and complexity of the database, but 90% identical is always pretty clear. Do you think setting `--id` and `--query_cov` could work well for you?

---

Each time the search is run, usearch_global has to reindex the database. If you have *lots* of .fa files, `--makeudb_usearch` and `--udb2fasta` could help speed this up!

**Comment by slvrshot** [comment]
> Welcome to vsearch! I also switched over to vsearch and have really liked it!
> 
> Vsearch uses identity scores not evalues to set cutoffs. 🤷‍♂
> 
> > **evalue** E-value (not computed for nucleotide alignments). Always set to -1.
> 
> So... do you want evalues or id values? evalues can vary based on the size and complexity of the database, but 90% identical is always pretty clear. Do you think setting `--id` and `--query_cov` could work well for you?
> 
> Each time the search is run, usearch_global has to reindex the database. If you have _lots_ of .fa files, `--makeudb_usearch` and `--udb2fasta` could help speed this up!

Hi Colin. Interesting running into you again. You've helped me in the past during the Qiime 1.8 days. Anyway, I have some very large .fasta file....roughly 257 GB of read data, split into 48 files...24 samples. 

My query database is BacMet 2 which contains 753 experimentally confirmed amino acid sequences. I used this database fine through a ublast search using USEARCH but so far I haven't had much luck using VSEARCH. 

I am following a protocol originally developed in this journal article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4210140/

Essentially ublast to obtain candidate sequences, extract sequences, then diamond blastx...extract again. I've had great success using this workflow but I had to chop up my sequencing data and concatenate it later because of the limitations of USEARCH 32....which can be quite annoying.

Anyhow I'm looking to adapt this workflow using vsearch as the initial blast search. The authors in the paper above recommended an e-value of 1e-5. I tried the above commands and vsearch failed to find anything at an identity score of 80%.

Any suggestions?

**Comment by colinbrislawn** [comment]
It's good to talk with you again. I'm glad we are both still out here doing science!

> 753 experimentally confirmed **amino acid** sequences

Unlike usearch, vsearch is nucleonic acid only. So maybe you could do this search with something like diamond or mmseqs2 (because these programs can do the dna -> aa mapping).

But wait! I have a good idea of what you could use vsearch to do!
> 257 GB of read data, split into 48 files

You could `--derep_fulllength --sizeout` on each of those files to remove any duplicate reads which should make the search faster.

**Comment by slvrshot** [comment]
> It's good to talk with you again. I'm glad we are both still out here doing science!
> 
> > 753 experimentally confirmed **amino acid** sequences
> 
> Unlike usearch, vsearch is nucleonic acid only. So maybe you could do this search with something like diamond or mmseqs2 (because these programs can do the dna -> aa mapping).
> 
> But wait! I have a good idea of what you could use vsearch to do!
> 
> > 257 GB of read data, split into 48 files
> 
> You could `--derep_fulllength --sizeout` on each of those 48 files to remove any duplicate reads which should make the search faster. Or maybe you have done some sort of preclustering already.

That's an interesting thought. I'm not too worried about the speed of the search. Since this is metagenomic data, I'm not sure if this is totally necessary.

**Comment by colinbrislawn** [comment]
OK. Let me know what you find!

As this is a DNA -> AA mapping (out of scope for vsearch, for now!), I think you could close this issue. But let me know if you find success with diamond or mmseqs2 for this job. I've used diamond a lot and have heard hype for mmseqs2, so I would appreciate your guidance on what works well for you.

**Comment by slvrshot** [comment]
> OK. Let me know what you find!
> 
> As this is a DNA -> AA mapping (out of scope for vsearch, for now!), I think you could close this issue. But let me know if you find success with diamond or mmseqs2 for this job. I've used diamond a lot and have heard hype for mmseqs2, so I would appreciate your guidance on what works well for you.

Yes I've used diamond before but supposedly this hybrid approach detailed in the paper above makes a significant speed improvement by quickly screening samples first using usearch then feeding that into diamond. Hopefully, AA mapping is added in the future.  

Thanks Colin.
