### ISSUE TITLE
Make OTU table directly?

### ISSUE THREAD

**Issue by fezoz** [torognes/vsearch#383]
Hi, I read an old thread (from 2016) about implementing a way of creating an OTU table directly without the need of the uc file and pearl scripts. I was wondering if its this is already available and if this is the right command for it:

vsearch --usearch_global sequences.fasta --db OTUs.fasta --id 0.97 --otutabout otutable.txt

if not, could anyone direct me where are those scripts to create an OTU table from uc files?

thank you !

**Comment by torognes** [comment]
Yes, you may output a OTU table directly from the clustering (`cluster_size`, `cluster_fast`, `cluster_smallmem`, `cluster_unoise`) and search commands (`usearch_global`, `search_exact`) in vsearch.

The file name for the table is specified with the `otutabout`, `biomout`, or `mothur_shared_out` options, depending on the format needed (classic, biom 1.0, or mothur, respectively).

The sequence headers may need to be in a specific format for vsearch to extract the sample and OTU identifiers. Please see the manual entries `otutabout`, `biomout`, or `mothur_shared_out` for details.

**Comment by fezoz** [comment]
Thanks both for your quick reply! I'm a bit confused on how the labeled_reads.fna should have size if they are all individual sequences prior dereplicating. 

my "labeled.reads.fna" headers look like :

> barcodelabel=sample1;sequencename

and my "otus.fna" headers look like this

> consensus=OTU_1;seqs=294;size=219980

When I use the command below I get that "seqs=" in the headers, but it doesn't match the "size".

`vsearch --cluster_size derep.fasta --id 0.97 --sizein --sizeout --relabel OTU_ --consout otu.fasta`

I do get an OTU table but I just want to make sure it is correct in the seq number of each OTU in each sample.

**Comment by torognes** [comment]
The number after `seqs=` should be the number of different sequences clustered. The number after `size=` should be the total number of reads in the cluster; it is equal to the sum of the `size` of each of the different sequences included in the cluster.

**Comment by colinbrislawn** [comment]
>Thanks both for your quick reply! I'm a bit confused on how the labeled_reads.fna should have size if they are all individual sequences prior dereplicating.

Good point. If you don't dereplicate your `labeled_reads.fna` this command would still work and you wouldn't have to include the `--sizein` command when running `vsearch --usearch_global`
