### ISSUE TITLE
Add option relabel_self to use sequence itself as a label in FASTA/FASTQ

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#384]
A new vsearch option to use the sequence itself as the label in FASTA/FASTQ files was requested for the vsearch plugin for qiime2. The option could be called relabel_self.

See https://github.com/qiime2/q2-vsearch/issues/55 for details.

**Comment by torognes** [comment]
I have some questions about some details.

1. Should we use `--relabel_self` as the option name or is `--relabel_seq` perhaps better?
2. Should we use the sequence exactly is it is or should it be normalized in some way, e.g upper-cased?
3. Should ambiguous nucleotide symbols (UIPAC) be allowed?
4. Should U be converted to T (as we do before computing MD5 or SHA1)?

@colinbrislawn, what is your opinion?

**Comment by colinbrislawn** [comment]
Great questions!
> what is your opinion?

I think the primary use of this command is to make vsearch directly compatible with other programs, like dada2 and deblur. Let's see how the dada2 dev answered these questions! @benjjneb

**Comment by torognes** [comment]
Added in commit 11a074e8863c87b514f9783708fdedcc868d2841.

I have used `relabel_self` as the option name. The sequence is used "as is" for the label, without any conversion. The option is available in all commands that write FASTA or FASTQ files.

**Comment by benjjneb** [comment]
Just caught this thread.

We typically don't write out fastq/a files with the sequences itself as the ID line, but it can be a useful format when importing to some other software that like to use the ID line as the sequence identifier. So, I'd probably just do the easiest thing and use the sequence "as is", as @torognes already did.

**Comment by torognes** [comment]
Added in version [2.14.0](https://github.com/torognes/vsearch/releases/tag/v2.14.0) just released.
