### ISSUE TITLE
chimera removal without map.pl

### ISSUE THREAD

**Issue by fezoz** [torognes/vsearch#386]
Hi, I was wondering if there is a way of removing chimeras without the need for the map.pl command? can it be done directly using vsearch ?

thank you!

**Comment by colinbrislawn** [comment]
Sure!

If you run just `vsearch` in your terminal, it will show you example commands you can run. Including these two commands for chimera removal.

```bash
vsearch --uchime_denovo FILENAME --nonchimeras FILENAME
vsearch --uchime_ref FILENAME --db FILENAME --nonchimeras FILENAME
```

These perform _de novo_ and reference-based chimera removal on a set of OTUs/ASVs/reads using the uchime algorithm.

You can see a great example of this in the [vsearch pipeline](https://github.com/torognes/vsearch/wiki/VSEARCH-pipeline).

Let me know if this helps!
Colin

**Comment by fezoz** [comment]
Thanks Colin! I think I didn't explain myself correctly. in the vsearch pipeline example, right after the step using --unchime_denovo and --uchime_ref there is the step where we extract the non chimeras from the original file using the map.pl script. I was wondering if there is a command in vsearch that can do this, instead of the map.pl script

**Comment by colinbrislawn** [comment]
Hello @fezoz,

Oh, I should have read your question more carefully. I should have recognized that you are running the vsearch pipeline already and were asking about part of the process.

>I was wondering if there is a command in vsearch that can do this, instead of the map.pl script

Not directly, but there is something similar you could do with --usearch_global or --search_exact... but I think map.pl was built because it was more efficient. I'll let the developer make a recommendation about their suggested pipeline.

Sorry if I caused any confusion!

**Comment by torognes** [comment]
Hi @fezoz,

There is unfortunately no command in vsearch to do what the `map.pl` script does.

It is possible to avoid the use of the `map.pl` script, but then you need to rewrite the pipeline substantially.

After dereplication across samples, you could cluster directly at 97% and then perform chimera removal (both de novo and reference). Finally, you could perform a search with all the dereplicated sequences against the OTU sequences to build an OTU table. That is perhaps a more traditional approach. I'll try to show an example pipeline with this approach.

**Comment by fezoz** [comment]
that would be very helpful! because I am getting very different OTU tables through directly from --cluster_size than from --usearch_global pathways

**Comment by torognes** [comment]
Hi @fezoz,

I have now added an example pipeline that does not use the `map.pl` script to the Wiki:

https://github.com/torognes/vsearch/wiki/Alternative-VSEARCH-pipeline

It's a more traditional pipeline that seems to work well. I have included some lines that shows how to use Swarm for clustering as well, but it does not use it by default.

Hope this helps you.
