### ISSUE TITLE
vsearch --search

### ISSUE THREAD

**Issue by slambrechts** [torognes/vsearch#392]
Hi,

I was wondering if `vsearch --search` is the equivalent of `usearch -otutab`?

I have 2 files which were generated using Usearch: a redundant `merged.fasta` file, and a fasta file containing OTU representatives. I would like to use these to generate an OTU table with Vsearch (using vsearch --search with the --otutabout option). Am I doing this the right way or should I also cluster my OTUs using Vsearch instead of Usearch?

Best,

Sam

**Comment by torognes** [comment]
Hi

There is no `--search` command in vsearch, but it vsearch will interpret this as the command `--search_exact` (because command and option names may be shortened as long as they are not ambiguous). However, the `--search_exact` command is not equivalent to `usearch -otutab`.

You may use something similar to the following to map the sequences to the OTUs and generate an OTU table:

```
vsearch --usearch_global merged.fasta --db otus.fasta --id 0.9 --otutabout otutab.txt
```

I hope this will work for you.

Torbjørn

**Comment by slambrechts** [comment]
Hi,

Thank you for your answer. `vsearch --usearch_global` is indeed what I was looking for. However, it appears the sequence headers in my merged.fasta are not compatible with `vsearch --usearch_global`. OTU identifiers are represented fine in the otutab.txt, but sample identifiers are not. I did not experience this problem in usearch before (not with usearch_global, nor with usearch -otutab). My sequence headers look like this:

`>M00941:843:GW19111440:1:1101:12617:4130 1:N:0:GCGTAGTA+TATCCTCT;barcodelabel=YO_4B_19;`

I'm guessing this will not be an easy fix, and I might have to go back to the original fasta files, redo the labeling and start anew?

Best,

Sam

**Comment by torognes** [comment]
It may be enough if you specify the `--notrunclabels` option. By default it will only read the initial part of the header before the first space, but with this option it will read the whole header and probably find `barcodelabel=YO_4B_19` and use it as to label the sample.

**Comment by slambrechts** [comment]
Yes idd, specifying the --notrunclabels option seems to do the trick. Thanks!

**Comment by torognes** [comment]
Good!
