### ISSUE TITLE
OTU table truncated at OTU_999999 out of ca 5,800,000 OTUs

### ISSUE THREAD

**Issue by dannyionescu** [torognes/vsearch#394]
Hi

I am analyzing a deep sequencing eDNA project with ca 6 million OTUs. The OTU table mapping the OTUs back to their samples was truncated at 999,999. Can you suggest a solution to this instead of splitting the OTUs fasta file into smaller batches?

Thanks

**Comment by torognes** [comment]
Hi

Thanks for your feedback.

I do not think there is a limit of 999,999 OTUs in the OTU tables generated by vsearch, at least there shouldn't be. I'll try to find out what is causing this problem and resolve it.

Could you describe the context of how you are using vsearch to generate this table? Is it within an established pipeline (e.g. QIIME, mothur, etc)?

What is the exact vsearch command line you are using? Is it a search (`usearch_global`, `search_exact`) or clustering command (`cluster_size`, `cluster_fast`, `cluster_smallmem`, `cluster_unoise`)?

- Torbjørn

**Comment by dannyionescu** [comment]
Good morning



Thanks for getting back to me.



The command I used is:



vsearch --cluster_size all.nonchimeras.fasta \
    --threads 20 \
    --id 0.97 \
    --strand plus \
    --sizein \
    --sizeout \
    --fasta_width 0 \
    --uc all.clustered.uc \
    --relabel OTU_ \
    --centroids all.otus.fasta \
    --otutabout all.otutab.txt



I took it from an online pipeline example I found on line.



The file all.otus.fasta has 5,838,822 OTUs.



Thanks



Best wishes



Danny











Dr. Danny Ionescu
Leibniz Institute for Freshwater Ecology and Inland Fisheries,
IGB, Dep 3, Experimental Limnology
Alte Fischerhütte 2
OT Neuglobsow
16775 Stechlin
+49 (0)33082 699 69
ionescu@igb-berlin.de








http://www.igb-berlin.de/en/profile/danny-ionescu



SAME 16 Meeting for Aquatic Microbial Ecology, 1st-6th of September 2019 in Potsdam

https://same16.org/








-----Original message-----

**Comment by dannyionescu** [comment]
Hello again

I just realized that the OTU table is complete but not sorted according to OTU number.



Sorry for the comnfussion.



Thanks



Danny











Dr. Danny Ionescu
Leibniz Institute for Freshwater Ecology and Inland Fisheries,
IGB, Dep 3, Experimental Limnology
Alte Fischerhütte 2
OT Neuglobsow
16775 Stechlin
+49 (0)33082 699 69
ionescu@igb-berlin.de








http://www.igb-berlin.de/en/profile/danny-ionescu



SAME 16 Meeting for Aquatic Microbial Ecology, 1st-6th of September 2019 in Potsdam

https://same16.org/








-----Original message-----

**Comment by torognes** [comment]
Ok, I am glad you solved the problem.
