### ISSUE TITLE
Missing minseqlength option to makeudb_usearch command

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#395]
A user have reported that the `minseqlength` option is not allowed with the `makeudb_usearch` command. It is therefore impossible to include sequences shorter than 32 bp in an udb file.

The bug has been confirmed.

**Comment by torognes** [comment]
Fixed in commit ad40392ea599aa0f10e05885bba19cb1a99350e7.

**Comment by enormandeau** [comment]
Will it be possible to create a release with that fix? My pipeline will require it and it will be easier for other people to use it. Thanks!

**Comment by enormandeau** [comment]
On another note, it may be worth checking that all the other commands that should accept it do. I think I had the chimera removal crash by passing it `--minseqlength`. It may or may not be the desired behaviour.

**Comment by torognes** [comment]
> Will it be possible to create a release with that fix? My pipeline will require it and it will be easier for other people to use it. Thanks!

Yes, I'm creating the release right now.

**Comment by torognes** [comment]
> On another note, it may be worth checking that all the other commands that should accept it do. I think I had the chimera removal crash by passing it `--minseqlength`. It may or may not be the desired behaviour.

The chimera detection commands (`uchime_ref`, `uchime_denovo`) do not accept the `minseqlength` option, but they do not ignore short sequences (even shorter than 32 bp). If short sequences should be ignored, it is possible to do it using the `fastx_filter` command. I'll have a look at the other commands and see if the `minseqlength` option has been disabled for them without reason.

**Comment by torognes** [comment]
The changes are now released in [VSEARCH version 2.14.2](https://github.com/torognes/vsearch/releases/tag/v2.14.2).

**Comment by enormandeau** [comment]
Thank you!

**Comment by torognes** [comment]
I hope it works as it should for you now. Please reopen issue if does not.
