### ISSUE TITLE
vsearch error

### ISSUE THREAD

**Issue by liucong2016** [torognes/vsearch#396]
when I use vsearch for amplicon sequencing data analysis, I have installes vsearch

when I use it, something wrong happended:

`ubuntu@ip-172-31-14-112:~/LC$ time vsearch ‐‐usearch_global seq18s-A-usearch.fa ‐‐db 18s-A-otus-nochimtabout 18s-A-otu‐table.txt ‐‐threads 8`

time vsearch ‐‐usearch_global: command not found

I have no idea with it. I need help.

**Comment by torognes** [comment]
Hi! It seems like this is a problem with the shell, not vsearch.

Could you try the command line without `time` in the beginning? Please make sure that the spaces and dashes on the command line are proper spaces and dashes as well. If you have copied them from somewhere, try to type them in directly.

Additionally, unrelated to this problem, you also need some option (perhaps `--otutabout`?) before the file name `18s-A-otu‐table.txt`. You also need to specify the `--id` option and an argument.

**Comment by mys721tx** [comment]
Most of time `time` is a shell built-in command and should not change anything. What is your output for `which vsearch`? If vsearch is not in your path, you must specify it manually like this.

```ShellSession
/path/to/vsearch ‐‐usearch_global seq18s-A-usearch.fa ‐‐db 18s-A-otus-nochimtabout 18s-A-otu‐table.txt ‐‐threads 8 
```

**Comment by liucong2016** [comment]
> Hi! It seems like this is a problem with the shell, not vsearch.
> 
> Could you try the command line without `time` in the beginning? Please make sure that the spaces and dashes on the command line are proper spaces and dashes as well. If you have copied them from somewhere, try to type them in directly.
> 
> Additionally, unrelated to this problem, you also need some option (perhaps `--otutabout`?) before the file name `18s-A-otu‐table.txt`. You also need to specify the `--id` option and an argument.

I try to type them in directly, and it works!! thank you very much!!

**Comment by torognes** [comment]
I am happy to hear that your problem was resolved.

**Comment by frederic-mahe** [comment]
This is a copy-paste issue from a source that is not ascii. The dashes `‐` in the original post are not the 45th ascii symbol `-`, but three-byte long utf-8 characters that look like the ascii dash. The shell does not know what to do with these characters, hence the error message.
