### ISSUE TITLE
Bad alignments across gaps in the seed sequence

### ISSUE THREAD

**Issue by scharch** [torognes/vsearch#399]
Please see attached input and output: the problem is columns 15-61 of the alignment and results in an incorrect consensus sequence. If I use `cluster_size` or `cluster_smallmem --usersort` to cluster with a different seed sequence, the alignment and consensus are correct.

`~/Downloads/vsearch-2.14.2-linux-x86_64/bin/vsearch -cluster_fast test.fa -msaout msa.fa -id .7 -sizein -sizeout -clusterout_sort`

[test.fa.txt](https://github.com/torognes/vsearch/files/4262611/test.fa.txt)
[msa.fa.txt](https://github.com/torognes/vsearch/files/4262613/msa.fa.txt)

**Comment by frederic-mahe** [comment]
The difference you observe comes from the fact that `vsearch` does not compute a _complete multiple sequence alignment_ (each sequence is aligned to all other sequences), but computes a _center star multiple sequence alignment_ (each sequence is aligned to the cluster seed). Center star alignment is a fast method, but its accuracy can decrease significantly when using low pairwise identity thresholds (or gappy sequences).

Here is a toy-example where the seed has a deletion, like in your test file:

```sh
printf ">s1;size=6;\nGGAA\n>s2;size=5;\nGGCCAA\n>s3;size=2;\nGGCAA\n" | \
    vsearch \
        --cluster_size - \
        --minseqlength 1 \
        --id 0.5 \
        --qmask none \
        --sizein \
        --fasta_width 0 \
        --sizeout \
        --quiet \
        --clusterout_sort \
        --msaout - \
```

It outputs the following alignment and consensus:
```
s1 --GGAA
s2 GGCCAA
s3 G-GCAA
   ++GCAA
```

An alignment with `muscle` would return:
```
s1 GG--AA
s2 GGCCAA
s3 GGC-AA
   GGC-AA
```

If we change the sequence order (seed is now the longest sequence):
```sh
printf ">s1;size=6;\nGGCCAA\n>s2;size=5;\nGGAA\n>s3;size=2;\nGGCAA\n" | \
    vsearch \
        --cluster_size - \
        --minseqlength 1 \
        --id 0.5 \
        --qmask none \
        --sizein \
        --fasta_width 0 \
        --sizeout \
        --quiet \
        --clusterout_sort \
        --msaout - \
```
then, center star alignment and complete alignment produce the same consensus sequence (GGCAA):
```
s1 GGCCAA
s2 --GGAA
s3 -GGCAA
   -GGCAA
```
