### ISSUE TITLE
Automatic regression testing

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#40]

**Comment by frederic-mahe** [comment]
Most options accepting range of values now test for the validity of the value entered by the user. I should create scripts testing that, with the objective to confirm correct behavior and to find options that are not sanitized yet.

**Comment by frederic-mahe** [comment]
**UPDATE** At the end of summer 2017, we had more than 1,500 unit tests for vsearch. Sadly, those tests cover only a fraction of vsearch's functionalities. I will have to prioritize covering some important functions first, for example `--fastq_mergepairs`.

**Comment by frederic-mahe** [comment]
The test-suite is usable again for continuous integration. Coverage is low, but that's a start.
