### ISSUE TITLE
Extracting the sequences reads

### ISSUE THREAD

**Issue by AhmadAlharbi7** [torognes/vsearch#401]
I got the Vsearch output file  with only reads I.D. clustering to each type in cloumns. Could you please advise me how can I extract the sequence reads  clustered to each type. As I need to do further steps on the clustered sequences.

Kind regrads

ahmad.alharbi@postgrad.manchester.ac.uk

**Comment by torognes** [comment]
Hi! There might be an option to write the needed sequences to a separate file, but I need some more specific information on what you are doing. Could you please show the full command line that you used?

**Comment by AhmadAlharbi7** [comment]
okay.  gB is the name of the gene region which has 4 different types.

# gB length
MAX_LENGTH = "373"
MIN_LENGTH = "275"

<path-to-vsearch>/vsearch --fastx_filter output.fasta --fastq_maxlen $MAX_LENGTH --fastq_minlen $MIN_LENGTH --fastaout output_trimmed.fasta

<path-to-vsearch>/vsearch --usearch_global output_trimmed.fasta --db gB_regions.fa  --strand both --id 0.85 --top_hits_only --otutabout gB_seqout.txt -threads 1

**Comment by AhmadAlharbi7** [comment]
See the output file I got


I#OTU ID	01b7cafb_b91f_4968_b8e9_df3b0d0f8102	02ab377f_db76_478d_a287_6160969f9c71	0332f8bb_b061_4b1c_afe1_b5063ec4f362	0418cd1c_e915_47ca_9987_94f5c44302dc	042f703d_89a9_4553_9eea_af602add351d	052b483a_69a0_41f5_b186_90582f1f0d21	06f10abe_f494_4a7d_b4f2_7c33304501a8	0935ad16_4f5d_48e2_b37d_420969e36674	0a73fc23_8668_45af_9fb8_eb34f5e53875	0c19fa74_4469_407f_8097_4b2bb61e2274	0c6f3631_6324_4831_93d5_8b21d0480aa7	0f0c87b8_4ed3_4393_af28_e283289e3ef6	0f1f6b5f_bcc2_4126_ac63_bcd567a17c65	1034d783_fcf8_461d_a15f_54ea37757903	107a0a88_290a_4e76_a503_826ec5e932d5	127a0d65_e5f4_4e6b_ba96_315c0059fa0b	146cb412_b47f_459e_89e4_ec82d97848a8	14e31bd3_6085_45e1_b767_8deeff618a9d	15cb86ca_ddcc_49ae_bbbd_38fb7ed40932	15dd10f7_e9d3_4d91_adc8_57909740aff4	17151dd3_8ee9_4c79_a390_f28f53f14112	173ddc75_99c6_4a5b_879e_cb45d3750d41	178914c5_9efa_4500_96f2_43910b1fc8ca	18117854_4306_4261_a7bd_8ea7fd8a58b4	182a37aa_b278_4de8_8992_5005399db481	19845eb6_c36a_45fb_b2c3_0b42473f9da0	19cc2120_29ff_47b3_a5de_993ca74cb5e0	19d80759_b94d_4e69_83f2_53ae30a305fa	19dc6bac_da8c_4380_8622_db47ab5bde8a	1d39d372_4187_4aa4_bc84_fe43560acab0	1e8f4dec_8622_4311_b22c_86765d51cf28	1fcbfa03_69aa_46bd_bc21_bce6df5d01b0	20ab6cf8_51b5_4f91_8e32_574be121998d	21341685_4520_49d3_b4b9_38d24c127057	216c9d13_cb4e_40a9_bd2f_5d69bfef8113	223f8cb6_ff82_4c69_aa85_1c7f18c58420	2466d3ab_b786_4d9f_be0c_a41661942b05	251538a7_5854_4212_aaff_40660b10405e	25f7ebb5_45b1_4b29_9161_6c14023cb9d0	262bc009_1dc2_4678_b835_b26d3be95419	27a33343_be04_426c_afa8_c8bafcc8a55f	2908cbcb_a154_4c54_9a78_d6cd80a574cf	29c97567_8eac_4075_a518_f872a085a37e	2a161ffa_1ceb_425c_a801_14c1b10da49b	2b41304f_3972_45ac_8723_2738fcd61fd2	2bea9222_a64c_4053_adae_5183aa1d66d5	2d921108_20cc_476d_8676_9138ec3865b1	2dd1c17e_024f_47a9_9b76_a67f3366f717	2de11b3e_3c9b_479d_ae0a_2a9be5299571	2e96262c_2920_4cfa_9c53_f5a14d915033	3198d114_ec3b_452d_a50c_44f4a0c50385	31f7db9e_320e_454f_ac4f_afd9d941ad00	33c53f7c_cf61_4592_8e0f_16c741f48dad	33ed325e_1c39_4bb7_abb6_e5cc7ef21df2	3412e368_acaa_456b_88aa_53732566a7bb	348d059a_50ba_487a_9268_e3809b161abe	34a78954_1b01_41ab_bfd9_55a5d6bdf5f4	3709b0d7_f6c7_4163_8bb3_dbbbff5ab08a	37e34992_d190_49ba_8d30_679817204851	38034da5_a5e8_4364_85a4_77e848cb097a	39886267_c0fe_42dd_9106_e63efc594556	3a433b64_f1a6_4182_bbeb_bef31401a33e	3a6727f1_b643_4097_943a_0f0f14f87d80	3b97b141_f8f7_43d5_a251_dd59b6f06a3c	3bc1c7b0_cf08_47e6_9c0d_f07185ca8eb6	3c350d30_0e54_479f_b124_92c67c2202f0	3cd43b9e_3ef9_4fd0_9009_37f81a90930c	3d51b155_6a61_4b28_9973_beee5afbee2b	3db54c18_dd3b_42a2_8823_7da8a42cfe57	3eaacb2c_d86b_446f_a690_1aafb86524a9	4052f19b_4cec_4c70_be7e_6b15706762a7	40d0a168_3b74_4e02_9393_50bfc5eaf544	4174a17d_16af_4d7b_abc1_22606c2e939a	41873724_85c1_4ab7_89ed_166166a4af23	424232d7_1786_4610_becc_1a76db442f77	44be52bf_87fb_471f_b5c2_57f0babae1ee	45060079_b447_4f03_a060_fff6737a0dc5	450c75b4_db55_4891_a266_9fab0ba8c8f1	4640d3f9_cf51_42b0_937f_822b318f56cf	48552bce_eeeb_4ac3_b9d4_fafde55ab11b	487b8d17_dd48_4c50_9d17_b87ab88dfb76	496cb972_c27a_4600_a381_69e2981740b2	4a8bd33b_6c5e_4ea8_8e11_c7c2b89af6ba	4aa82c0a_beb9_4f0a_b311_c4685d57035a	4affcece_5083_42ba_80e9_a05286d537fd	4b43bc3d_efd7_43f8_9c0c_f8209b5b436c	4b65b10c_cf8b_48b4_ace8_67d7af41558e	4bb0f5a4_7fa7_4eaf_ba12_37bac77fdd74	4bd6d903_06f3_4186_b1c0_55a85550215e	4c13d21f_a828_42db_b6dc_a67e921ef3fa	4e6f068f_cd90_46c9_bedf_62523b1a6d8e	4f1d7f74_a285_4aee_8d4c_6d727321f4ed	50e34ddf_ff92_4465_b613_35edb03a21a7	517de4ab_ccf1_4278_a1fa_2837b553a39b	52527ce3_1148_4ef7_b823_aaf32f11f0c3	525df7a9_981f_4a3a_aa35_28afc400298f	53151d6c_8e3b_4fe1_90e9_a5dd5eb884de	531d455e_c301_48b5_b955_54e15db2ed95	539dee96_2087_4c00_b1ef_2b0d8382497b	53b03dc8_304e_4d3f_8c00_4101c9a0c1a4	5527a623_fd64_47be_af6e_793442a51481	55500eca_13d0_4ddb_ad44_77d7d163ba1c	55f70d53_8ff8_49b2_a2a5_4694d5b88b08	5615cdfd_de65_4f7d_b2a2_f83c6525959c	5841d00e_6338_4abe_8362_552f4a429b29	5988ed7e_d47d_4ca4_891e_b53e99ad2cc2	5a1e5486_cd2a_4a8b_87e4_5427084bb1d0	5a8b7219_a76f_4ed9_b2c8_2f186ff21bfd	5b749395_605d_4264_acd6_9cb7281cedcf	5e6cf263_36c6_4709_8beb_9c78fc89fd72	5fbaa11a_c372_4c60_a682_dd3d00997a22	61f9790a_9663_42de_90ec_c8e004be766b	61fb1ce6_0f8d_4e8b_8298_53ae5636a13e	63761d83_9df2_49ae_a1dc_cd375e5b0f7e	63c11329_8fbd_4479_84f7_bf6a67d6475c	63dd8c52_298d_4e2a_9113_dac94b4b8a4b	63ee5419_695e_42b6_a397_49999135e295	643a92af_5681_49c2_9a71_b3f3f66c8c88	665df29f_3ac2_42a9_ac95_50767750b45a	67c58d8a_7cee_4983_ae8e_276c0c7cea88	68053dc3_26f0_416a_a9cc_d02a427f1006	685def3a_0b8d_407f_b683_c5992e2bc5cc	68ad3714_ca01_4179_9b03_260232517752	6a3d67f7_8b20_48d6_91c4_7498ab493d55	6c74c76b_f382_4190_8cc3_85772d9c1b99	6e5ba3d2_711b_416f_ac3e_5ed3187f60f7	6eb2b682_b3f4_4f18_8f67_758f0ea917e7	6f5a0a19_9e4d_4a42_9b21_23c4a621e13a	6f8f5372_689d_4fda_a9e2_9f5dc8e1e997	71725d4c_bd4e_4229_b399_6d73b9c658a1	719f3cc9_e6a0_4c1e_8ab1_27df02a03f9a	732c41f3_a8d1_4131_b6cd_6ea551c063d1	7367784a_b516_459b_b59b_6d58717fc7e5	73a1aab5_1bd9_4e23_a78d_21cf5673e203	73e77d70_285e_47b7_bebd_ebe5f5ed798f	740b86f6_7a9d_46e0_803c_5f16d15659a3	7440300d_fae8_4c4d_bc5a_d34355eca31b	74a037a1_6e08_44fe_9cce_367cadfb39a1	75aa2853_f3b0_4aa7_84a2_c92705f70d40	764261a7_0674_4e17_8278_386ed06acb99	7a6a6796_b3e5_437d_ae65_ad1e1a9ce0b3	7aeb3fec_417e_40b1_b70c_6ca57e210b95	7b337a98_be49_469b_9fd6_67d5eab303c3	7bffe28a_56dd_4c2e_9293_c3fa59942d1e	7c5eca76_a652_4bdd_81d0_44b0256f38a5	7e99323f_c6fc_4dcc_b00d_3f6000dad1a6	7ed880ce_bc6b_4394_a27e_17711332e773	81118910_f810_4769_bc1d_f9e6d8bed98e	8207af0e_81b5_42cc_bbe1_2a97caf8e8dd	83b5ffc3_6811_418f_aade_0f1d2f567e4e	85f04274_a841_452d_be4a_b5d8b544e1e9	86addc6e_74b4_459c_a8a4_1b02314eb50c	87a1bd89_b0bc_4577_be36_4669dad73274	8aa919a8_9205_4fc3_9d54_5d9402c5b8f1	8c04bc9a_9518_4570_9295_1c241f42f210	8d96f4d8_c73a_43fb_8687_912a42eb7f7b	8e649004_ddab_4ce0_90c0_af6a54ef2610	8fccbe07_6150_4d86_9bbc_d78eeeef6046	90fdb0ce_03f9_4f7c_83eb_6dc0366f8ef6	928e6484_9459_4714_a3f2_f4e4405933c8	92c91088_0e4f_4c8f_adfa_edd1d1086d00	92d9511e_6dd6_4a0c_aa5f_5d3af963f76f	940735ed_7135_415a_ab12_1267dfec4c98	94afb9aa_aadb_430e_85b4_839c2989fa29	96e23dd7_0000_486e_a686_208b38a641be	97fd7a2c_19c8_4e07_a9c6_e994d941f05f	99461c2c_58b5_4a4c_ae83_b8b0c01e72c1	9981ca5a_58a3_4e83_9c6f_f548a8ab130a	9b5fe002_dcf4_4ffd_8d18_4ce12216c07e	9bd517f1_e128_438f_b1a0_4ac49a24434c	9c31fc70_0e9e_48ca_9f41_28fabd95875e	9c510a65_c34c_4c98_a880_1b7d006b091b	9d7dd0c0_184a_4d62_90f2_a03221cc0c86	9e294185_f182_4d1b_8a3c_b4a67fa4dad9	9ebb0739_1080_497c_9b8c_a41965394d15	9f2ffd75_5ca2_4a2e_bd65_d951439eed00	a04ce499_2d78_4ae5_bdc7_9c9c5d51caa8	a370abb5_4ffd_4516_ad01_2ac5beb8af03	a39e502d_eee9_4fb9_b905_a39f305b782e	a4681bf9_8666_4bf1_85d2_09c307188004	a7423da4_5958_455a_a2ef_f4e9bf3cdb33	a7c0730f_544e_4aa7_9a1a_1850ae248e08	aa0449bc_dd89_4053_be4c_3a4c5a6fa6ea	aaed3003_c9a0_4df7_8dbb_e83677bf80ca	ae216d53_7dbc_4b23_8fee_dbd21ce5e707	aea63d16_f90b_4b87_8da6_4fc0ba937067	aef22465_368e_4d65_a167_3e34500e1a39	b0171f73_7f11_4420_8dfa_73050285289a	b0e3cc3e_cf77_4454_9e7f_50a7998abe1b	b2246f95_fd7b_49fd_aab8_742e3938ac54	b232f5a5_3ed8_4ae3_92b3_d797507a3946	b6d40617_12b8_4b20_889e_07ed641df0ad	b6d49df3_1734_4699_afe9_89730dfe0c4c	b77e4f29_fbdb_4cfc_82ae_f424032f6298	b7acaa29_c182_49fb_b72c_39166ec2ed35	b8e79d66_1926_4350_8c63_642ad58ce6f9	b9d1aa3d_2d46_4466_9cf1_bf36e4fde9b6	ba9b4a0c_96cc_478a_aca4_5f6e59429f58	bb0e353f_c612_4712_8dcb_ed7059a42662	bb74d87c_8b3e_4e46_a95a_ef45b2667038	bbda88a0_6c05_42e9_8a8d_6f7015299418	bc2fb8c5_6c90_4b9e_a8d5_76b4e9687b98	bce69cb1_7d9f_403b_b874_356170fffdfb	bd5db652_06b8_4b42_a213_6dbf3936db92	be5fe86c_52ca_4aae_9eeb_69cc80f1a1b9	be996616_7d4e_4be4_a92e_24f9ea10f271	bf07a6aa_4a5c_4fe0_9df7_5096a421c482	c080b469_39ad_41cc_ad02_7dc06fbfe37f	c0ad08e7_98aa_40d2_a500_4fb05199d537	c186e82b_3442_4642_afa4_ff1e023c03ff	c2035794_b7f8_4884_ac67_1fa92cb0c20a	c2d13158_5f01_42ca_9abb_f59216ea063e	c3ba0d47_bcc5_4041_ac3e_10d4224d698d	c4a483ff_aedf_4a79_8a83_062732353627	c60b26fa_a40e_4196_9011_bf7e197ddc18	c65e3453_2b93_4aa6_952e_ea7f004a57e8	c66bed4e_650e_4536_8024_14bacb6265f1	c73def14_e55f_46c6_9218_840ed9958b9c	c8e72cb1_8915_4b65_82e8_9f8b33291c81	c9a7eeb7_8f8a_469b_afb8_0834419baac4	caa68181_26b1_4904_81cb_1b5efb7f565f	cb2e64ab_710b_44ae_bae9_138448679119	cbd21165_52b9_430f_88c8_75a8e2a3eda5	cd58fe1d_11e2_49e1_9fb3_b9e7bacc607c	ce991566_4a1b_4873_93cd_2a6834428e89	d1208c97_a60c_4eb7_a1c9_df8b9f508fb2	d1ddd9f9_c70e_4b31_8063_6435b6f687a2	d256f46b_f9d4_40b8_b57b_92908d38beea	d4bc2cc9_efc2_415a_9aec_477623c4c6b6	d5119d1c_fa99_41f3_9a16_e3af143ed892	d583df33_5e4f_4231_8ffd_1ec95f9b4fc6	d5e4b650_3d50_4218_b45d_5f7318ea0ec5	d5ffddf3_c3f2_456e_8fb2_2258572f77a0	d7a64dd6_db01_4024_8aba_1f5cb02f3999	d80424f6_f5a1_4c8b_b19d_2f7253c89ebe	d8a2ea0a_bbaf_498c_a774_2db3f397e92e	dac711f7_f602_4586_8335_84ae1a709780	dc97a84a_79ad_4fca_ac39_d550f72ce983	e011a250_350d_4985_b44a_0fca6d7fc7f7	e1e8dfbc_f58e_4dde_bc55_160959a1c23b	e222e1da_2552_4da3_bb2f_db08c0717d66	e45588be_9e14_487d_9243_41df56a72dfa	e4767e0b_c351_4d1a_afbf_85c87742046a	e49be0ea_268b_4249_9e3d_487f85fcc37e	e55923a2_6f0b_49f6_9a6f_145a3fe2e398	e5c13bad_edc7_496e_a2ab_3c9dbe37aae3	e5cf3888_ad4a_462a_a530_bc73a051985a	e6512375_c894_4c44_87b3_18b89003f213	e7667315_87c0_42bc_aab1_6f3ae3cdb2ad	e7a42c9a_9c95_4740_b54b_125fa5a8ba1d	e880d482_3eb4_413e_a1c1_b38d1584bbbf	e8f29c60_7ea5_4d8c_92a0_a1273db33b86	e9bc7359_4797_4173_b2e2_351216e4e7fd	ea0f2b1c_3968_4433_bbf5_4ba00ac65f81	ea8c9b6e_78db_4f95_bdd5_46cfddb1e1e6	eaa2e907_95d0_4c81_b5dd_b5f576b8263b	ebe0ab1f_2e45_4d72_baf3_73a7075842b5	ec0eb4ab_ff8b_43d6_a138_714d2eb1ded6	ed63d3e2_d057_4d1a_b7bf_8f5df8755cda	eddd2bf4_d7a7_4c52_94f7_01a588e2c2dc	ee83ec15_86f3_47a8_8e69_bbc80b51fbd8	eea04506_cf68_44c9_988a_67220e3f0fdc	efbd9fff_440d_444d_a053_9c2b9c3c5a38	efcd23e0_019e_4929_89a9_a75d131d0a60	efd268d2_ed43_4207_ab5d_53ebbaa76c04	f0a29452_ce39_4e9d_8013_2ca5d59a4175	f0a2a842_feb3_48da_a132_63e1dee5febd	f0ebeb61_d1bd_4eb6_b7c8_3e018f80eb6e	f1341f8a_3f47_463e_bb55_f42afebafef8	f2f236e7_6af7_4db1_adb1_015789326b1a	f3e01788_77e8_4bf3_8413_9541480337cd	f401f17c_ae65_4142_93bd_75598005e850	f4f1b070_3f87_44ac_8197_b44bb7464c20	f51c5ad4_f40b_4d01_882c_86b3a7945b34	f6c44d61_4e96_4888_b3a4_e4ce94c06f75	f7ced821_ef18_4cba_9e62_73f5aced34d0	f8880fa0_9790_4e41_8651_e63d0f090ba7	f8b8dd32_716e_472f_9a58_9c4afd517fbd	f964db8f_a547_4fc5_b57b_524dadc32007	fcc73e52_694a_4166_9843_7d402fe5ded6	fcfe3f40_565a_4e47_951b_476dbf536680	feb9424c_eecc_4bd4_9a96_20ac9d513160
gB-1	0	0	0	0	0	0	0	1	1	0	1	0	0	1	1	0	2	0	0	0	0	1	0	1	1	0	1	0	0	0	2	0	0	0	0	0	0	0	0	0	0	0	1	1	0	0	0	0	2	1	1	0	0	2	0	0	2	0	1	0	0	0	0	0	0	1	0	0	0	0	0	0	1	0	0	0	2	0	1	0	0	1	0	0	0	2	0	1	1	0	0	0	0	0	1	1	0	0	1	0	0	0	2	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	1	0	0	0	0	1	2	0	0	0	0	0	1	1	0	0	0	0	0	0	1	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	0	0	0	0	1	2	2	0	0	1	1	0	0	0	0	1	0	0	2	0	1	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	2	0	0	0	0	0	1	0	0	0	0	1	0	2	0	0	0	0	0	1	0	1	1	0	0	0	2	0	1	0	0	1	1	0	0	1	0	1	1	0	0	0	1	0	0	0	1	0	0	0	0	0	1	0	2	0	0	0	0	0	0	0	2	1	0	0	0	0	0	0	0	0	0	0	2	0
gB-2	1	1	1	1	1	1	1	0	0	2	0	2	2	0	0	1	0	2	1	1	2	0	1	0	0	1	0	1	2	1	0	1	1	2	1	1	1	2	1	1	1	2	0	0	1	1	1	1	0	0	0	1	1	0	2	1	0	1	0	1	1	1	1	2	2	0	1	1	1	1	1	1	0	1	2	1	0	1	0	1	1	0	1	2	1	0	1	0	0	1	1	2	1	1	0	0	2	1	0	1	1	1	0	1	1	1	1	2	2	1	1	0	1	2	1	2	1	1	1	0	1	2	2	1	0	0	2	1	1	1	2	0	0	2	1	1	1	1	1	0	1	1	1	1	1	1	0	1	1	1	1	2	1	2	1	1	1	1	1	0	0	1	1	2	1	1	0	0	0	1	1	0	0	1	1	1	2	0	1	1	0	1	0	1	2	1	2	1	0	1	1	1	1	2	0	2	1	1	2	2	1	2	1	2	0	1	0	2	1	1	2	1	0	2	1	1	1	0	1	0	1	1	1	1	1	0	1	0	0	2	1	1	0	1	0	2	1	0	0	1	1	0	1	0	0	1	1	2	0	1	1	1	0	1	1	1	1	1	0	2	0	1	1	1	2	1	1	1	0	0	1	1	1	1	1	1	1	1	2	1	0	1
gB-3	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0

**Comment by AhmadAlharbi7** [comment]
I got it without sequences just with the reads I.D. I want the sequences aligned to gB-1 in a separate file and those to gB-2 in a separate file

**Comment by torognes** [comment]
Sorry for the very late reply.

I do not think there is a way in vsearch to write the sequences matching to the different database sequences into different output files.

You may need to process each gB-sequence separately with a script.

Perhaps you could use the `--matched` or `--dbmatched` options of vsearch to write the query or database sequences that are matching to a separate file.

Alternatively, you may use the `--userout` and `--userfield` options to extract just the target and query identifiers. You could then select the matching query identifiers for each gB region using e.g. `grep`. Finally you could use the `fastx_getseqs` command in vsearch to extract the sequences you need.
