### ISSUE TITLE
Vsearch crash when input have a non-ASCII character

### ISSUE THREAD

**Issue by fjossandon** [torognes/vsearch#404]
Hello,
When trying to compare sequences, Vsearch crashed because of a "**ë**" character that I didn't know that the database had. This same input worked fine when using Usearch though.

Here a working example.
test_db.fasta
```
>12345;Epichloë_amarillans
AAATTTCCCGGGAAAAAATTTCCCGGGAAAAAATTTCCCGGGAAA
```
test_seq.fasta
```
>test_seq
AAATTTCCCGGGAAAAAATTTCCCGGGAAAAAATTTCCCGGGAAA
```
command = `vsearch --usearch_global test_seq.fa --db test_db.fa --blast6out test_out.txt --id 0.7`
output:
```
vsearch v2.14.1_linux_x86_64, 15.6GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file test_db.fa 0%

Fatal error: Illegal character encountered in FASTA/FASTQ header.
Unprintable ASCII character no 195 on or right before line 2.
```
Is it possible for Vsearch to accept printable non-ASCII characters???

**Comment by frederic-mahe** [comment]
related to issue #398 

I am surprised to see a binomial taxa name with diacritics. I don't remember ever finding non-ASCII characters in genus-species names, besides the cross symbol for hybrids . For future reference, swarm silently accepts non-ASCII characters in fasta headers, but I can help to think that introducing non-ASCII in fasta/fastq files is a risky behavior.

**Comment by fjossandon** [comment]
Well, looking around it seems that the correct name for that species do have the diaeresis in it (https://en.wikipedia.org/wiki/Epichlo%C3%AB), its an old name. And now that you mention that other issue, I can see that entry too in my UNITE file, at least in the webpage the character is still there (https://unite.ut.ee/bl_forw_sh.php?sh_name=SH1644897.08FU#fndtn-panel1), I wonder if they plan to change it or not; interestingly, for that same sequence, its INSD taxon name is "Clavicipitaceae (Epichloe schardlii)", the genus I found...

Given that Swarm accepts non-ASCII characters, maybe Vsearch could accept it too?? I think there is no harm if its accepts printable non-ASCII, while still crashing if it contains non-printable ones that are way harder to detect (https://flaviocopes.com/non-printable-ascii-characters/).

**Comment by torognes** [comment]
Thanks for raising this issue. Perhaps VSEARCH should just warn about these special characters, but not stop.

**Comment by fjossandon** [comment]
> Thanks for raising this issue. Perhaps VSEARCH should just warn about these special characters, but not stop.

That sound like a fantastic idea!

**Comment by fjossandon** [comment]
Thanks @torognes!!
Also thanks for the demonstration, is interesting to see that an apparently single character will cause 2 warnings due to the 2-byte.

Are there plans to release a version 2.14.3 with these fixes soon?? =)

**Comment by torognes** [comment]
Yes, I plan to release a new version in a few days when I've completed a few more minor changes.

**Comment by torognes** [comment]
New version 2.15.0 was just released. Enjoy!

**Comment by fjossandon** [comment]
Awesome!
