### ISSUE TITLE
different OTU tables following different pipelines

### ISSUE THREAD

**Issue by fezoz** [torognes/vsearch#406]
Hi! I just finished following your pipeline to get an OTU table. did it exactly as you suggest here (https://github.com/torognes/vsearch/wiki/VSEARCH-pipeline). I got an OTU table directly from clustering.

But then, if I use that all.otus.fasta file to manually create an OTU table using:

vsearch --usearch_global all.nonchimeras.fasta --db all.otus.fasta --id 0.97 --otutabout OZ.table.cons.txt

I got an table with different values. some OTUs remained the same or very similar abundances, but others were very different.

Am I missing something? I just want to make sure I am getting an OTU table with accurate relative abundances

thank you !

**Comment by torognes** [comment]
Generally, the results you get from clustering may deviate slightly from those you get when afterwards searching directly against the OTU centroids. This has to do with the order of processing of the sequences and ambiguities when a sequence is closer than the threshold (e.g. 97% identical) to several potential centroids.
