### ISSUE TITLE
--usearch_global and sorting

### ISSUE THREAD

**Issue by hjruscheweyh** [torognes/vsearch#407]
Hi Torbjorn, Hi Fred

Is there a way/parameter to guarantee that the output from `vsearch --usearch_global` will return alignments in the same order as they were in the input fasta file? This would be useful for parsing paired-end alignment files.

Best and thanks,
Hans

**Comment by frederic-mahe** [comment]
Hi Hans, I think the only way to guarantee output order is to use `--threads 1`. Multithreading separates alignment into independent tasks, which will execute and write results at different speed. Hence, the variable output-order.

**Comment by hjruscheweyh** [comment]
Understandable. I thought that you might have implemented an output-queue that can force output in a certain order.

I will see if I can find a cheap Python or Linux workaround.

Hans
