### ISSUE TITLE
-minsize flag in -cluster_fast

### ISSUE THREAD

**Issue by lgeissler91** [torognes/vsearch#409]
Hello! 

I'm currently trying to use a wrapper script for analysis of nifH amplicon sequencing analysis called taxadiva.pl  (https://github.com/lavanyarishishwar/taxadiva).

It uses the flag '-minsize' in -cluster_fast, however when I try using it, vsearch on my machine tells me that '--minsize' is not an option for that algorithm. 
Is this due to a version difference? Whats the appropriate replacement in newer (or older?) versions.

Thanks in advance!

**Comment by torognes** [comment]
Unfortunately, there is no `minsize` option for `cluster_fast` in vsearch. It has never been. Earlier versions did not check as thoroughly for illegal options as the later ones. Previously, the option would just have been ignored. If you need to remove clusters of low abundance you need to run `sortbysize` or `fastx_filter` with `minsize` after clustering.

**Comment by lgeissler91** [comment]
Ah okay good to know. Thank you very much!
