### ISSUE TITLE
Crash on Windows with some versions of zlib1.dll when reading gzipped files

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#412]
On Windows, it seems like vsearch does not read gzipped fasta files (.fasta.gz) properly, at least not with the `cluster_fast` command. The file just appears empty.

**Comment by torognes** [comment]
It seems like the vsearch crashes on windows when gzipped files are read (either fasta or fastq) when using certain versions of the zlib1.dll library. It appears to work well with version 1.2.5, but not 1.2.3 or 1.2.11 (current).

**Comment by torognes** [comment]
It seems like the `zlib1.dll` library comes in many flavours. There are different versions, where the latest is 1.2.11. There are also some compiled with the `ZLIB_WINAPI` flag (discouraged by the author) and some not. There are also seems to be both GUI and console variants of the library. As far as I can see, vsearch will not work with the versions of the library compiled with the `ZLIB_WINAPI` flag; these are sometimes, but not always, named `zlibwapi.dll`. Futhermore, vsearch will also not work with the GUI variant of the library.

It is tempting to link vsearch statically with zlib on Windows to avoid this mess. Alternatively, we could distribute a working version of `zlib1.dll` with the vsearch binary.

**Comment by andzandz11** [comment]
Where can I find a version that has been proven to be working?

**Comment by torognes** [comment]
I have only found one working version of `zlib1.dll`. It is provided by the MinGW-w64 project and available on SourgeForge [here](https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/Binaries%20%2864-bit%29/zlib-1.2.5-bin-x64.zip). 

The `zlib-1.2.5-bin-x64.zip` archive should have a MD5 of 845552203770cadf58dfb5178890a229 and the size should be 121 486 bytes. After unzipping, you'll find the `zlib1.dll` file in the `bin` folder within `zlib`. The file size should be 90 112 bytes. The MD5 should be 0f67ee0b965d3d29388c238aebcf60bc.

It should be found automatically by vsearch if placed in the same folder.
