### ISSUE TITLE
Version and binary of vsearch for macOS 11 on ARM

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#413]
As macOS 11 (Big Sur) has now been [announced](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/) to run on Apple's 64-bit ARMv8 (aarch64) cpus as well as x86_64, it would be nice to have vsearch run on the macOS / ARMv8 platform as well. Since it already runs on macOS and on ARM it should be easy to port. We could make a fat binary (Universal 2) or, more likely, two separate binaries.

**Comment by torognes** [comment]
The M1 chip has been released and is available in a couple of Macs now. It looks promising.

https://www.apple.com/newsroom/2020/11/apple-unleashes-m1/

**Comment by torognes** [comment]
A binary for vsearch on Apple Silicon (the M1 chip) has been included in the latest release (vsearch-2.15.1-macos-aarch64.tar.gz). It compiled on the new hardware without any changes!

**Comment by colinbrislawn** [comment]
Bio-conda does not support osx-arm64 yet, but they will! Once available, I'll see if I can get vsearch built on that platform.

**Comment by torognes** [comment]
Great! I noticed that it was already included in the latest version of Homebrew for the arm64 architecture.

https://formulae.brew.sh/formula/vsearch
