### ISSUE TITLE
Warn (and stop) if amino acid sequences are detected

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#414]
There has been a request in the forum for vsearch to warn (and stop) if an amino acid FASTA sequence is detected.

https://groups.google.com/forum/#!topic/vsearch-forum/iwVKINHqffo

Lots of non-ACGTU IUPAC characters or the presence of E, F, I, L, P, or Q could trigger a warning or fatal error.

**Comment by PlantDr430** [comment]
Does this mean that Vsearch is not intended to cluster amino acid sequences? Is this a feature that may be implemented in the future?

**Comment by torognes** [comment]
Yes, vsearch only works with nucleotide sequences. We do not have any plans to support amino acid sequences.

**Comment by frederic-mahe** [comment]
I suggest an additional message in the function that already warns about the presence of invalid characters `fastx_close()` (in the `fastx.cc` file):
```C++
fprintf(stderr, "REMINDER: vsearch does not support amino acid sequences.");
```

**Comment by torognes** [comment]
I have added the suggested warning to `fastx.cc` in commit 18ef765512cbc207733355d2066b605cd5d3e855.
