### ISSUE TITLE
cluster-features-open-reference

### ISSUE THREAD

**Issue by chaibenl** [torognes/vsearch#416]
Qiime 2 and others with vsearch as a plug-in offer the option 'cluster-features-open-reference'. How this option can be achieved with vsearch in its native version? Thank you. 
--Benli

**Comment by colinbrislawn** [comment]
open-reference clustering is just
1) doing closed-ref clustering, then
2) taking the reads that don't match and clustering them denovo.

So you could do something like this:

```
vsearch --usearch_global reads.derep.fasta \
  --db database.fasta \
  --sizein --sizeout --id 0.97 \
  --uc closed-ref-hits.uc \
  --notmatched closed-ref-misses.fasta \
  --dbmatched closed-ref.otus.fasta

vsearch --cluster_size closed-ref-misses.fasta \
  --sizein --sizeout --id 0.97 \
  --relabel OTU_ \
  --uc denovo-OTUs.uc \
  --centroids denovo.otus.fasta
```

Before we go to much further, I think it's worth noting that open-ref has [some](https://pubmed.ncbi.nlm.nih.gov/26664811/) [issues](https://peerj.com/articles/1487/) 🙀  and is becoming less popular.

I'm not sure about your goals for your data set, but I no longer use open-ref clustering on my projects as I have found better options! 🎁  Consider the [vsearch pipeline](https://github.com/torognes/vsearch/wiki/VSEARCH-pipeline) suggested by the vsearch devs, or another denoising tool like [swarm](https://github.com/torognes/swarm) or [dada2](https://benjjneb.github.io/dada2/index.html).

**Comment by chaibenl** [comment]
Colin, 

Thank you for the advice. It's very helpful.

Benli
