### ISSUE TITLE
OTUs with sequences having larger than 97% similarity after clustering them with 97% threshold

### ISSUE THREAD

**Issue by vbalanus** [torognes/vsearch#419]
I've used VSearch (vsearch_2.4.3_win_x86_64) implemented into Seed 2.1 (http://www.biomed.cas.cz/mbu/lbwrf/seed/) for clustering about 4.5 million fungal ITS2 sequences on a Windows 10 computer (64 Gb RAM and 3.2 GHz Core-i7 processor).

Everything went fine without any error message. But after selecting the most abundant sequences from every cluster, I've found that there are most abundant sequences from different clusters having 99 or 100% similarity to each other.
Is it normal or something went wrong?

The vsearch log file for the clustering was the following:

14:24:28
Sorting...
deleting previous fasta file... *\fast_clustering.fas
File *\fast_clustering.fas has been saved.
deleting previous uc file... *\fast_clustering.uc
Clustering...
*\Seed_2.1_64bit\tools\vsearch_2.4.3_win_x86_64\vsearch.exe -cluster_fast "*\Seed_2.1_working_lib\Szolo_seed\fast_clustering.fas" -id 0.97 -uc "*\Seed_2.1_working_lib\Szolo_seed\fast_clustering.uc" -usersort
Clustering finished succesfuly...
Preparing sequences...
Number sequences in clusters 4542372
Processing results - please wait... 4542372

**Comment by torognes** [comment]
The centroids of two clusters should never be 97% or more similar when clustering with `--id 0.97`. However, other sequences in two different clusters may in some cases be more similar than that. That can happen when they are on the border between two different clusters and similar enough (>=97%) to both centroids. Which cluster they will be assigned to depends on the order of the sequences and may appear random. This is one of the problems with this type of "greedy" clustering algorithm.

From the log file, it seems like the vsearch `cluster_fast` command is used, which will sort the sequences by decreasing length. (The sequences also seems to be pre-sorted, but I think this will be ignored by vsearch even though the `usersort` option is specified.) That means that the centroid sequence will be the longest sequence in the cluster (or one of them, if there are multiple equally long sequences). You may therefore find other, possibly more abundant, sequences in two different clusters that may be very similar (> 97%).

So this is actually normal and not an error.
