### ISSUE TITLE
How to save singletons in cluster_fast?

### ISSUE THREAD

**Issue by Mengying33** [torognes/vsearch#421]
Hello everyone,
I am trying to use vsearch to process my data. In the step of _cluster_fast_, I would like to save singletons (I have saved **--minuniquesize 1** in the last _unique_ step). I have read the vsearch_manual and some posts, but I still confused about the cluster_fast default value.  Are singletons reserved by default in the step _cluster_fast_? Or do I need to set specific parameters? If so, what parameters need to be set? **--minisize 1**?

It's a small problem, but I want to make a check.

Thanks in advance!
Mengying

**Comment by frederic-mahe** [comment]
hello @Mengying33 , here is a toy-example:
```sh
printf ">s1;size=10;\nAAAA\n>s2;size=1;\nTTTT\n" | \
    vsearch --cluster_fast - --minseqlength 1 --id 0.5 --quiet --centroids - 
```
returns:
```
>s1;size=10;
AAAA
>s2;size=1;
TTTT
```
as you can see `--cluster_fast` does not filter out low abundant sequences (e.g., size=1).  The `--minsize` option you've mentioned is used only with the `--cluster_unoise`, not the `--cluster_fast`. Here the option `--minseqlength 1` is used to simplify the example (shorter input sequences).

**Comment by Mengying33** [comment]
@frederic-mahe Thanks for your nice reply! This makes my problem solved!!!
