### ISSUE TITLE
translated search

### ISSUE THREAD

**Issue by zamanzad** [torognes/vsearch#425]
Hi, I have a question related to translated search, was wondering if we have a nucleotide query used with a protein database, a translated search can be performed in vsearch --usearch_global command or not.
Thanks.

**Comment by torognes** [comment]
Hi, sorry, but vsearch does not support amino acid (or translated) searches at all, and there are no plans to do so at the moment.

**Comment by zamanzad** [comment]
Thanks  a lot for your quick response.
