### ISSUE TITLE
Add option Sample like in Usearch

### ISSUE THREAD

**Issue by tiagobrc** [torognes/vsearch#426]
Is there a way in Vsearch to add sample identifiers to read labels just like in usearch (using the option -sample)?

I am trying to use vsearch but this option does not seem to exist.

Can you please confirm to me that is the case? Or point me to the equivalent parameter in vsearch?

Usearch explanation of the function:

`
`
`
Adding sample identifiers to read labels
If multiple samples are combined into a single file as shown in some of the above examples, then you lose track of which read came from which sample. This is addressed by adding a sample identifier to each read label. The simplest method is to use the -sample option, e.g.

`
`
`

Cordially,

Tiago

**Comment by colinbrislawn** [comment]
Hello Tiago,

Check out the `--relabel` and `--relabel_keep` options. You could also change read labels using the linux `sed` command.

Alternatively, adding the `--sample` flag to vsearch could be helpful.

Colin

**Comment by frederic-mahe** [comment]
Hi @tiagobrc

with vsearch you can read from streams and write to streams, which allows for very flexible and powerful pipelines. For instance, you can merge many fastq samples while retaining the name of the original sample in sequence headers:
```sh
# create individual samples
for SAMPLE_NAME in sample{1..9}.fastq ; do
    printf "@s\nA\n+\nI\n" > "${SAMPLE_NAME}"
done

# pool fastq samples, retain sample names in fastq headers
for SAMPLE_NAME in sample_*.fastq ; do
    vsearch \
        --quiet \
        --fastx_filter "${SAMPLE_NAME}" \
        --relabel "${SAMPLE_NAME/.fastq/}_" \
        --fastqout -
done > all_samples.fastq

# clean up
rm sample{1..9}.fastq all_samples.fastq
```
You will end up with fastq entries formatted as such: "@SampleName_EntryNumber"

**Comment by torognes** [comment]
I think the vsearch (and usearch) option `--label_suffix sample=";sample=SampleA;"` is equivalent to the usearch option `-sample SampleA`. This option can currently be used with the `fastq_mergepairs` and `fastx_revcomp` commands.

In principle the `--label_suffix` option could be used with almost any command that writes FASTA or FASTQ files, so I will enable it with many more commands in the next release.

I'll consider adding the `--sample` option and perhaps the use of the `@` symbol with the `--relabel` option as well.

**Comment by torognes** [comment]
Added in version 2.21.0 just released
