### ISSUE TITLE
Vsearch for clustering protein sequences?

### ISSUE THREAD

**Issue by jacquesantoine26** [torognes/vsearch#427]
Dear All,

My protein database became too big for 32-bit Usearch -cluster_fast.
I tried Vsearch as a replacement but it does not seem to like protein sequences and rejects a number of invalid characters.
It does not crash and nevertheless produces a cluster file: can it be trusted?
I read the Vsearch manual but found nothing on protein sequences.
Please help!
Thank you.

Jacques

**Comment by torognes** [comment]
Sorry, but vsearch does not work with protein sequences and there are no plans to do so.
