### ISSUE TITLE
cluster id in consensus file

### ISSUE THREAD

**Issue by vineeth-s** [torognes/vsearch#428]
Hi,

Would it be possible to have the cluster id in the consensus file FASTA header ?

Cheers, and TIA

**Comment by torognes** [comment]
Sorry for the late reply.

Yes, you can use the `--clusterout_id` option to add that information to the FASTA headers.

```
   --clusterout_id
                       Add cluster identifier information to the output files when using the --centroids, --consout and --profile
                       options.
```

**Comment by vineeth-s** [comment]
thanks much 
sorry i didnt catch this while rtfm'ing'
