### ISSUE TITLE
Unexpected unmerged reads

### ISSUE THREAD

**Issue by olivierrue** [torognes/vsearch#430]
Hi, here are two examples of reads that vsearch (v2.15.1_linux_x86_64) don't merge, even if alignment seems to be evident. They come from real ITS amplicon sequencing data.

```
vsearch  --threads 1 --fastq_mergepairs test_R1.fastq --reverse test_R2.fastq --fastqout vsearch.assembled.fastq  --fastqout_notmerged_fwd vsearch.unassembled_R1.fastq  --fastqout_notmerged_rev vsearch.unassembled_R2.fastq  --fastq_allowmergestagger
```

`Pairs that failed merging due to various reasons:
2  multiple potential alignments`

Yet, R1 and R2 are identical or an overlap of 195 nt is exepected.

R1 reads:
```
@M03930:222:000000000-J9C6R:1:1101:23724:18126 1:N:0:110
CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTAAAAAAACTTATAAACACTTTTAGGAACAAACAAACT
GAACCTTTTTTTTTTCAAAAAAACACAAAAAAAAACTTTCAACAACGGATCTCTTGGTTCTCGCATCGATGAAGAACGCAGC
+
DEDCDFFFFFFFGGGGGGGGGGHHHHHGGHHGHHHHHHHHHGHHGGGHHHHHHHHGGGGGGHHHHHHHHHHHGGGHHHHHHHHHHGHHHHHHHHHHHHHHHHHH
HHHHHHHHHHGGGGGHHHHHHGGGHHHGHHHGGGGGHHHHHHGHHEFFGGGGGGGGGFGGGGGGGGGGGGGGHGGGGGDFCF
@M03930:222:000000000-J9C6R:1:1101:22718:21885 1:N:0:110
CTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTCTCCGTTGGTGAACCAGCGGAGGGATCATTACAGAGTTATCTAACTCCCAAACCCATGTGAACTTAC
CATTTGTTGCCTCGGCAGAGCCTACCCGGTACCTACCCTGGAGCGAGCTACCCTGTAGCTACCCTGGAGCGGGCTACCCTGTAACGTTTTGCCGGTGGACCATT
AAACTCTTGTTATTATATTGTAATCTGAGCGTCTTATTTTAAT
+
CCCCCFFFFFFFGGGGGGGGGGHGHHHGGHHGHHHHHHHHHGHHGHGGHHHHHHHGGGGGGGHGHHHHHHHHHHHHHHHHHHHHHHHHGHGGGHHHHHHHHHHH
HHHHHHHHHHHHHGGGGGGHHHHHHHHGGGGGHHHHHHHHHHHHGGGGGHHHHHHGHHHHHHHHHGHHHHGGGGGGGGGGGGGGGGFGGGGGGGGBGD?FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

and R2 reads:
```
@M03930:222:000000000-J9C6R:1:1101:23724:18126 2:N:0:110
GCTGCGTTCTTCATCGATGCGAGAACCAAGAGATCCGTTGTTGAAAGTTTTTTTTTGTGTTTTTTTGAAAAAAAAAAGGTTCAGTTTGTTTGTTCCTAAAAGTG
TTTATAAGTTTTTTTAATGATCCTTCCGCAGGTTCACCTACGGAAACCTTGTTACGACTTTTACTTCCTCTAAATGACCAAG
+
ABBBCCCCCCFFGGGGGGGGGGGGGHHHHHHHHHHHHGHGGHHHHHHHHHHGGGGGGHHHHHGGGGGGHHHHGGGGGGGGGHHHHHHHHHGHHHGFHHGGFHDG
FGHFHHHGHGHHGGGHGGFHHHHHHHHGGGGGHHHGHHHGHGGGGGHHGGGGGGGGGFGGGGGGGGGFGGGGGGGGGGGGGF
@M03930:222:000000000-J9C6R:1:1101:22718:21885 2:N:0:110
GCTGCGTTCTTCATCGATGCCAGAACCAAGAGATCCGTTGTTGAAAGTTTTGACTTATTAAAATAAGACGCTCAGATTACAATATAATAACAAGAGTTTAATGG
TCCACCGGCAAAACGTTACAGGGTAGCCCGCTCCAGGGTAGCTACAGGGTAGCTCGCTCCAGGGTAGGTACCGGGTAGGCTCTGCCGAGGCAACAAATGGTAAG
TTCACATGGGTTTGGGAGTTAGATAACTCTGTAATGATCCCT
+
?ABABBABBBFFGGGGFGGGGGHHHHHHHHHHHHHHHGHGGHHHHHHGBHHHGHHHHHHHHHGHHHHHGGGGGGHHHHHHHHHHHHHHHHHHHBHHFGHHHHFG
GFGHHHGGGGGGHHGHHHGGHGFGHEH2GGGGFGFHFDFGEHGGHHHHFGHGEHGDGGHGGHHGFEEF=DHHGGG;:CEHCGFHFHG@BGGAFGFEA0FGFFEB
09FFF0BFGGBADFFFAEAFBF/F/BBBFFFFFFFFB/:BFF
```

Is the composition of the sequences problematic for alignment? Other tools like pear or flash succeed. Is there a way to improve vsearch for this type of sequences?

Thanks in advance for your feedback

**Comment by astanabe** [comment]
Hi,
If you change value of "merge_minrepeatdiagcount" in "mergepairs.cc" to INT_MAX and recompile, you may get expected results, I think.
Best wishes,

**Comment by torognes** [comment]
Hi and thanks for pointing out this problem with vsearch.

These reads pairs are not merged because vsearch finds a potential alternative alignment in addition to the obvious one. To avoid a potential wrong alignment, it will not merge the sequences. I think some other tools ignore these kinds of problems.

VSEARCH uses a heuristic to identify potential alignments based on the number of common identical 5-mers it finds in different possible ungapped alignments of the two sequences. When it finds two or more potential ungapped alignments with at least 12 (`merge_minrepeatdiagcount`) such 5-mers in common with the same pair of sequences, it will refuse to merge them.

The first pair of sequences in the example are the exact reverse complements of each other and they contain long stretches of the same nucleotide. This is probably the reason for why it finds a potential alternative alignment. If you displace one of the sequences by just a single position there seems to be 13 such 5-mers in common in the streches of A's and T's.

In the second pair of sequences there is an alternative alignment with a displacement of 26 positions relative to the correct one that also aligns as many as 18 5-mers. It is due to a near-perfect partially overlapping tandem repeat. The alternative alignment looks like this:

```
...CTACCCTGTAGCTACCCTGGAGCGGGCTACCCTGTA...
   |||||| ||| ||||||||||||| |||||||||||
...CTACCCGGTACCTACCCTGGAGCGAGCTACCCTGTA...
```

Other alternative alignments are also possible here.

The heuristic seems to be a bit too blunt in these cases and vsearch could clearly be improved. Perhaps by taking the length of the potential alignment into account. I'll consider doing that.

I can see that this is fungi ITS data. Is a large fraction of your sequences not merged because of this problem?

It may be especially problematic if certain species are systematically excluded because they contain repeats.

**Comment by olivierrue** [comment]
Hi Torbjorn and thanks for the explanations.

I don't really know the proportion of these sequences because they are not my data.These cases were brought to me by a user of our pipeline (FROGS) that uses vsearch. Even if the proportion is small, it remains problematic (and maybe the proportion could be higher in other biological conditions).These cases were brought to me by a user of our pipeline (FROGS) that uses vsearch. Even if the proportion is small, it remains problematic and the proportion may vary in other biological conditions. If you manage to improve the algorithm this would be great news. 

I could try to analyse the Unite sequences (mergeable ones) to see if cases like the ones presented here are frequent or not. I will keep you informed if you are interested ?

At the same time I thank you for the development of vsearch!

**Comment by torognes** [comment]
Thanks. Yes, please keep me informed about your results from UNITE. I'll probably have to analyse that data too in the process of improving the algorithm.

**Comment by olivierrue** [comment]
Hi Torbjorn.
Below is the analysis performed to determine if sequences extracted from Unite are problematic to vsearch.

### First ITSx extracts ITS1 and ITS2 sequences from UNITE (v8.2)
```
conda activate itsx-1.1b
ITSx -i /db/frogs_databanks/assignation/Unite_Euka_8.2_20200204/Unite_Euka_8.2_20200204.fasta --save_regions 'ITS1,ITS2' -o itsx -p /usr/local/genome/ITSx_1.0.11/ITSx_db/HMMs/ --cpu 16
conda deactivate
```
### Analysis of ITS1 sequences
```
mkdir ITS1
cd ITS1
ln -s ../itsx.ITS1.fasta .
```
#### Select sequences with a length between 250 and 490 (at least 10 nt for overlap) from ITS1 FASTA file
```
conda activate seqkit-0.11.0
seqkit seq --min-len 250 --max-len 490 itsx.ITS1.fasta > well_sized.fasta

grep -c '>' well_sized.fasta
41278

seqkit subseq -r 1:250 well_sized.fasta -w 0 > R1.fasta
seqkit subseq -r -250:-1 well_sized.fasta -w 0 | seqkit seq --complement --reverse --upper-case --line-width 0 - > R2.fasta
```
#### Create FASTQ files from FASTA file with fake quality (30)
```
conda activate bbmap-38.86
reformat.sh in=R1.fasta out=R1.fastq qfake=30
reformat.sh in=R2.fasta out=R2.fastq qfake=30
conda deactivate
```
#### Run vsearch
```
conda activate vsearch-2.14.1
vsearch  --threads 1 --fastq_mergepairs R1.fastq --reverse R2.fastq --fastqout vsearch.assembled.fastq  --fastqout_notmerged_fwd vsearch.unassembled_R1.fastq  --fastqout_notmerged_rev vsearch.unassembled_R2.fastq  --fastq_allowmergestagger --fastq_ascii 33 --fastq_maxdiffs 25 --fastq_minovlen 10

vsearch v2.14.2_linux_x86_64, 188.7GB RAM, 40 cores
https://github.com/torognes/vsearch

Merging reads 100% 
     41278  Pairs
     39301  Merged (95.2%)
      1977  Not merged (4.8%)

Pairs that failed merging due to various reasons:
      1977  multiple potential alignments

Statistics of all reads:
    250.00  Mean read length

Statistics of merged reads:
    302.91  Mean fragment length
     58.76  Standard deviation of fragment length
      0.32  Mean expected error in forward sequences
      0.32  Mean expected error in reverse sequences
      0.20  Mean expected error in merged sequences
      0.00  Mean observed errors in merged region of forward sequences
      0.00  Mean observed errors in merged region of reverse sequences
      0.00  Mean observed errors in merged region

conda deactivate
```
#### Extraction of not merged identifiers, and then original FASTA sequences
```
grep "^@" vsearch.unassembled_R1.fastq | sed "s/@//g" | cut -d ' ' -f 1 > ids.txt
conda activate seqkit-0.11.0 && seqkit grep -f ids.txt well_sized.fasta > examples_not_merged.fasta && conda deactivate
conda activate seqkit-0.11.0 && seqkit stat examples_not_merged.fasta && conda deactivate

file                       format  type  num_seqs  sum_len  min_len  avg_len  max_len
examples_not_merged.fasta  FASTA   DNA      1,977  631,180      250    319.3      489
```
### Analysis of ITS1 sequences

The same commands were applied with ITS2 sequences. Here are the results:

```
conda activate vsearch-2.14.1
vsearch  --threads 1 --fastq_mergepairs R1.fastq --reverse R2.fastq --fastqout vsearch.assembled.fastq  --fastqout_notmerged_fwd vsearch.unassembled_R1.fastq  --fastqout_notmerged_rev vsearch.unassembled_R2.fastq  --fastq_allowmergestagger --fastq_ascii 33 --fastq_maxdiffs 25 --fastq_minovlen 10

vsearch v2.14.2_linux_x86_64, 188.7GB RAM, 40 cores
https://github.com/torognes/vsearch

Merging reads 100% 
     27630  Pairs
     26796  Merged (97.0%)
       834  Not merged (3.0%)

Pairs that failed merging due to various reasons:
       834  multiple potential alignments

Statistics of all reads:
    250.00  Mean read length

Statistics of merged reads:
    308.36  Mean fragment length
     58.53  Standard deviation of fragment length
      0.30  Mean expected error in forward sequences
      0.30  Mean expected error in reverse sequences
      0.19  Mean expected error in merged sequences
      0.00  Mean observed errors in merged region of forward sequences
      0.00  Mean observed errors in merged region of reverse sequences
      0.00  Mean observed errors in merged region
```
and
```
conda activate seqkit-0.11.0 && seqkit stat examples_not_merged.fasta && conda deactivate

file                       format  type  num_seqs  sum_len  min_len  avg_len  max_len
examples_not_merged.fasta  FASTA   DNA        834  268,875      250    322.4      485
```

I attach FASTQ files containing problematic reads, for ITS1 and ITS2. 

* [ITS1.tar.gz](https://github.com/torognes/vsearch/files/6048384/ITS1.tar.gz)
* [ITS2.tar.gz](https://github.com/torognes/vsearch/files/6048383/ITS2.tar.gz)

I hope it will help you to improve the algorithm.

**Comment by torognes** [comment]
@olivierrue, thanks a lot!

**Comment by torognes** [comment]
In commit 6f39ea95e499b93fbb80eb24c4f59dbada7cc4df, I have made a change to the `fastq_mergepairs` command. The approach to detect potentially multiple overlap alignments has been changed and now allows many more pairs to be merged. In the ITS1 set, only 56 pairs (2.8%) are rejected. In the ITS2 dataset only 7 of 834 pairs (0.8%) are now rejected. I've also made other changes to the command (see issue #436).

@olivierrue, thanks again of bringing this issue up and for providing the datasets.

**Comment by torognes** [comment]
I've looked at some of the remaining unmerged pairs, and the reason for not merging them seems correct. There is usually some repeats that makes it possible to merge them well with two different overlap lengths.

**Comment by torognes** [comment]
The [release](https://github.com/torognes/vsearch/releases/tag/v2.17.0) with the improved `fastq_mergepairs` command is now available.

**Comment by olivierrue** [comment]
@torognes, thanks for this quick improvement and release !
