### ISSUE TITLE
big difference for clustering otus using vsearch and usearch

### ISSUE THREAD

**Issue by jianshu93** [torognes/vsearch#431]
Dear Torognes,
usearch11 -cluster_otus uniques.fasta -otus otus.fa -relabel Otu -threads 24 -id 0.97 (singletons removed by default -minsize=2)

vsearch -uchime_denovo uniques.fasta --nonchimeras uniques_nochimera.fasta --threads 24
vsearch --cluster_size uniques_nochimera.fasta --id 0.97 --centroids otus_vsearch.fa --threads 24 --relabel Otu

usearch11 use default uparse algorithm for clustering otus. How is vsearch --cluster_size differ from uparse? I have very big difference between otus.fa (2415) and otus_vsearch.fa (12713 total, 8021 singletons). Do I also need to use uchime_ref before clustering? Robert suggests uchime_denovo only but not uchime_ref

Thank you,

[uniques.fasta.gz](https://github.com/torognes/vsearch/files/6074326/uniques.fasta.gz)

**Comment by davidealbanese** [comment]
Dear @jianshu93,
I think you can get close in this way:

1. Dereplication. Predict sequence abundances of each sequence by dereplication, order by abundance and discard sequences with abundance value smaller than 2;
2. Clustering (cluster_size);
3. Remove chimeric sequences from the representatives (uchime_denovo).

See https://micca.readthedocs.io/en/latest/otu.html#de-novo-greedy

**Comment by torognes** [comment]
There are major differences between the `cluster_otus` command in usearch and the alternative commands in vsearch. In vsearch there is no directly corresponding command. Please see [the discussion on the VSEARCH Forum](https://groups.google.com/g/vsearch-forum/c/kh8UZuJlT6g) for further details.
