### ISSUE TITLE
Output merged fasta sequences from allpairs_global?

### ISSUE THREAD

**Issue by andrewd789** [torognes/vsearch#433]
Hi,

`allpairs_global` can output pairwise alignments of matching sequences. Would it be possible to also output each pair of matched sequences merged together in a fasta file?

Here is a scenario where this could be useful: I have two sets of fasta sequences, called A and B, which overlap. A and B might be derived from Illumina sequencing of two overlapping gene regions, which together exceed the length of the sequencing system. I want to find, and merge together, any combinations of an A sequence plus a B sequence that perfectly align over a certain length, thus hopefully obtaining a correct sequence of the full region. 

I can use `allpairs_global` with `-id` and `-mincols` criteria to identify pairs of appropriately matching A and B sequences. But then I need to use something else to merge together those pairs of matching sequences. But it seems like it should be easy to simply output the merged sequences from `allpairs_global`, doesn't it? 

Perhaps this would be complicated by imperfectly matching pairs of sequences, as there isn't a basis for determining which nucleotide is the correct one from fasta data. In which case, it could only be a valid option with '-id 1' (i.e. perfect matches)?

**Comment by frederic-mahe** [comment]
hi @andrewd789 

what you are trying to do with fasta sequences looks a lot like what `vsearch --fastq_mergepairs` does with fastq sequences. If you still have access to your raw fastq sequences, or if you are ok with converting fasta to fake-quality fastq, then you might want to look into that.

Assuming your fasta sequences are not folded (use `vsearch ... --fasta_width 0` to unfold), you can convert fasta entries to fastq:
```sh
printf ">s1\nAAA\n>s2\nAAT\n" | \
    paste - - | \
    awk 'BEGIN {FS = "\t" ; OFS = "\n"}
         {sub(">", "@", $1)
          QUAL = $2
          gsub(".", "I", QUAL)
          print $1, $2, "+", QUAL
         }' > fake_R1.fastq
```
From there, you can try `vsearch --fastq_mergepairs` and its options to control the minimal overlap length and the number of mismatches.

**Comment by torognes** [comment]
As @frederic-mahe wrote, this sounds very much like the `--fastq_mergepairs` command to merge paired-end reads, just with FASTA sequences. An extra requirement is that sequence B is on the opposite strand (reverse complementary) relative to A and that the sequences are supposed to overlap at their 3' ends. (Staggered overlap can be allowed.)

Perhaps we should add a `--fake_qual` option to allow the use of any `--fastq_` command with a FASTA file?

**Comment by frederic-mahe** [comment]
> An extra requirement is that sequence B is on the opposite strand (reverse complementary) relative to A and that the sequences are supposed to overlap at their 3' ends.

Yes, I forgot about that. The fake R2 file can be reverse-complemented using vsearch too (`--fastx_revcomp`).

> Perhaps we should add a `--fake_qual` option to allow the use of any `--fastq_` command with a FASTA file?

I wonder if a dedicated command would not be better than an option. Something like `--fasta2fastq` with options to choose a quality value and an offset. There does not seem to be anything similar in usearch.

**Comment by colinbrislawn** [comment]
>hopefully obtaining a correct sequence of the full region

When you mentioned this, I first thought of assembly or targeted resequencing.

>Perhaps this would be complicated by imperfectly matching pairs of sequences, as there isn't a basis for determining which nucleotide is the correct one from fasta data.

This is a standing problem in assembly, and modern tools support downstream steps to profile potential mutations and investigate their validity. Have you considered approaching this as a assembly problem?

I always happy to see new features added to vsearch! I'm just thinking about other ways to frame this question 🤔

**Comment by andrewd789** [comment]
Hi, thanks for the comments. I agree, this is similar to `fastq_mergepairs`. If it were possible to pass fasta sequences (one reverse-complemented) into `fastq_mergepairs` then that might do the job. I think an option or command to convert fasta to fastq with fake quality information would be helpful.

I think one constraint of `fastq_mergepairs` for this purpose is that the A and B sequences don't have a consistent order (unlike sequences in a typical pair of R1 and R2 fastq files), so it would only be applicable to a single, selected, pair of sequences at a time. Alternatively, the pairs of sequence files could be ordered on the basis of `allpairs_global` output, with optimally matching sequences first.

**Comment by andrewd789** [comment]
@colinbrislawn yes that could be another way to approach it. However, I thought it seemed theoretically easier to filter and denoise to arrive at one (or a few) clean A and B sequences, among which correctly matching A-B pair(s) should be easy to identify. This might just be because I'm more familiar with that approach though.

**Comment by torognes** [comment]
I have added the command `fasta2fastq` in commit d360da66fbba265604ec3e45c889277ddb09e112.

It may be run like this:

```
vsearch --fasta2fastq input.fasta --fastqout output.fastq --fastq_asciiout 33 --fastq_qmaxout 41
```

It uses the value given by the `fastq_qmaxout` option as the fake quality score. The values 33 and 41 above are the defaults, so these options do not have to be specified.

**Comment by andrewd789** [comment]
Hi, thanks for adding this, I will give it a try! (And sorry for the slow response).
