### ISSUE TITLE
Orient seqs by mapping to db

### ISSUE THREAD

**Issue by KasperSkytte** [torognes/vsearch#434]
Hi!

Thanks for vsearch. Due to demand, I'm attempting to make a fully open source version of my [AutoTax](https://github.com/KasperSkytte/AutoTax) pipeline which is now largely based on usearch. So I'm basically taking it one step at a time, and I just wanted to ask whether there is way using `vsearch` to orient sequences based on a reference database like with `usearch -orient`? I see there is no direct command for it, is that just because it's not implemented yet? Or should I use an alternative approach by fx combining existing commands+options for mapping against a database and then reverse-compliment the sequences based on the search results?

**Comment by torognes** [comment]
HI!

Thanks for your interest for using vsearch in AutoTax.

The `orient` command is not implemented in vsearch. We have not been able to keep up with all the commands and options added to usearch since version 7, but we do try to add some of the most interesting or easily implemented ones based on requests. So for now, you'll need an alternative approach, unfortunately.

The `orient` command seems to be relatively simple to implement in vsearch based on [the description](https://www.drive5.com/usearch/manual/cmd_orient.html) and the existing code in vsearch, so I might try to add it, if it would help you move AutoTax to fully open source.

**Comment by torognes** [comment]
I am working on an implementation of the `orient` command now. Hope to have it ready next week.

**Comment by KasperSkytte** [comment]
Hi Torbjørn!

Thank you very much. I would appreciate it, if it's relatively easy to implement. I also use the `stripgaps` option, but that can easily be done with sed/awk instead.

**Comment by torognes** [comment]
The `orient` command has been added in commit 1fa275587f271f8942605bf36248c47772a61dc5.

**Comment by torognes** [comment]
The updated code with the `orient` command has now been released as [version 2.16.0](https://github.com/torognes/vsearch/releases/tag/v2.16.0).

**Comment by KasperSkytte** [comment]
Thank you very much! That was quick, I'll close this.

**Comment by torognes** [comment]
Fine, don't hesitate to report any problems with this command.

**Comment by KasperSkytte** [comment]
Hi again

I have started testing thing with the orient command and I may have some issues, at least with the data I have tested with. I have used 5000 full length 16S sequences as input and none are oriented with `vsearch`, but only 1 is undetermined with `usearch11`. I have used the same database for both (but of course generated by their respective `-makeudb_usearch` commands, and with `vsearch`  wordlength 12 as described in the documentation).

## vsearch
```
$ vsearch --orient ../test/example_data/5k_fSSUs.fa --db ../refdatabases/vsearch/SILVA_138_SSURef_NR99_tax_silva.udb --fastaout oriented_vsearch.fa --tabbedout orient_stats_vsearch.txt

vsearch v2.16.0_linux_x86_64, 30.9GB RAM, 12 cores
https://github.com/torognes/vsearch

Reading UDB file ../refdatabases/vsearch/SILVA_138_SSURef_NR99_tax_silva.udb 100%
Reorganizing data in memory 100%
Creating bitmaps 100%
Parsing abundances 100%
748130866 nt in 510984 seqs, min 900, max 4000, avg 1464
Orienting sequences 100%
Forward oriented sequences: 0 (0.00%)
Reverse oriented sequences: 0 (0.00%)
All oriented sequences:     0 (0.00%)
Not oriented sequences:     5000 (100.00%)
Total number of sequences:  5000
```

## usearch
```
$ usearch11 -orient ../test/example_data/5k_fSSUs.fa --db ../refdatabases/usearch/SILVA_138_SSURef_NR99_tax_silva.udb --fastaout oriented_usearch.fa --tabbedout orient_stats_usearch.txt

usearch v11.0.667_i86linux64, 32.3Gb RAM, 12 cores
(C) Copyright 2013-18 Robert C. Edgar, all rights reserved.
https://drive5.com/usearch

License: xyz, max 1 process(es)

00:00 5.6Mb     0.0% Rows
00:01 1.1Gb    39.1% Rows
00:01 2.8Gb   100.0% Rows
00:01 2.8Gb  Reading pointers...done.
00:01 2.9Gb  Reading db seqs...done.
00:01 3.6Gb  CPU has 12 cores, defaulting to 10 threads
00:01 3.6Gb     0.1% 0 plus (0.0%), 0 minus (0.0%), 0 undet. (0.0%)
00:02 4.3Gb    31.3% 968 plus (61.8%), 599 minus (38.2%), 0 undet. (0.0%)
00:02 4.3Gb   100.0% 3435 plus (68.7%), 1564 minus (31.3%), 1 undet. (0.0%)
```

**Comment by KasperSkytte** [comment]
The data I have used is this: https://github.com/KasperSkytte/AutoTax/blob/master/test/example_data/5k_fSSUs.fa

**Comment by torognes** [comment]
Thanks for reporting the problem. Sorry for the error. I am working to resolve it.

**Comment by torognes** [comment]
It should be fixed now in commit 778a97c6410ace5c68ca08437547afd73b96a556. I'll make a new release soon.

**Comment by KasperSkytte** [comment]
Magnificent, works like a charm now. Thank you for the quick fix!

**Comment by torognes** [comment]
The [release](https://github.com/torognes/vsearch/releases/tag/v2.17.0) with the fixed orient command is now available.
