### ISSUE TITLE
permission issue on BigSour?

### ISSUE THREAD

**Issue by FabianRoger** [torognes/vsearch#437]
I don't know if this is the issue but since I updated to BigSour, code that previously worked doesn't run anymore.

I even re-installed the latest version of vserach (the binary package for mac with intel chip) but the problem persists. 

This is the code

    vsearch --cluster_fast ~/path/to/file/file.fasta --centroids ~/path/to/file/file_clustered_99.fasta --id 0.99 --uc ~/path/to/file/file_99_cluster.txt

The code ran without problems last time I tried it. Now I get the error 

`Fatal error: Unable to open centroids file for writing`

____________________________________________

Vsearch version: `vsearch v2.17.0_macos_x86_64, 16.0GB RAM, 4 cores`

Hardware: `Fabians-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

Software: 

    ProductName:	macOS
    ProductVersion:	11.2.2
    BuildVersion:	20D80

**Comment by frederic-mahe** [comment]
hi @FabianRoger could you please try to run some tests?

https://github.com/frederic-mahe/vsearch-tests

The first failing tests will help us understand whether this is a vsearch issue or not.

**Comment by FabianRoger** [comment]
Thanks fro coming back so fast. I attach the output of the run_all_tests.sh script

Not that it says that vsearch is not in the path, but this is not the problem as I call Teh executable with the full path. 

[vsearch_test.txt](https://github.com/torognes/vsearch/files/6229956/vsearch_test.txt)

**Comment by frederic-mahe** [comment]
> Fatal error: Unable to open centroids file for writing

Well, that could mean that the write rights for the folder are not set up correctly. Could you please try to write to that folder (`touch ~/path/to/file/tmp` should do the trick).

**Comment by FabianRoger** [comment]
OMG... The path had changed. It works flawlessly. Sorry for taking up your time with this and thanks for the help!

**Comment by frederic-mahe** [comment]
no problem. Happy to see that vsearch works on the latest macOS.
