### ISSUE TITLE
Formatting SILVA to use with VSEARCH

### ISSUE THREAD

**Issue by GeoMicroSoares** [torognes/vsearch#438]
Hi there,

I've been trying to use VSEARCH with the latest [SILVA database](https://www.arb-silva.de/no_cache/download/archive/release_138/Exports/), but seems there's something with its headers that stop any meaningful outputs from being produced. I've read [here](https://github.com/torognes/vsearch/issues/405) that headers should be formatted in a specific way e.g. `>12345;tax=k:Bacteria,p:Firmicutes,c:Clostridia,o:Clostridiales,f:Clostridiaceae,g:Clostridium sensu stricto 2,s:Clostridium cadaveris`.

This doesn't look like something easily done with `sed`, given possible spaces in the species field. At the moment, the FASTA looks as follows:
```
$ head -n1 SILVA_138_SSURef_NR99_tax_silva.fasta
>AY846380.1.2583 Eukaryota;Archaeplastida;Chloroplastida;Chlorophyta;Chlorophyceae;Monoraphidium minutum
```

Just wondering if anyone's come up with a way to modify the SILVA SSURef NR99 FASTA to work properly with `VSEARCH --sintax`?

At this point, using the SILVA FASTA above I'm getting something like this:
```
$ cat test.txt
test_seq		+
```

**Comment by frederic-mahe** [comment]
Well, you could use a `sed` command like this one:
```sh
sed '/^>/ {s/;/,p:/ ; s/;/,c:/ ; s/;/,o:/ ; s/;/,f:/ ; s/;/,g:/ ; s/ /;tax=k:/}' input > output
```
However, the number of fields in silva's taxonomy is variable (not always 8), so this will not work for all silva entries. Maybe there is a silva export that preserves the taxonomic-level markup?

**Comment by GeoMicroSoares** [comment]
Thanks @frederic-mahe , giving that a try but getting this error: `sed: 1: "/^>/ {s/;/,p:/ ; s/;/,c ...": bad flag in substitute command: '}'`

Have been looking for compatible SILVA exports but it doesn't seem to be a thing...

**Comment by torognes** [comment]
It seems like the number of terms in the SILVA taxonomy ranges from 2 to 20. I do not think there is an easy way to convert this data to the fixed level taxonomy used in `sintax`. I guess you'll need to get some additional data from SILVA to be able to do this.

**Comment by GeoMicroSoares** [comment]
Thanks @torognes - could you recommend a properly formatted database compatible with VSEARCH --sintax for 16S rRNA gene amplicons by any chance?

**Comment by vmikk** [comment]
@GeoMicroSoares, You may try to use [RESCRIPt](https://github.com/bokulich-lab/RESCRIPt)-formatted SILVA database. It should have 7 taxonomic ranks and could be easily converted to SINTAX-friendly headers.
Please find the files here: https://docs.qiime2.org/2021.2/data-resources/#silva-16s-18s-rrna

Just extract `dna-sequences.fasta` from `silva-138-99-seqs.qza`, and `taxonomy.tsv` from `silva-138-99-tax.qza` with zip.
To concatenate full headers with sequences you may use: 
```
awk 'NR>1' taxonomy.tsv \
  | sed 's/; /,/g' | sed 's/__/:/g' | sed 's/ /_/g' | sed 's/\t/;tax=/' | sed 's/^/>/' \
  > txx

awk 'NR==1 {print ; next} {printf /^>/ ? "\n"$0"\n" : $1} END {printf "\n"}' dna-sequences.fasta \
  | awk 'NR%2==0' \
  | paste -d'\n' txx - \
  | gzip > SILVA138_RESCRIPt.fasta.gz

rm txx
```

With kind regards,
Vladimir

**Comment by jcmcnch** [comment]
I ran into the same issue and made some notes in a repo that may be useful for others along the lines of @vmikk 's answer:

https://github.com/jcmcnch/515F-Y_926R_database_construction

**Comment by jcmcnch** [comment]
@GeoMicroSoares
