### ISSUE TITLE
Chimera detection

### ISSUE THREAD

**Issue by 18AS** [torognes/vsearch#444]
I picked de-novo OTUs using SUMACLUST. Can I apply de-novo chimera checking with vsearch on the representative sequences generated after OTU picking using the **"vsearch chimera detection"** utility hosted in the usegalaxy.org platform? Could you please point out if this is recommended and why if not. I will be grateful if you kindly share your suggestions in this regard or correct me.

**Comment by torognes** [comment]
Yes, I think you perform chimera detection with VSEARCH on the representative sequences obtained from SUMACLUST.

The version of VSEARCH on usegalaxy.org is fairly old (version 2.8.3 from August 2018), but I do not think there has been any important changes to the chimera detection code since then.
