### ISSUE TITLE
-sample_delim in building OTU Table

### ISSUE THREAD

**Issue by hjruscheweyh** [torognes/vsearch#445]
Dear vsearch developers

I'm writing you because I have an issue while building an OTU Table with vsearch.

Lets assume that I have 2 samples `sample_1` and `sample_2` with the reads:

reads.fasta --> 
```
>sample_1.1
ACGT
>sample_1.2
ACGT
>sample_2.1
ACGT
>sample_122
ACGT
```

I cluster these sequences into OTUs (content doesnt matter) and want to align the original sequences back to the OTU sequences to build the OTU Table:

`vsearch -usearch_global reads.fasta --db otus.fasta ....`

Now I get an OTU table with only one sample named `sample`. This is because vsearch assumes that everything before the first underscore identifies the sample and the rest only identifies individual reads. 

Is there a way how I can specify that only a dot should be used as sample delimiter? In `usearch` this is the parameter `-sample_delim` and I wonder if `vsearch` has a parameter with the same function.

Thanks a lot and best,

Hans

**Comment by torognes** [comment]
Hi

I am sorry, but vsearch does not have the `sample_delim` option as for now.

I do not understand why you ended up with just `sample` as the sample name.

Currently, vsearch should create a sample name from all characters it finds in the label until something else than letters (`A`-`Z`, `a`-`z`), digits (`0`-`9`) or underscores (`_`) appears. In the example above, I think the sample names should be everything before the dots (`.`), i.e. `sample_1` and `sample_2` (and `sample_122`, perhaps a typo).

One can also use the alternative form where the sample name is specified more explicitly, with a FASTA header like `>abc;sample=sample_1;xyz`. In this case, everything between `sample=` and `;` will be used as the sample name.

I will consider implementing the `sample_delim` option in the future.

Here is the documentation from USEARCH on this issue:

https://www.drive5.com/usearch/manual/upp_labels_sample.html

**Comment by hjruscheweyh** [comment]
Hi!

Thank you for the feedback. I have added the `sample=` term into my fasta files and now it works without any issue. Thank you a lot.

Hans
