### ISSUE TITLE
static compile vsearch

### ISSUE THREAD

**Issue by hildebra** [torognes/vsearch#446]
Hey vsearch team,
I was wondering if you could add a static compile for vsearch? The latest vsearch 2.17.0 is not compatible with the C++ libraries I have currently installed so (GLIBCX..) I need to manually compile it.
thanks, Falk

**Comment by torognes** [comment]
I've just released [vsearch version 2.17.1](https://github.com/torognes/vsearch/releases/tag/v2.17.1) with precompiled executables with static linking for all Linux architectures. I hope this resolves the issue.

**Comment by hildebra** [comment]
thank you

**Comment by billzt** [comment]
Sorry, but can you provide a static compile for version 2.24.0? I found that v2.23.0 has a static compile release, but v2.24.0 hasn't

**Comment by torognes** [comment]
I've added the static versions now.
