### ISSUE TITLE
qsegout / tsegout

### ISSUE THREAD

**Issue by dleopold** [torognes/vsearch#447]
Does vsearch have output options similar to the -qsegout and -tsegout options from usearch? These options output only the aligned section of the query or target sequence, respectively. I often use this functionality of usearch when building taxonomic reference databases to extract target amplicons when one or both priming sites may be missing. Of course, some of the options in the -userfields could be used to identify and extract the aligned regions, but it would be nice to be able to directly output the aligned region to a fasta file.

**Comment by torognes** [comment]
Sorry, but vsearch currently does not have those options.

It seems like a simple feature to implement, and I will consider including it in a future version.

**Comment by torognes** [comment]
The qsegout and tsegout options have been added in commit 5e65ef4ad623482a7ead0012d8e53a62b59b6053 for all clustering and searching commands.

**Comment by torognes** [comment]
Added in version 2.21.0 just released.

**Comment by dleopold** [comment]
Thank you.
