### ISSUE TITLE
vsearch compilation issue

### ISSUE THREAD

**Issue by DenisGoryunov** [torognes/vsearch#448]
I've cloned vsearch and got error after autogen.sh script running by command:
./autogen.sh

"Can't locate Autom4te/General.pm in @INC (@INC contains: /home/tools/autoconf/autoconf-2.69/share/autoconf /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/tools/autoconf/autoconf-2.69/bin/autoreconf line 43.
BEGIN failed--compilation aborted at /home/tools/autoconf/autoconf-2.69/bin/autoreconf line 43."

Could you help me to fix it please?

**Comment by torognes** [comment]
Have you installed automake? I think the error message you got indicates that autoconf is installed, but not automake.

The following packages are usually required to compile vsearch: autoconf, automake, make, g++, and libstdc++. In addition zlib-dev and bzip2-dev are recommended, but not required. The exact names of these packages depend on the Linux distribution.

**Comment by frederic-mahe** [comment]
For example, on GNU/Debian and derivative distributions, the autotools are available in the package [ui-auto](https://packages.debian.org/en/buster/ui-auto).

**Comment by DenisGoryunov** [comment]
Thank you for your response! I did the following before the autogen.sh running:
module load gcc/gcc-6.3
 automake --version
automake (GNU automake) 1.11.1

But ended up with exactly the same error message.

**Comment by torognes** [comment]
It's difficult to say what's wrong. Maybe there is a problem with the Perl installation.

Automake version 1.11.1 is fairly old (2009). I am using version 1.16.

Have you considered using [the pre-compiled binaries](https://github.com/torognes/vsearch/releases)?

**Comment by DenisGoryunov** [comment]
Thanks! I'm wondering, which Perl version is required?
We have perl-5.10.1 and perl-5.30.1 installed on our cluster.

**Comment by torognes** [comment]
Autoconf requires Perl. On Debian, Autoconf 2.69 requires Perl >=5.005, so it does not seem to require a recent version.

**Comment by DenisGoryunov** [comment]
I've fixed the issue. Apparently there is a conflict between Automake and GCC versions in our system. Thank you for your help!

**Comment by torognes** [comment]
Good to know you solved the issue.
