### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by Patg13** [torognes/vsearch#451]
Hi 
I tried to complied the lastest version of vsearch and I got an error during the make :

fastx.cc: In function 'uint64_t fastx_file_fill_buffer(fastx_handle)':
fastx.cc:566:11: warning: variable 'bytes_read' set but not used [-Wunused-but-set-variable]
       int bytes_read = 0;
           ^~~~~~~~~~
fastx.cc:633:32: error: 'bytes_read' was not declared in this scope
       h->file_buffer.length += bytes_read;
                                ^~~~~~~~~~
fastx.cc:633:32: note: suggested alternative: 'xopen_read'
       h->file_buffer.length += bytes_read;
                                ^~~~~~~~~~
                                xopen_read
fastx.cc: At global scope:
fastx.cc:636:1: error: expected declaration before '}' token
 }
 ^

I've tried compile from v2.17.1.tar.gz and from the cloned repo, same error.

Do I miss a library or is there something I must do to correct this ?
Thanks !

**Comment by Patg13** [comment]
Oups, my bad... I had a conda environment loaded and it was conflicting the the compilation, I deactivated it and it's compiling correctly now.

**Comment by torognes** [comment]
Not your fault! There was an error in the code causing a compilation error when the zlib.h head file was unavailable. Fixed in commit f435de0c65a6426a765ba5a89de9f10958aed6f0.
