### ISSUE TITLE
Feature request - UDB support with `uchime_ref`

### ISSUE THREAD

**Issue by vmikk** [torognes/vsearch#462]
Hello,
Would it be possible to support UDB files when using `uchime_ref`?
Currently `vsearch --uchime_ref ... -db DB.udb` returns
```
Fatal error: File type not recognized.
```

This will save a lot of time if reusing the same database for chimera detection.
Probably related to the issue #234.

With kind regards,
Vladimir

**Comment by torognes** [comment]
This feature has now been implemented in commit 6a302a18c3067dfc312562f4b4b532c6188e8da8. The `--db` option will accept a UDB file. The file format is detected automatically. Simple create a UDB file with the `makeudb_usearch` command, perferably with the `--dbmask dust` option included (for similar results as with a FASTA file).

**Comment by vmikk** [comment]
That's awesome! Thank you so much!
