### ISSUE TITLE
Version of the make utility to compile the vsearch software

### ISSUE THREAD

**Issue by DenisGoryunov** [torognes/vsearch#463]
Hello,

Today i encountered an issue when tried to compile the software on the cluster. In particular i was not able to do it by **make 3.81** , but managed that using **make 4.3**. Could you please specify in the software documentation the reqired **make** version ?

Regards,
Denis

**Comment by torognes** [comment]
Thanks for the feedback. Could you please indicate what kind of system (os version, architecture) you are compiling vsearch on, which version of vsearch you are compiling, what kind of error you encountered, etc?

I have compiled vsearch successfully using make version 3.81, 3.82 and 4.2.1, and have never encountered problems with any particular version of make.

**Comment by DenisGoryunov** [comment]
We are using Scientific Linux release 6.8 (Carbon) x86_64. I compiled vsearch v2.18.0_linux_x86_64. The error was:
```
make  all-recursive
make: *** [all] Killed
```

**Comment by frederic-mahe** [comment]
I tried to replicate the issue but Scientific Linux 6.8 was released in July 2016, and the whole 6.x branch was marked as end-of-life a year ago. I was not able to find an ISO I could install.

I confirm that `vsearch` compiles correctly with GNU Make 3.82 on other Linux distributions I have tested. I have access to several computation facilities, which tend to be conservative regarding the installed software, and GNU Make 3.82 is the oldest version of `make` available on these systems. So, I was not able to test make 3.81.

**Comment by DenisGoryunov** [comment]
Hi,
Thanks for you reply. Unfortunately i'm just one of the cluster users and don't have ISO for the Scientific Linux release 6.8 (Carbon) x86_64 for testing.

**Comment by DenisGoryunov** [comment]
We are using gcc-6.3 and autoconf 2.69. I thought that the error was because of the make 3.81, as error disappeared when i switched to the  make 4.3.

**Comment by torognes** [comment]
Seems like 3.82 may be required on Linux. I will note this in the documentation.

**Comment by DenisGoryunov** [comment]
Thank you for your assistance.

**Comment by torognes** [comment]
Note added in version 2.19.0.
