### ISSUE TITLE
Allow randseed option to sintax command

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#464]
It has been suggested to allow the randseed option to be used with the sintax command since the algorithm has a random element and can give different results.

**Comment by torognes** [comment]
Added in commit 4880186cf5d39ff3bc468098b583b91008c9a0ab.

**Comment by torognes** [comment]
Feature added in version 2.19.0 just released.

**Comment by lokeshbio** [comment]
Hi, I just used the `--randseed` option and tried with identital runs but it seems like it still gives very different results!

**Comment by torognes** [comment]
Thanks for reporting this! I'll look into the problem.

**Comment by lokeshbio** [comment]
I noticed that `sintax.cc` script has the `int64_t x = random_int(kmersamplecount);` function in line 255! Not sure if there is a way to feed `--randseed` to this function?

**Comment by johnne** [comment]
Hi @torognes,
are there any updates on this issue?

**Comment by torognes** [comment]
Unfortunately, I have not had time to look at this issue in detail yet, but I will have a look at as soon as I have some time.

**Comment by torognes** [comment]
It seems like one needs to limit the number of threads to 1 with the option `--threads 1` for the `--randseed` option to work well with the `--sintax` command. Otherwise the results may vary due to randomness related to multiple threads. You may use this as a workaround for now.

I will add info about this to the documentation and see if there is a better solution.

**Comment by torognes** [comment]
In commit 75e6251, I have added a warning when using `--sintax` with `--randseed` and multiple threads. I have also included information about this problem in the manual.
