### ISSUE TITLE
drop in replacement for usearch

### ISSUE THREAD

**Issue by lskatz** [torognes/vsearch#484]
Hi, thank you for this software.  Assuming that everything I want to do in usearch is in vsearch, can I literally rename it?  Like `mv vsearch usearch`?  I didn't see that explicitly in the documentation but maybe I missed it.  Thank you!

**Comment by torognes** [comment]
I do not think that is a good idea. It implements most functions in usearch version 7, but not everything is exactly similar. Many functions implemented in later versions of usearch is missing in vsearch. We have tried to make it similar and compatible, but not to the extent that I would recommend literarily replacing it.

**Comment by lskatz** [comment]
I think this is the line where I want to drop in a replacement, in a 3rd party software.  Any tips are appreciated if you have them.  Basically I cannot get usearch when building a container for this software and I want to be able to drop in vsearch somehow.  https://github.com/zheminzhou/EToKi/blob/1.2/modules/MLSType.py#L181

**Comment by lskatz** [comment]
I think I figured it out and that I had to switch it to the nt fasta files instead of aa.

**Comment by torognes** [comment]
Yes, vsearch does not work with amino acid sequences. Those functions of usearch are not implemented.
