### ISSUE TITLE
Could I only output the names  of query and target sequences when I use "--usearch_global" function?

### ISSUE THREAD

**Issue by Statistic-Qin** [torognes/vsearch#486]
I use the **--usearch_global** funtion for mapping query and target sequences. I find I can use the **--fastapairs** output the mapped sequences, but I can't only output the paired names. I want the output file like the picutre, which is using the **-mapout**  option in **usearch**.
![image](https://user-images.githubusercontent.com/40289105/166130237-1459196d-c3f8-4a94-85c0-9d62d732007d.png)

**Comment by frederic-mahe** [comment]
I am not sure to understand your question, but the `--userout` and `--userfields` options allow users to define their own output table:
```sh
vsearch \
    --usearch_global <(printf ">s1\nAAAAA\n") \
    --db <(printf ">s2\nAAAAT\n") \
    --minseqlength 1 \
    --id 0.75 \
    --quiet \
    --userfields query+target \
    --userout -
```
```
s1	s2
```

**Comment by Statistic-Qin** [comment]
Thanks！ That options solved my problem.

**Comment by frederic-mahe** [comment]
@Statistic-Qin if your problem is solved, then please close the issue
