### ISSUE TITLE
sintax: should the command accept the --minseqlength option?

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#494]
`vsearch --sintax` does not accept that option, and filters out sequences shorter than 32 nucleotides.

**Comment by torognes** [comment]
The option should be accepted. Will fix.

**Comment by torognes** [comment]
Fixed in commit b83e8b7797ad05ede4928e7e8216b6bbb1badf8a. Both the `minseqlength` and the `maxseqlength` option is allowed now.

**Comment by torognes** [comment]
Fixed in version 2.21.2, which has been released. Unfortunately I forgot to mention this in the release description.
