### ISSUE TITLE
Missing options in `--orient`

### ISSUE THREAD

**Issue by mirand863** [torognes/vsearch#502]
Hi, I am trying to replace `--usearch_global` with `--orient` for a third-party package that depends on vsearch, but `--orient` does not have some parameters that exist with `--usearch_global`, i.e.:

    --id
    --maxaccepts
    --strand
    --query_cov
    --userfields
    --leftjust

Can you please add these parameters for `--orient`? Or is there a reason why these parameters are not available?

**Comment by torognes** [comment]
Hi, `--usearch_global` and `--orient` are quite different commands and it does not make much sense to include these options for `--orient`. I do not understand why you would replace these commands. Usearch does not have these options for `orient` either.

**Comment by torognes** [comment]
I see now that this is related to an issue in RESCRIPt (https://github.com/bokulich-lab/RESCRIPt/issues/146).

I guess you would need to change a bit more than just the command. Some of the arguments (e.g. `id`, `maxaccepts`, `query_cov`) can probably just be dropped. What to do with the others depend on the context and how they are used.

**Comment by mirand863** [comment]
> Hi, `--usearch_global` and `--orient` are quite different commands and it does not make much sense to include these options for `--orient`. I do not understand why you would replace these commands. Usearch does not have these options for `orient` either.

Thank you very much for the fast response!

You are absolutely right. These parameters do not exist in usearch and some can also be removed without any implication. Hence, I will close this issue.
