### ISSUE TITLE
Can vsearch combine two clustered-otutab together?

### ISSUE THREAD

**Issue by peiyaohu** [torognes/vsearch#507]
Can vsearch be used to merge 2 otutabs (clustered from two different batches of samples, at 97% similarity) together?

**Comment by peiyaohu** [comment]
Thanks！ 
But I have another question: 
Both otutab1 and otutab2 were clustered at 97% similarity. And I want combine them into a new otutab(otutab3): 

If I use otutab1 as a reference, use blast to compare otutab2 with it (set 97% similarity), some otu may be aligned while others are not. Then relabel the unaligned OTUs bind them to otutab1, that’s=>
 otutab3 =otutab1+ otutab2-unaligned,
then is otutab3 reliable?

**Comment by torognes** [comment]
I would not rely on it. Even though all OTUs in otutab3 are at least 97% different, there might be sequences assigned to an otu in otutab1 that are actually more similar to otus in otutab2 and the other way round. You should reassign all sequences to  otus again together.

**Comment by frederic-mahe** [comment]
> Even though all OTUs in otutab3 are at least 97% different, there might be sequences assigned to an otu in otutab1 that are actually more similar to otus in otutab2 and the other way round.

I've added a test covering that specific case https://github.com/frederic-mahe/vsearch-tests/commit/8d421c49ac150823c5cb9b5c2d4cd03502acb79d

I am going to close that issue. Please feel free to re-open if need be.
