### ISSUE TITLE
Handle alignments of long sequences correctly

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#52]
Very long sequences, i.e. sequences longer than about 16000 bp, if using default scoring parameters, may get scores of a magnitude greater than can be held in a 16-bit signed integer, e.g. lower than -32768 or higher than 32767. Such alignments are not handled correctly by the current version of vsearch and may lead to incorrect results. This problem must be detected and solved by aligning using a larger magnitude for scores. Currently vsearch may not work correctly for sequences longer than about 16000 bp.

**Comment by macmanes** [comment]
The current STDOUT says that the sequences > 15kb in length are discarded. Is this really the case? It might be better to pass them to the output file un-clustered rather than just discarding them.

**Comment by Blahah** [comment]
this is a total blocker for us @torognes - is there anything we can do to help speed it along? Can you point to the specific problem in the code?

**Comment by torognes** [comment]
I understand that the sequence length limitation is a serious problem in many cases and I am working on a solution. Just passing the longer sequences on to the output might be a possibility, but I would rather work on fixing the problem more permanently.

There are at least three problems with long sequences:

1) Long sequences may generate very high and very low alignment scores that the aligner (in align_simd.cc) cannot handle because it currently processes eight different alignments in parallel (using SSE2 instructions) with scores limited to 16-bit values. The cases were overflow occurs need to be detected. I also need to write a four-way 32-bit version of the aligner to handle the problematic cases.

2) Another problem with long sequences is that the current aligner stores the entire alignment backtracking matrix. This requires substantial amounts of memory with long sequences and usually becomes a problem at about the same magnitude of sequence lengths (~20kb). This problem can be solved using the linear space divide and conquer approach to optimal alignment by Myers and Miller. I have an implementation of that approach in another project that I can adapt and include in vsearch.

3) The third problem is that vsearch performs a full optimal global alignment of the sequences. This works well when sequences are reasonably short, but with long sequences this can be very slow since time used is proportional to the product of the lengths of the sequences. A solution might be to perform a banded alignment around a selected diagonal only.

When designing vsearch I had 100-1000bp sequences (i.e Illumina or 454 reads) in mind as my previous experience with metagenomic data has been with sequences of this length range. I realise now that people want to use it for much longer sequences.

USEARCH version 7 has a default maximum sequence length of 50000 bp (specified with the -maxseqlength option). Is 50000 acceptable or do you need to process even longer sequences? How long? Entire eukaryotic chromosomes? Please describe the use cases were you'd like to use vsearch.

**Comment by torognes** [comment]
Implementing a linear space optimal aligner that should solve the problems (both the magnitude of scores and the extreme memory requirements). Hope to release a new version by the end of the week.

**Comment by Blahah** [comment]
That's excellent, thanks @torognes

**Comment by torognes** [comment]
Hi @macmanes and @Blahah !

This problem is fixed in vsearch 1.0.8. It should now work correctly also for very long sequences.

Similar to usearch there is an --maxseqlength option to discard long sequences. The default has been reset to 50000 bp (similar to usearch), but it can be increased if needed,

Underflow or overflow in the SIMD aligner is now detected and dealt with. A linear memory aligner has been implemented which will be used in those cases and for aligning sequences where the product of their length is more than 25 000 000. So if you align two sequences longer than 5000 bp the new aligner will be used. That aligner is perhaps 20X slower than the SIMD aligner, but uses only a very  small amount of memory.

The speed of vsearch will not be fast with long sequences, but it should at least work correctly. It is designed for short sequences. In the future we might consider adding a faster and heuristic method to align long sequences, but for now it will use an exact and optimal alignment.

I hope vsearch will be useful for your project.
