### ISSUE TITLE
maxseqlength is not supported by makeudb_search command

### ISSUE THREAD

**Issue by javieriserte** [torognes/vsearch#523]
Here's a minimal code to reproduce the error.

    printf '>S1\n%*s' 11 | tr ' ' 'A' | vsearch --makeudb_usearch - --maxseqlength 10 --output a.udb

I get this error:

    Fatal error: Invalid options to command makeudb_usearch
    Invalid option(s): --maxseqlength
    The valid options for the makeudb_usearch command are: --bzip2_decompress --dbmask --gzip_decompress --hardmask --log --minseqlength --no_progress --notrunclabels --output --quiet --threads --wordlength

--maxseqlength is a general option and should be available for all commands.

**Comment by torognes** [comment]
You're right, this option should be available for the `--makeudb_usearch` command. Thanks for reporting!

**Comment by frederic-mahe** [comment]
I've added tests covering that particular issue https://github.com/frederic-mahe/vsearch-tests/commit/230418efc43f503cae7dfdd4530f26f905f13980

**Comment by torognes** [comment]
Fixed in commit 3ec2202.

**Comment by frederic-mahe** [comment]
Fix confirmed, I am closing this issue. Thanks!
