### ISSUE TITLE
fastq_mergepairs: merging stats should be written to log file if --log is used 

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#527]
Current situation:
- without `--log`: vsearch header + **merging stats** are written to `stderr`
- with `--log`: vsearch header + time and memory are written to log file, and vsearch header + merging stats are written to `stderr`

I think it should be:

- with `--log`: vsearch header + **merging stats** + time and memory are written to log file, and vsearch header is  written to `stderr` (use `--quiet` to remove if need be)

(covered` by tests in commit https://github.com/frederic-mahe/vsearch-tests/commit/2e692a4695bd2ce91c49bb4982a482b5679d4a63)

**Comment by torognes** [comment]
Should be fixed in commit 9009225.

**Comment by frederic-mahe** [comment]
thanks!
