### ISSUE TITLE
sintax output is sometimes 4 columns and other times 5 columns

### ISSUE THREAD

**Issue by todd-desantis** [torognes/vsearch#532]
Within a single output file, most rows are 4 columns, as expected, but some of the query sequences that presumably match nothing in the database result in rows with 5 columns. The first column is the  sequence header and the next 4 are empty.   Here's real output notice the row for ASV1964 has more tabs then the other two rows (might be able to see with this formatting).

```
ASV1956 d:Bacteria(1.00),p:Firmicutes_A(1.00),c:Clostridia(1.00),o:Lachnospirales(1.00),f:Lachnospiraceae(1.00),g:Anaerobutyricum(1.00),s:Anaerobutyricum__soehngenii(1.00)     +       d:Bacteria,p:Firmicutes_A,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Anaerobutyricum,s:Anaerobutyricum__soehngenii
ASV1964                         
ASV1931 d:Bacteria(1.00),p:Firmicutes(1.00),c:Bacilli(1.00),o:Lactobacillales(1.00),f:Lactobacillaceae(1.00),g:Lactobacillus(1.00),s:Lactobacillus__delbrueckii(1.00)   +       d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Lactobacillus,s:Lactobacillus__delbrueckii
```

**Comment by torognes** [comment]
Thanks for reporting this issue. Could you please check which vsearch version you are running? I think this issue have been reported and fixed earlier, but it may have returned. See issue #493.

**Comment by todd-desantis** [comment]
Thank for the response.  I encountered the problem on v2.21.1.
```
$ vsearch
vsearch v2.21.1_linux_x86_64, 251.5GB RAM, 40 cores
```
I now see that you've released later versions. I'll upgrade and see if the problem persists.

**Comment by todd-desantis** [comment]
I'm now running vsearch v2.23. Thanks. I'll close this issue.
