### ISSUE TITLE
blast6out subject and query hit location.

### ISSUE THREAD

**Issue by Verrus** [torognes/vsearch#54]
Vsearch does not list hit location, only query orientation and subject length.
using a fasta database.
So i guess a feature request/enhancement.

**Comment by Verrus** [comment]
Hi Torognes,

Thanks so much for the tip, i will eleborate a little on your suggestion based on my experience.

My first run was executed with the blastout -m 8 according to these specifications.
http://www.drive5.com/usearch/manual/blast6out.html

Fields 7,8,9,10 are indeed the same fields you described as (qlo+qhi+tlo+thi)

As stated by you the global alignment positions were returned thus the length 1, and the length of query and target.

By using the --userout parameter with all possible fields, my desired answer was returned, and thus contained the alignment positions.

Blast -m 8 or outfmt=6 describes the same fields but do not display the same values as with the userout.

My problem is solved.

Thanks!

**Comment by torognes** [comment]
Hi Verrus,

To ensure the best compatibility with usearch we have decided to change the meaning of the userfields qlo, qhi, tlo and thi back to the definition in usearch and make them equal to fields 7-10 in the blast6out format.

In addition, as a compensation, we'll add four new userfields called qilo, qihi, tilo, and tihi which will represent the match coordinates (query start, query end, target start, target end) when terminal gaps are ignored (the i stands for internal or interior). These values will be similar to the current values of qlo, qhi, tlo, thi in vsearch 1.0.7.

You will then have to modify your scripts a little bit. Sorry for the inconvenience.

- Torbjørn

**Comment by Verrus** [comment]
Hi Torbjørn,

No problem, modifications like these are trivial!

Good luck with the implementation!

- Verrus

**Comment by torognes** [comment]
Hi @Verrus !

The changes indicated above are included in vsearch 1.0.8.

The userfields qlo, qhi, tlo and thi now contain the start and end of the query and target sequences. So tlo will always be 1 and thi will always be equal to the length of the target. Unless the matching is on the reverse strand qlo will always be 1 and qhi will always be equal to the length of the query. If the match is on the reverse strand, qhi will be 1 and qlo will be equal to length of the query.

The new qilo, qihi, tilo, and tihi userfields will contain the coordinates of the alignment ignoring terminal gaps (like qlo, qhi, tlo and thi was previously).
