### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by jtremblay** [torognes/vsearch#555]
When I try to compile on a centos7 system I get the following error:
```
dynlibs.cc:76:29: error: expected initializer before « OF »
 gzFile ZEXPORT (*gzdopen_p) OF((int, const char *));
                             ^~
dynlibs.cc:77:26: error: expected initializer before « OF »
 int ZEXPORT (*gzclose_p) OF((gzFile));
                          ^~
dynlibs.cc:78:25: error: expected initializer before « OF »
 int ZEXPORT (*gzread_p) OF((gzFile, void *, unsigned));
                         ^~

```
I've tried with gcc 8.4.0  and gcc 12. Any hint? 
Cheers,

**Comment by torognes** [comment]
The `OF` macro is defined in `zconf.h` which is part of the `zlib` development package. It is found in the package `zlib1g-dev` on Debian/Ubuntu and `zlib-devel` on Fedora (and Red Hat) linux. The [zlib](https://www.zlib.net) package enables decompression of `.gz` files. The macro is probably not needed, but was used for compatibility with really old compilers.

Did you build with autoconf and automake etc as described in the README?

Please see the README, the Dockerfile and the files in the `dockerfiles` folder for precise build descriptions.
