### ISSUE TITLE
USEARCH wants to go open-source?

### ISSUE THREAD

**Issue by cjfields** [torognes/vsearch#559]
Not really a bug report, but I noticed when looking up documentation on UNOISE that R. Edgar seems to want to make USEARCH open-source (see the added notice):

https://www.drive5.com/usearch/

(snapshot in case it disappears)

<img width="854" alt="image" src="https://github.com/torognes/vsearch/assets/49265/de383405-fbfa-4cc3-8ef6-a86e41cdc67e">

Is there any interest from the vsearch developers or community in this?

**Comment by torognes** [comment]
Thank you. I was not aware of this. It will be interesting to see what happens.

**Comment by frederic-mahe** [comment]
I saw that last December, but I was not sure what to think of it. Usearch is widely used, and it would be a good news for replicability if that important piece of software were to go open source.

Finding people willing to put in the time necessary to learn that new code base, to maintain it, and to extend it might be difficult though. Of course, it depends on the initial state of the code, and on the experience of the person doing the job, but it certainly requires a high level of motivation.

In the meantime, I think work on `vsearch` will continue as usual:)

@cjfields Thank you for bringing that to our attention. I am going to close the issue for now, but feel free to continue the conversation if there are new developments.

**Comment by torognes** [comment]
USEARCH 12 is now available here: https://github.com/rcedgar/usearch12
