### ISSUE TITLE
vsearch-2.29.0-linux-x86_64-static segmentation fault

### ISSUE THREAD

**Issue by slw287r** [torognes/vsearch#574]
The static build for Linux x86-64 goes segfault on my system

```
$ ./vsearch --help
vsearch v2.29.0_linux_x86_64, 187.4GB RAM, 64 cores
https://github.com/torognes/vsearch

Segmentation fault

$ uname -a
Linux hpc 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
% ./vsearch --help
vsearch v2.29.0_linux_x86_64, 377.3GB RAM, 96 cores
https://github.com/torognes/vsearch

zsh: segmentation fault (core dumped)  ./vsearch --help

% uname -a
Linux box 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Please consider fixing it. Thanks.

**Comment by torognes** [comment]
Thanks for reporting this issue!

The static builds are a bit difficult to get right. It seems to work on Debian:Stable, but I see there are problems on other distributions.

Which Linux distribution are you using?

**Comment by slw287r** [comment]
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708

**Comment by torognes** [comment]
I assume you are aware that CentOS 7 is very old and reached its end of life on June 30th, 2024. It is not officially supported anymore and may have security problems.

I have not succeeded in building a static binary for CentOS 7. However, I have made an ordinary binary using RedHat's UBI 7 docker image. I seems to run on CentOS 7. I think it should work for you.

You'll find it named `vsearch-2.29.0-linux-x86_64-ubi7.tar.gz` in the release.

https://github.com/torognes/vsearch/releases/download/v2.29.0/vsearch-2.29.0-linux-x86_64-ubi7.tar.gz

**Comment by torognes** [comment]
I have now deleted the static binary for Linux/x86_64.

**Comment by frederic-mahe** [comment]
I am closing that issue. I made a note to revisit that topic for the next `vsearch` release.
