### ISSUE TITLE
Segmentation fault (core dumped) with --cluster_unoise

### ISSUE THREAD

**Issue by LukaLmelias** [torognes/vsearch#583]
Hi,

I run into `Segmentation fault (core dumped)` when running `--cluster_unoise` command (v2.29.1). Error message from logging is:  `ERROR - Command failed with return code -11`

This error seems to occur only when `--minsize` is greater than the number of sequences in the file to be denoised.

Many thanks in advance for your help on how to handle this.

**Comment by frederic-mahe** [comment]
@LukaLmelias thanks for reporting this bug.

Indeed, there is an issue when the list of clusters is empty. This is a bug I've introduced last June while working on vsearch 2.29, sorry about that. I've pushed a fix to the main branch (https://github.com/torognes/vsearch/commit/49d7ff2e2a6bc61b231340d5ed918852d18fdfb9), and I've added a regression test to our test-suite.

**Comment by LukaLmelias** [comment]
Thank you for the speedy response!

Yep now it works, feel free to close this issue.

**Comment by torognes** [comment]
Fixed in vsearch version 2.29.2 just released.

https://github.com/torognes/vsearch/releases/tag/v2.29.2
