### ISSUE TITLE
same OTUs identifiers for different samples

### ISSUE THREAD

**Issue by ksc289** [torognes/vsearch#585]
Good morning everyone :) 
I am doing metabarcoding for the first time and I have the following question:

Can I use vsearch to cluster different samples at the same time and have unique otus identifiers appear for all the samples?
Context: I have about 50 different samples and I have clustered them separately with vsearch. The thing is that the otus I get in each sample do not match each other, that is, otus 1 in sample A is not the same otus 1 that appears in sample B, C...

I have read the vsearch documentation and I have come to the conclusion that I can do the following:
1. concatenate all the fasta files of the 50 samples.
2. cluster at 97% with the following command:
vsearch --cluster_fast all_samples.fasta \
        --id 0.97 \
        --centroids centroids.fasta \
        --uc clusters.uc \
        --relabel OTU_ \
        --sizeout

3. Assign the otus to the original samples:
vsearch --usearch_global muestra1.fasta \
        --db centroids.fasta \
        --id 0.97 \
        --otutabout tabla_OTUs.txt

Do you think this will work? What will happen to the otus that are not repeated between samples?

Thank you very much in advance :)

**Comment by frederic-mahe** [comment]
I think the minimal example below does what you want:
- create two fasta files (SAMPLE1 and SAMPLE2),
- use `vsearch --fastx_filter` to add a sample attribute to each sequence in each file `;sample=sampleID`,
- concatenate the samples,
- clusterize with `vsearch --cluster_fast`,
- use the option `--otutabout` to get an occurrence table

```sh
SAMPLE1=$(mktemp)
SAMPLE2=$(mktemp)
printf ">s1\nA\n" | \
    vsearch \
        --fastx_filter - \
        --sample "sample1" \
        --quiet \
        --fastaout ${SAMPLE1}
printf ">s1\nA\n" | \
    vsearch \
        --fastx_filter - \
        --sample "sample2" \
        --quiet \
        --fastaout ${SAMPLE2}

cat ${SAMPLE1} ${SAMPLE2} | \
    vsearch \
        --cluster_fast - \
        --minseqlength 1 \
        --id 0.97 \
        --relabel OTU_ \
        --sizeout \
        --quiet \
        --otutabout -

rm ${SAMPLE1} ${SAMPLE2}
```

You obtain a table indicating in which samples each OTU occurs:

```
#OTU ID	sample1	sample2
OTU_1	1	1
```

**Comment by ksc289** [comment]
Good morning Frederic,
Thank you very much for your reply. I have adapted the code you gave me to my samples, but basically I have done the following:
- For all the samples I have used the following command:
`vsearch --fastx_filter sample_x.fasta --fastaout C_tagged.fasta --sample sampleX`

-Then, concatenate all the samples with cat into a single file.
`vsearch --cluster_fast all_tagged_samples.fasta --minseqlength 1 --id 0.97 --relabel OTU_ --sizeout --quiet --otutabout otu_table.txt`

I got a table like this:
![image](https://github.com/user-attachments/assets/e64844c1-34ce-46a0-b96e-7a773a222832)

I understand that the numbers that appear in the sample are the number of reads that correspond to a given otus, right?

Thanks again :)

**Comment by frederic-mahe** [comment]
hello @ksc289 , your workflow seems correct to me.

> -Then, concatenate all the samples with cat into a single file.
vsearch --cluster_fast all_tagged_samples.fasta --minseqlength 1 --id 0.97 --relabel OTU_ --sizeout --quiet --otutabout otu_table.txt

`--cluster_fast` can produce several output files simultaneously. If need be, you can combine `--otutabout` with other outputs such as `--uc`, `--centroids`, etc.

> I understand that the numbers that appear in the sample are the number of reads that correspond to a given otus, right?

Yes, this is correct, each cell represents the number of reads from that OTU in that sample. The sum for each column should be equal to the number of reads in the corresponding sample. Note that you can use `--sizein` during clustering if the sequences in your samples already have abundance values (i.e. are already dereplicated).

Also, the column separator in `--otutabout` is a tabulation. In your screenshot the space in `#OTU ID` is interpreted as a column separator, which is not correct and offsets all your occurrence values by one column.

**Comment by frederic-mahe** [comment]
I am closing this issue. Feel free to re-open if need be.
