### ISSUE TITLE
cluster nucleotide sequences with identity=1 but ignoring N

### ISSUE THREAD

**Issue by sralchemab** [torognes/vsearch#586]
Dear all,

I'm trying to perform clustering on a FastA file by sequence length and perfect identity but ignoring Ns (meaning that two sequences of the same length that differ only in positions with Ns should be consider identical).

Is there a way to achieve this using `vsearch`?

I tried running all combinations of `--cluster_fast` / `--cluster_size` and `iddef` from 0 to 4 like below:

```shell
for METHOD in fast size
do
    for IDDEF in 0 1 2 3 4
    do
        echo $(date)" ${METHOD}, iddef ${IDDEF}"
        vsearch \
            --strand plus --qmask none --id 1 \
            --iddef ${IDDEF} \
            --cluster_${METHOD} input.fasta \
            --uc output.${METHOD}.iddef${IDDEF}.uc \
            > output.${METHOD}.iddef${IDDEF}.log 2>&1
    done
done
echo $(date)" Done"
```

I couldn't achieve my goal with any of these combinations.

Furthermore, because all combinations produce clusters with sequences of varying length (which is technically correct when a sequence is longer than another but the shorter is comprised within the longer), I tried manually splitting the resulting clusters by sequence length, but I was still having issues. This time, sequences with mismatches (non Ns) have been clustered together, which shouldn't be happening for `--id 1`, am I right?

I would appreciate any help on the matter.

Kind regards,
Santiago

**Comment by frederic-mahe** [comment]
hello @sralchemab 

If I understand your goal correctly, the minimal example below groups identical sequences of the same length, ignoring Ns. This does not seem to be different from your code, but it works:

```sh
printf ">s1\nA\n>s2\nN\n" | \
    vsearch \
        --cluster_fast - \
        --minseqlength 1 \
        --qmask none \
        --iddef 1 \
        --id 1.0 \
        --quiet \
        --uc -
```

It returns only one cluster, as expected:

```
S	0	1	*	*	*	*	*	s1	*
H	0	1	100.0	+	0	0	=	s2	s1
C	0	2	*	*	*	*	*	s1	*
```

Additional tests with the same clustering parameters (see https://github.com/frederic-mahe/vsearch-tests/commit/857a4bcc1078ac546b81ad932dae62adfe671669) show no unexpected behavior: sequences with different lengths are not grouped; sequences with hard mismatches (different nucleotides) are not grouped; the position of the soft mismatch (N) does not matter; the sequence with the soft mismatch can be the cluster seed or a hit (order does not matter).

> Furthermore, because all combinations produce clusters with sequences of varying length (which is technically correct when a sequence is longer than another but the shorter is comprised within the longer)

That should not happen with `--iddef 1`. In the example below, `sequence2` is a substring of `sequence1`, yet it is not grouped with `sequence1`, as expected with `--iddef 1 --id 1.0`:
```sh
printf ">s1\nAA\n>s2\nA\n" | \
    vsearch \
        --cluster_fast - \
        --minseqlength 1 \
        --qmask none \
        --iddef 1 \
        --id 1.0 \
        --quiet \
        --uc -
```
Two clusters, as expected:
```
S	0	2	*	*	*	*	*	s1	*
S	1	1	*	*	*	*	*	s2	*
C	0	1	*	*	*	*	*	s1	*
C	1	1	*	*	*	*	*	s2	*
```

If you obtain a different result, please indicate which version of `vsearch` you are using.

> sequences with mismatches (non Ns) have been clustered together, which shouldn't be happening for --id 1, am I right?

It can happen for certain definitions of similarity, for example if the mismatches are in 5' or 3' positions. With `--iddef 1 --id 1.0`, sequences must have the same length and be strictly similar, with similarity defined as such:

> When computing the amount of similarity by counting matches and mismatches after alignment, ambiguous nucleotide symbols will count as matching to other symbols if they have at least one of the nucleotides (ACGTU) they may represent in common. For example: W will match A and T, but also any of MRVHDN.

**Comment by frederic-mahe** [comment]
I am closing this issue. Feel free to re-open if need be.
