### ISSUE TITLE
Sequence masking

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#6]

**Comment by frederic-mahe** [comment]
@torognes I've implemented a few DUST masking tests I've found in [Morgulis et al. 2006](https://kodomo.fbb.msu.ru/FBB/year_10/ppt/DUST.pdf):

> Morgulis, A., Gertz, E. M., Schäffer, A. A., & Agarwala, R. (2006). A fast and symmetric DUST implementation to mask low-complexity DNA sequences. Journal of computational biology, 13(5), 1028-1040.

Tests in bash are available here (see https://github.com/frederic-mahe/vsearch-tests/blob/b52115b5e053e9ee7ec5fa876eef40ad08043843/scripts/fixed_bugs.sh#L142).

I've noticed that vsearch's DUST yields results that can differ a bit from blast's DUST and SDUST results as reported in the paper. Nothing major: a slight offset, and a lower sensitivity for short low-complexity regions. It's there if you want to look at it.

If you think of masking corner-cases I should test, please feel free to send them to me.
