### ISSUE TITLE
Single Makefile, Autotools and smaller repo

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#60]
We should probably settle on one Makefile instead of four to avoid confusion.

A user packaging vsearch for debian wrote:

"At the moment (v1.0.7) VSearch is somewhat awkward in that you need to choose the
compression mode of the input files at compile time.
I'm sure they'll sort this at some point, but for now we have to compile the
whole thing three times."

Source: https://ftp-master.debian.org/new/vsearch_1.0.7+dfsg-1.html

**Comment by frederic-mahe** [comment]
That's great! Both my computers run on Debian. They also mention that we could factorize a little bit our test data sets. It is true that cloning our git repository takes a long time the first time, even on a fast internet connection.

**Comment by torognes** [comment]
Agreed.

BTW, they also made a package for swarm!

https://ftp-master.debian.org//new/swarm-cluster_1.2.19+dfsg-1.html

**Comment by torognes** [comment]
The size of the repo should be reduced. Perhaps all binaries could be removed from the bin folder, at least the non-current ones. Binaries could be distributed in as part of the release in GitHub.

**Comment by torognes** [comment]
Adapted for autotools build system with single makefile in v1.3.0 in summer branch.

**Comment by colinbrislawn** [comment]
> The size of the repo should be reduced.

For vsearch, most of the size comes from `data`.
```
$ du * -sh
26K	autogen.sh
26K	configure.ac
378M	data
130K	eval
122K	LICENSE_GNU_GPL3.txt
26K	LICENSE.txt
26K	Makefile.am
221K	man
98K	README.md
3.0M	src
391K	test
```
If you are trying to keep size down, perhaps you could host a separate git repo for test data sets?

Github is even launching [a platform for extremely large data sets](https://github.com/blog/1986-announcing-git-large-file-storage-lfs), if the need were to arise.

**Comment by torognes** [comment]
I agree, we should try to move the large datafiles to a separate repo. I will look into it.

**Comment by torognes** [comment]
I've made a separate vsearch-data repo now and copied the data files to that repo. I will soon delete them from the main vsearch repo and remove them from the history too.

**Comment by colinbrislawn** [comment]
:+1:

**Comment by torognes** [comment]
I've tried to remove all of the data and bin directories from the repo history now, but I seems I did not completely succeed. Will try to fix.

**Comment by torognes** [comment]
Seems like it is fixed now. The repo is down to about 4MB (from almost 400MB).
