### ISSUE TITLE
Dereplication: option to use hash values as sequence names

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#64]
During dereplication, strictly identical sequences are grouped and receive the name of the first sequence of the group. Arguably, one can consider that sequence names loose their meaning during dereplication. Therefore, it could be interesting to offer an option that would give more informative names to sequences.

One possibility is to rename sequences using their hash values. When doing so, a given sequence will always inherit the same name, and it guarantees (with a very high probability) that FASTA entries from different projects with identical names also have strictly identical sequences.

Commonly used hash functions are MD5 and SHA (sha1sum). Other hash functions could be used. The option could take the following form:
```
vsearch --derep_fulllength input.fasta --sizeout --hash_as_names sha1sum
```
(option name and hash functions could be different)

**Comment by torognes** [comment]
That's a good idea that should be easy to implement.

A related issue: The sortbysize and sortbylength commands support a `--relabel` option that will put a new label on each sequence. The new label contains a specified prefix followed by a number (1, 2, ...). The `--relabel` option could be extended to dereplication as well.

What about `--relabel_hash sha1` and `--relabel_hash md5`? It could be applied to sorting too, to be consistent.

I assume the MD5 or SHA hash function should be applied to the sequences as unwrapped text with all symbols in lower case.

**Comment by frederic-mahe** [comment]
Extending to sorting is a good idea. The new option `--relabel_hash sha1` should take into account the `--sizein` and `--sizeout` options. 

Yes, sequences should be submitted to hash functions unwrapped. I think all symbols are upper-cased internally by vsearch (except when soft masking is activated). So hashing should be done on upper-cased strings.

**Comment by frederic-mahe** [comment]
related to [issue 84](https://github.com/torognes/vsearch/issues/84).
