### ISSUE TITLE
Improve reading of FASTA files, including very long header lines

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#66]
Some NCBI databases in FASTA format contain long FASTA header lines with multiple entries separated by Ctrl-A characters (hex 0x01). VSEARCH currently does not accept Ctrl-A characters in FASTA headers, but aborts with a fatal error. These characters should probably be accepted.

**Comment by torognes** [comment]
See question on the VSEARCH Forum:
https://groups.google.com/forum/#!topic/vsearch-forum/EvrnxwylE10

The problem does not seem to really be about illegal characters in FASTA headers, but really about long FASTA headers.

**Comment by torognes** [comment]
This problem is temporarily fixed in VSEARCH 1.0.12. This version will accept FASTA header lines up to 1MB long. A fatal error will occur if a longer header line is detected. I think the longest header lines in the NCBI nt database is about 500kB.

A better and more permanent solution requires extensive changes to db.cc and query.cc to properly handle FASTA header lines of virtually unlimited length in a more elegant way. Ideally, reading FASTA files should also be parallelised. Also, much of the common code in query.cc and db.cc should be refactored.

**Comment by torognes** [comment]
VSEARCH 1.0.13 increases the allowed line length to 4MB.

**Comment by torognes** [comment]
The problem has been resolved in the summer branch, version 1.2.13 and later.

**Comment by dturaev** [comment]
Reading in the nr-database for an exact search, vsearch stops at 99% with the message "Fatal error: illegal character '-' on line 579257666 in fasta file"
