### ISSUE TITLE
Ambiguity in consensus alignment

### ISSUE THREAD

**Issue by bingo11** [torognes/vsearch#67]
Not sure whether there is an option to modify the consensus behavior but it seems that, in 
cluster-fast, the reported consensus is chimeric. 
 
Is the issue can be reproduced using the following toy example (seq 2. aligns with seq 1 in reverse strand):

>1
ATGATCGTGTGATCGTGTAGCTGNNNNNNNNNNTGCTGTAGCTGTGTAGCTGTAAAATGTGACTGTGCTGTAGCTG
>2
ATGTAGTGTGATCGTGTGATCGTGTAGCTGTGCAGCTACAGCACAGTCACATTTTACAGCTACACAGCTACAGCA

The expected alignment should be:

>1
ATGATCGTGTGATCGTGTAGCTGNNNNNNNNNNTGCTGTAGCTGTGTAGCTGTAAAATGTGACTGTGCTGTAGCTG--------------------------------
>2
---------------------------------TGCTGTAGCTGTGTAGCTGTAAAATGTGACTGTGCTGTAGCTGCACAGCTACACGATCACACGATCACACTACAT

The reported alignment is:

>*1
ATGATCGTGTGATCGTGTAGCTGNNNNNNNNNNTGCTGTAGCTGTGTAGCTGTAAAATGTGACTGTGCTGTAGCTG--------------------------------
---------------------------------ATGTAGTGTGATCGTGTGATCGTGTAGCTGTGCAGCTACAGCACAGTCACATTTTACAGCTACACAGCTACAGCA
ATGATCGTGTGATCGTGTAGCTGAAAAAAAAAAAGCTAGAGCGATCGAGCGATAAAATAGCACTGCACCGAAACCACAGTCACATTTTACAGCTACACAGCTACAGCA

Granted, the strand of the sequences is maintained but shouldn't one of them be reverse and the consensus adjusted to report the correct alignement?

All the best,

Bing

**Comment by torognes** [comment]
Thanks for reporting this bug. It seems like hits on the reverse strand are incorrectly handled in the multiple sequence alignment and consensus sequence code. Sorry for the inconvenience. I will look into this problem very soon.

**Comment by bingo11** [comment]
Thanks for the quick response! Please let me know if I can help in any way.

**Comment by torognes** [comment]
This problem should be fixed in VSEARCH version 1.0.14.
