### ISSUE TITLE
adopt semantic versioning

### ISSUE THREAD

**Issue by nhoffman** [torognes/vsearch#68]
This is a great project - I am in the process of incorporating it into research pipelines, and at some point will consider adding it to pipleines that we use for production clinical assays. It would be extremely helpful to adopt some sort of semantic versioning to distinguish bugfix releases from those that change the API.   

There are obviously lots of ways to implement a semantic versioning system (http://en.wikipedia.org/wiki/Software_versioning). I don't have a strong opinion on what variant is used, but the primary objective should be to communicate when it is (probably) safe to use the new release without (significant) revalidation vs when upstream or downstream components will require modification. 

I believe that vsearch is important software that will become a core dependency for many projects (as usearch is now) - I suggest that meaningful version numbering would help facilitate this.

Thanks for considering,
Noah

**Comment by frederic-mahe** [comment]
Thanks for your suggestion Noah,

I was reading on the topic of semantic versioning recently (http://semver.org/) and it seems very reasonable to adopt a predictable versioning system.

However, it seems to me that there are changes that are difficult to communicate through the numbering system only. For example, if a default value changes, the user interface is not modified but results will be different. We can stick to a versioning system, but ultimately users will have to read the version history to decide whether or not they can use the new release.

**Comment by torognes** [comment]
I like the idea and intend to follow it.

**Comment by frederic-mahe** [comment]
I've added a milestone in the change log to indicate when we started to follow semantic versioning. Feel free to change it if you don't like it. I think we can close that issue now.
