### ISSUE TITLE
Integrate patches from Debian

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#72]

**Comment by frederic-mahe** [comment]
I've integrated the Debian modifications regarding the man page. The problem is apparently coming from the `--option` notation. The dashes need to be escaped `\-\-option` to avoid some unicode issues when copy-pasting snippets from the man page.

**Comment by torognes** [comment]
The patches are listed here:

http://anonscm.debian.org/viewvc/debian-med/trunk/packages/vsearch/trunk/debian/patches/

**Comment by torognes** [comment]
I've integrated the patches to the code. Only changes to the Makefile(s) remain.

**Comment by frederic-mahe** [comment]
Hi Torbjørn, you've forgot to update the version history in the manpage. I'll let you do it.

**Comment by torognes** [comment]
Eh, I always forget something... I'll include it in the next release later today. Thanks for the reminder.
