### ISSUE TITLE
cluster input sequences shorter than 32nt

### ISSUE THREAD

**Issue by avilella** [torognes/vsearch#74]
Hi @torognes ,

I am runnning vsearch cluster on a set of 10000 DNA sequences, some of which are shorter than 32 nucleotides. The clustering seems to behave nicely and consistently: if I run it over an `id` parameter sweep of 0.99 to 0.50, it seems to reach a stable level of 280 clusters for `id=90`:

```
wc -l test.fasta
20000 test.fasta

for id in `seq -w 99 -1 50`; do echo id=$id; /opt/foo/bar/thirdparty/vsearch-1.0.10/bin/vsearch-1.0.10-linux-x86_64 --clusters foo_id.$id.fasta_n --cluster_fast test.fasta --id 0.$id --centroids bar_id.$id; done

for id in `seq -w 99 -1 50`; do echo id=$id; ls -1 foo_id.$id.fasta_n* | wc -l; done | head -n 20
id=99
393
id=98
386
id=97
350
id=96
299
id=95
295
id=94
292
id=93
287
id=92
287
id=91
287
id=90
286

```

About three quarters of my input sequences are shorter than 32, and I would like to be able to run vsearch cluster and have them included in the final set of cluster files:

```
wc -l foo_id.90*fasta_n* | grep total
  5684 total
```

Is there any way to include input sequences shorter than 32 into the final results? My minimum right now is 16bp, maybe 15-14 could also be useful.

Thanks,

@avilella

**Comment by torognes** [comment]
Hi @avilella, if you use the option "--minseqlength 1", all sequences will be included.

**Comment by avilella** [comment]
wicked, thanks!
