### ISSUE TITLE
cluster_fast and msa output for each of the clusters

### ISSUE THREAD

**Issue by avilella** [torognes/vsearch#75]
Hi @torognes ,

What is the best way to do both clustering and msa of each cluster with vsearch?

I am currently running the clustering step like this (perl wrapper):
```
$cmd = "$vsearch_exe --minseqlength 1 --clusters $prefix.$id.$suffix --cluster_fast $inputfile --id $id --centroids vsearch_id.$id";
```

What I would like to obtain, is the `--msaout` for each of the clusters that come out of the clustering step.

Currently, I can do it one by one with a command line like this:

```
vsearch-1.0.10/bin/vsearch-1.0.10-linux-x86_64 --msaout msa.0.90 --cluster_fast foo.0.90.fasta_n257 --id 0.90
vsearch v1.0.10_linux_x86_64, 126.0GB RAM, 48 cores
https://github.com/torognes/vsearch

Reading file foo.0.90.fasta_n257 100%  
166 nt in 5 seqs, min 32, max 34, avg 33
Indexing sequences 100% 
Masking 100%
Sorting by length 100%
Counting unique k-mers 100% 
Clustering 100%  
Writing clusters 100% 
Clusters: 1 Size min 5, max 5, avg 5.0
Singletons: 0, 0.0% of seqs, 0.0% of clusters
Multiple alignments 100% 
```

What is the best way to obtain the msa file for each of the clusters from the cluster_fast step?

Thanks,

@avilella .

**Comment by torognes** [comment]
Hi @avilella,

You can it all in one step, like this:

`$cmd = "$vsearch_exe --minseqlength 1 --clusters $prefix.$id.$suffix --cluster_fast $inputfile --id $id --centroids vsearch_id.$id --msaout msa.fsa";`

All the multiple sequence alignments will be written to one specified file (here: msa.fsa). There is a blank line between the clusters. The first sequence in each cluster, the centroid sequence, is indicated with a star (asterisk) at the beginning of the header. All MSAs also include a consensus sequence at the end.

- Torbjørn

**Comment by avilella** [comment]
I see. And that would be equivalent to:

1. Running without `--msaout`:

$cmd = "$vsearch_exe --minseqlength 1 --clusters $prefix.$id.$suffix
--cluster_fast $inputfile --id $id --centroids vsearch_id.$id";

2. For each of the cluster output files, then run with same `--id $id` and
with `--msaout file.msa`:

$cmd = "$vsearch_exe --minseqlength 1 --msaout $file.msa --cluster_fast
$file --id $id";

Would the results be equivalent for the same value of `--id $id`?

Cheers,

Albert.

**Comment by torognes** [comment]
yes, it should be equivalent.
