### ISSUE TITLE
Chimera detection progress indicator

### ISSUE THREAD

**Issue by frederic-mahe** [torognes/vsearch#78]
Hi Torbjørn,

when using the new `vsearch 1.1.3` on the big dataset, there seems to be a problem with the chimera detection (progress indicator is going crazy):
```
Reading file neotropical_soil_175_samples_representatives.fas 100%  
8789864140 nt in 23735051 seqs, min 32, max 582, avg 370
Indexing sequences 100%  
Sorting by abundance 100%
Counting unique k-mers 100%  
Detecting chimeras 344%
```
I used the following options:
```
"${VSEARCH}" --uchime_denovo "${QUERIES}" \
    --fasta_width 0 \
    --chimeras "${CHIMERAS}" \
    --uchimeout "${UCHIME}"
```
It could be a bug, or a dataset riddled with chimeras?

**Comment by torognes** [comment]
This was exactly the bug I thought I had fixed in 1.1.3, but I cannot have tested it properly. Are you sure this is not 1.1.2?

**Comment by frederic-mahe** [comment]
I think I am using v1.1.3, but for some reason, I cannot be sure. I double-checked the targeted version and relaunched the computation, just in case. We have to wait for the computation to progress.

**Comment by frederic-mahe** [comment]
Everything seems normal now. It was a false alert. Sorry!
