### ISSUE TITLE
Generating cluster files

### ISSUE THREAD

**Issue by mirjalil** [torognes/vsearch#80]
So when I generate clusters, I see thousands of files generated where it becomes tedious to merge these files and assign cluster IDs to each sequence! 

I think it would be very help ful if instead of generating thousands files, the program outputs one file that contains sequence identifier (in the same order as the input sequence files)

For example like this output (sequence identifier + cluster number)
>M02127_29_000000000-A9TRU_1_1106_3986_10247     1
>M02127_29_000000000-A9TRU_1_1101_10456_3701    101
>M02127_29_000000000-A9TRU_1_2113_20500_6535    23
>M02127_29_000000000-A9TRU_1_2112_16631_24644  1
>M02127_29_000000000-A9TRU_1_2101_15799_17407  6
>M02127_29_000000000-A9TRU_1_1101_15526_22103  4
>M02127_29_000000000-A9TRU_1_1101_11162_16368  7
>M02127_29_000000000-A9TRU_1_1106_15675_3202    8
>M02127_29_000000000-A9TRU_1_2111_12556_16904  9
>M02127_29_000000000-A9TRU_1_1102_9265_16831  89

**Comment by frederic-mahe** [comment]
Hi,

It seems you are using the `--clusters` option. You should try the options `--centroids` or `--uc` instead.

**Comment by mirjalil** [comment]
I tried both --clusters and --centroids, but --centroids only gives the centroids of each cluster! And the output of --uc is not understandable!

Therefore, I wrote a python script to organize the clusters in a new file! I can share it via this repository so that other people can also use it, if you think that's something more people may need!

**Comment by torognes** [comment]
If you use the --uc option and look at the lines starting with H and S, you will have the cluster number in the second column and the sequence id in the ninth column. See the usearch documentation for details: http://drive5.com/usearch/manual/opt_uc.html

**Comment by frederic-mahe** [comment]
You can get the information you are looking for from the `--uc` file quite easily:
```
awk '$1 == "H" || $1 == "S" {print $9, $2}' file.uc
```
Note that for several reasons we cannot force results in the same order than the input order: one reason being that the uclust algorithm sorts input sequences by decreasing length before clustering. Multi-threading also is a source of variability in output order.

**Comment by mirjalil** [comment]
Thanks! That is useful!
