### ISSUE TITLE
Space in a header line

### ISSUE THREAD

**Issue by annaship** [torognes/vsearch#81]
Dear VSEARCH developers,

Thank you for developing VSEARCH. We were looking for a good replacement to usearch for a long time!

My problem now is that in Illumina fasta files there are spaces in a header line and .uc file made by vsearch uses only the part in front of the space. So my names file and .uc file have different headers as a result.

Do you think you will change that behavior to be the same as usearch's?

**Comment by frederic-mahe** [comment]
Dear @annaship,

maybe the `--notrunclabels` would solve your problem?
```
--notrunclabels
        Do not truncate sequence labels at first space, use the full header in output files.
```

**Comment by annaship** [comment]
Thank you
