### ISSUE TITLE
--relabel does not work consistently

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#84]
Good afternoon,

The option `--relabel` does not consistently relabel reads in the output files.
Given the following file called `toy.fna`:
```
>read_1;size=2;
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATT
>read_2;size=1;
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTT
>read_3;size=1;
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTT
>read_4;size=3;
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATT
```

Dereplication DOES NOT relabel:
`vsearch --derep_fulllength toy.fna --sizein --sizeout --output toy.derep.fna --relabel test_`
Sorting DOES relabel:
`vsearch --sortbysize toy.fna --sizein --sizeout --output toy.sort.fna --relabel test_`
Clustering DOES NOT relabel:
`vsearch --cluster_smallmem toy.fna --id 0.70 --centroids toy.cluster.fna --relabel test_`
Chimera checking DOES NOT relabel:
`vsearch --uchime_denovo toy.fna --nonchimeras toy.chimeras.fna --relabel test_`

I would appreciate additional support for `--relabel`, especially after OTU clustering so that each `read_` can become `OTU_`.

Thanks!

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn,

`--relabel` is for the moment only available for sorting. Extending the support to clustering would impact several output files, with different formats. I'll let Torbjørn judged if it is doable.

For dereplication, we had in mind to offer an option to rename the sequences using hash values. Maybe `--relabel` could be added to the list?

**Comment by colinbrislawn** [comment]
Hello there,

Thanks for providing an update on this issue.

In the last several weeks, the developer of usearch has added support for `-relabel` to the `cluster_otus` command of the [uparse pipeline](http://drive5.com/usearch/manual/cmd_cluster_smallmem.html). (This is interesting! This step was originally done using the independent python script `fasta_number.py`. Once vsearch added this native feature, Edgar added it to his software as well. Your work is being noticed!) 

When the information contained in a file significantly changes, say during dereplication or during clustering, I think having the option to `--relable` your new results is powerful; it lets your clearly state in each fasta header that that read means something different. 

Thank you both for your excellent software!

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn,

> When the information contained in a file significantly changes, say during dereplication or during clustering, I think having the option to `--relabel` your new results is powerful; it lets your clearly state in each fasta header that that read means something different. 

Exactly, that's why in my own analyses I drop the old read names and replace them with a more informative name derived from the sequence itself: hash value, always the same for a given sequence, (almost) always different for different sequences.

You are right, extending the possibility to use `--relabel` to dereplication and other functions, like usearch recently did, would be useful and more coherent.

Thanks,

PS: I took the liberty to correct a typo in your comment (relable -> relabel).

**Comment by colinbrislawn** [comment]
Thank you @frederic-mahe! I look forward to this new feature.

Thanks for fixing my typo as well. I'm quite bad at spelling.

**Comment by torognes** [comment]
Hi @colinbrislawn, we'll try to support relabel on more commands in the future. There are a lot of suggestions now for things to be done. First of all we need to finish our manuscript. I will probably have more time in the fall than in the spring (no teaching), so I hope to get some programming done then.

Just a note on usearch and relabel: relabel was an option to the sortbysize and sortbylength in usearch 7. It was not new to vsearch.

http://www.drive5.com/usearch/manual/cmd_sortbysize.html
http://www.drive5.com/usearch/manual/cmd_sortbylength.html

**Comment by torognes** [comment]
Ordinary relabelling as well as relabelling with a sha1 and md5 digest/hash added in the summer branch, for both sorting and dereplication. Will try to add it to clustering too.

**Comment by torognes** [comment]
Added for nonchimeras output from chimera detection, and for centroids output for clustering. In summer branch.

**Comment by colinbrislawn** [comment]
Thank you!
