### ISSUE TITLE
Vsearch needs a Galaxy wrapper

### ISSUE THREAD

**Issue by bgruening** [torognes/vsearch#88]
This issue is to let you know that the Galaxy community is trying to get this solved: https://github.com/galaxyproject/tools-iuc/tree/vsearch

**Comment by torognes** [comment]
Thanks!

**Comment by bgruening** [comment]
@torognes this is now committed https://github.com/galaxyproject/tools-iuc/tree/master/tools/vsearch
and part of the Galaxy ToolShed: https://toolshed.g2.bx.psu.edu/view/iuc/vsearch/

**Comment by frederic-mahe** [comment]
Thanks, vsearch's documentation has been updated.
