### ISSUE TITLE
Consensus output in clustering produces empty fasta sequences

### ISSUE THREAD

**Issue by cboursnell** [torognes/vsearch#89]
When using this option
` --consout FILENAME          output cluster consensus sequences to FASTA file`
the fasta file can contain a lot of empty sequences that have a header, but no bases. This is even when using a high `--id` like `0.95`. 
If no consensus can be found for whatever reason at least the centroid should be written out.
The number of blank sequences seems to depend on the definition of `id` used with the
` --iddef INT                 id definition, 0-4=CD-HIT,all,int,MBL,BLAST (2)`
option.
`1` seems to give the least and `3` gives the most blank lines

**Comment by torognes** [comment]
Thanks for reporting this problem. I will look into it soon. If you have a small dataset that will reproduce this error, I will appreciate if you could send it to me.

**Comment by torognes** [comment]
Another user also reported this problem and I have received sample data to reproduce the error.

**Comment by torognes** [comment]
I have investigated the issue and it seems to happen for instance in cases where there is one long centroid sequence and several shorter sequences that rarely overlap each other. The most common symbol will then be a gap symbol all over the alignment. This leads to a consensus containing only gap symbols, which will subsequently be removed. We are then left with an empty sequence. This seems to be correct according to the definition of the consensus sequence used.

We could change the behaviour to output the centroid sequence in this case, but I am not sure.

**Comment by torognes** [comment]
The consensus symbol in a column will be a gap symbol if at least half the sequences contain a gap in that column. Otherwise the consensus symbol will be the most common symbol of A, C, G or T in that column. If two symbols are equally common, the first of those symbol in alphabetical order will be chosen.

**Comment by torognes** [comment]
Note that consensus sequences are written both with the `--consout` and `--msaout` commands. Gaps are removed in the consensus sequences written by `--consout` but remain in the consensus sequences written by `--msaout`.

**Comment by frederic-mahe** [comment]
Our definition of the consensus seems to be the same than the one officially used by usearch: http://www.drive5.com/usearch/manual/consensus.html. I am not sure we should change anything here. When a multiple sequence alignment is gappy enough to yield an empty consensus, it would be ill-advised to use the seed in lieu of consensus. In fact, empty consensus sequences could be used to identify and discard dubious and problematic clusters.

> Note that consensus sequences are written both with the --consout and --msaout commands. Gaps are removed in the consensus sequences written by --consout but remain in the consensus sequences written by --msaout.

We should modify the documentation (in future vsearch releases) to reflect that. Right now, the documentation says "Columns containing a majority of gaps are skipped, except for terminal gaps." for both options. A sentence could be added to warn about gappy MSA leading to empty consensus.

I also created a wiki page summarizing the problem: https://github.com/torognes/vsearch/wiki/Clustering#why-is-my-consensus-sequence-empty
