### ISSUE TITLE
Dereplication based on prefixes of sequences

### ISSUE THREAD

**Issue by torognes** [torognes/vsearch#90]
Similar to derep_prefix in usearch.

http://www.drive5.com/usearch/manual/dereplication.html
http://www.drive5.com/usearch/manual/cmd_derep_prefix.html

**Comment by frederic-mahe** [comment]
Greg Caporaso suggested to use a [Trie](https://en.wikipedia.org/wiki/Trie). We investigated that data structure while working on swarm, and I also think it would be a suitable approach. The prefix dereplication process would then require the sequences to be sorted by decreasing length.

**Comment by wasade** [comment]
On biocore/scikit-bio#937, @gregcaporaso also suggested [marisa-trie](https://code.google.com/p/marisa-trie/) as an underlying library for scikit-bio (although if this happens, scikit-bio would interface via the Python/Cython [library](https://pypi.python.org/pypi/marisa-trie))

**Comment by torognes** [comment]
I have added the derep_prefix option in the "summer" branch of vsearch. It does not use a trie but a hash very similar to the one used for full length exact dereplication. It starts by sorting the sequences by length, shortest first. It then processes the sequences in order. If it does not find an exact match it will try with a prefix one symbol shorter until it finds a match or until the length of the prefix is equal to the shortest sequence. It uses a simple hash function and looks up any matches in the hash. I was unsure how fast it would be, but was surprised on how fast it was despite many lookups.

It ends up with the same number of sequences (clusters) as usearch's derep_prefix, but the clusters may be different. It is not clearly defined which cluster a short sequence should end up in if there are two longer sequences which share the same prefix. You'll end up with the same clusters and the same cluster representative (the longest sequence), but if you add up the abundances the total abundance might differ based on to which cluster you add the shorter sequences. Feedback on how this should be resolved is highly welcome!

I've tried to compare the run time of usearch and vsearch for prefix clustering. It depends a lot on the actual dataset, but here are some numbers:
vsearch on BioMarks dataset: 4 seconds on my MacBook Pro using 1 thread
usearch on BioMarks dataset: 10 minutes and 5 seconds on my MacBook Pro using several threads (150x slower than vsearch)

Currently running it on an EMP dataset - results will follow.

**Comment by wasade** [comment]
Ah, fantastic! cc'ing @josenavas and @ekopylova who may be interested in commenting on the derep.

**Comment by torognes** [comment]
It took 30 min and 23 seconds to prefix-dereplicate an EMP dataset with 18179981115 nt in 154896650 seqs (25GB data) running with 1 thread on a linux server with Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz cpus. It used about 44GB of memory. Ended up with 111231707 unique sequences, avg cluster 1.4 sequences, median 1, max 77. Unable to run usearch due to memory limit.

**Comment by josenavas** [comment]
Those numbers are really promising!

**Comment by ekopylova** [comment]
That's great! Another useful feature is the output .uc file (in addition to the de-replicated FASTA file) which can be used to expand the final OTU map.

**Comment by wasade** [comment]
Just to make sure I understand, the largest number of duplicated sequences
is 77? That seems a bit low, right?

**Comment by torognes** [comment]
@wasade , yes 77 is the largest number of duplicated sequences, i.e. 77 different length prefixes of the same sequence. This dataset was already dereplicated using exact full length sequences, so 77 is actually rather high considering the average sequence length of 117. It can be run with "sizein" and "sizeout" options to add up the abundance numbers for all sequences in the same cluster.

**Comment by frederic-mahe** [comment]
> It ends up with the same number of sequences (clusters) as usearch's derep_prefix, but the clusters may be different. It is not clearly defined which cluster a short sequence should end up in if there are two longer sequences which share the same prefix. You'll end up with the same clusters and the same cluster representative (the longest sequence), but if you add up the abundances the total abundance might differ based on to which cluster you add the shorter sequences. Feedback on how this should be resolved is highly welcome!

Regarding that problem, the safest bet is probably to link the short sequence to the most abundant matching sequence (if several matches). To achieve that, fasta entries could be sorted by increasing sequence length, then by decreasing abundance, and then by increasing alpha-numerical order to obtain a stable sorting order (like the sorting option does).

**Comment by josenavas** [comment]
:+1: to @frederic-mahe solution!

**Comment by frederic-mahe** [comment]
Hi @torognes,

if you use abundance values to break ties when performing prefix clustering, you might want to use the original abundance value of each sequence, not the updated abundance values (i.e. the cumulated abundance values of previously merged prefix sequences). It would reduce the snowballing effect.
