### ISSUE TITLE
I've made a homebrew package for vsearch

### ISSUE THREAD

**Issue by tseemann** [torognes/vsearch#93]
FYI - I've made a homebrew package for vsearch

https://github.com/Homebrew/homebrew-science/pull/2409

The main hacking was around the need for ../zlib and ../bzip2 which I had to ensure pointed at the Homebrew locations, but otherwise a clean compile.

**Comment by torognes** [comment]
Great, thanks!

**Comment by torognes** [comment]
I've added a not about it in the README.md.

**Comment by tseemann** [comment]
That is kind of you, thank you.
