### ISSUE TITLE
question about compile time optimizations

### ISSUE THREAD

**Issue by pescobar** [torognes/vsearch#96]
Hi,

while reviewing the makefile I have seen this line:

```
CXXFLAGS=-O3 -msse2 -mtune=core2 -Icityhash $(WARN) $(PROFILING)
```

I am not sure but I think those options will make the binary run in any cpu newer than core2 (core2 was released before 2010) but the binary won't take advantage of the features in modern cpus. 

Is there any reason why not switching this line to something like this one so the compiled binary uses all the features in the cpu where it's being compiled?

```
CXXFLAGS=-O3 -march=native -Icityhash $(WARN) $(PROFILING)
```

I am tempted to do this in my system but I wanted to ask before doing it in case there is any reason why this cannot be done and the mtune=core2 is mandatory.

If there in no reason against using "march=native" I would suggest to update the Makefile so it's possible to do "make release" to compile the generic binary optimized for core2 which would run in mostly any machine and the plain "make" which would compile with optimizations for the cpu where the compilation is being done.

does it makes sense what I suggest or am I missing something?
thanks for your help.

Pablo.

**Comment by torognes** [comment]
Hi @pescobar 
Thanks for your suggestion. There is a requirement for SSE2 in the alignment code, hence the -msse2 option. But otherwise I agree with you - it would be better to optimize or tune it for the cpu on the system it is compiled on. I will make the changes to the makefile in the next release that will probably be out in a week or two. You can safely make this change on your own system.

**Comment by torognes** [comment]
I have decided to keep the Makefile as it is. You can probably safely change the options as indicated on your own system, but the given Makefile is used to compile the distributed pre-compiled binaries and should work well on a wide range of systems.

**Comment by torognes** [comment]
I've made some changes to the configure.ac and src/Makefile.am in line with your suggestion in the "summer" branch. It now uses "-mtune=native" as well as "-msse2" and "-mssse3" for the appropriate files. It will then run on any machine with at least sse2, but will be tuned for the native machine. You may set "-march=native" for maximum performance, but then the binary may not run on older/other machines than it is compiled on.
