### ISSUE TITLE
option --minh ignored while using --uchime_denovo

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#98]
I have a small fasta file of clustered sequences on which I am running uchime_denovo. I don't think changing my ‑-minh has any effect on results.

Running with defaults:
```
> vsearch -uchime_denovo rep_set.fna \
> -strand plus -sizein -threads 16 ‑-minh 0.28 \
> -nonchimeras rep_set.point28.fna \
> --log rep_set.point28.log
vsearch v1.1.3_linux_x86_64, 62.8GB RAM, 48 cores
https://github.com/torognes/vsearch

Reading file rep_set.fna 100%  
5041537 nt in 19980 seqs, min 191, max 281, avg 252
Indexing sequences 100%  
Sorting by abundance 100%
Counting unique k-mers 100%  
Detecting chimeras 100%  
Found 15665 (78.4%) chimeras, 4304 (21.5%) non-chimeras,
and 11 (0.1%) suspicious candidates in 19980 sequences.
```

Running with much higher --minh:
```
vsearch -uchime_denovo rep_set.fna \
> -strand plus -sizein -threads 16 ‑-minh 2 \
> -nonchimeras rep_set.two.fna \
> --log rep_set.two.log
vsearch v1.1.3_linux_x86_64, 62.8GB RAM, 48 cores
https://github.com/torognes/vsearch

Reading file rep_set.fna 100%  
5041537 nt in 19980 seqs, min 191, max 281, avg 252
Indexing sequences 100%  
Sorting by abundance 100%
Counting unique k-mers 100%  
Detecting chimeras 100%  
Found 15665 (78.4%) chimeras, 4304 (21.5%) non-chimeras,
and 11 (0.1%) suspicious candidates in 19980 sequences.
```

Output files are identical:
```
> md5sum *fna
ca697b5e087901bbbf2509bedce31381  rep_set.fna
a918fca25985aa6fdf6b191107481930  rep_set.point28.fna
a918fca25985aa6fdf6b191107481930  rep_set.two.fna
```

Maybe an issue with these lines:
https://github.com/torognes/vsearch/blob/33c9583cb5ea9ae084c505426a50049e420a1234/src/chimera.cc#L740-L747

**Comment by colinbrislawn** [comment]
--uchime_denovo also appears to ignore the --sizein flag.

```
> vsearch -uchime_denovo rep_set.fna \
> -strand plus ‑-minh 0.28 \
> -nonchimeras rep_set.point28.nosizein.fna \
> --log rep_set.point28.nosizein.log
vsearch v1.1.3_linux_x86_64, 62.8GB RAM, 48 cores
https://github.com/torognes/vsearch

Reading file rep_set.fna 100%  
5041537 nt in 19980 seqs, min 191, max 281, avg 252
Indexing sequences 100%  
Sorting by abundance 100%
Counting unique k-mers 100%  
Detecting chimeras 100%  
Found 15665 (78.4%) chimeras, 4304 (21.5%) non-chimeras,
and 11 (0.1%) suspicious candidates in 19980 sequences.

>md5sum *fna
ca697b5e087901bbbf2509bedce31381  rep_set.fna
a918fca25985aa6fdf6b191107481930  rep_set.point28.fna
a918fca25985aa6fdf6b191107481930  rep_set.point28.nosizein.fna
a918fca25985aa6fdf6b191107481930  rep_set.two.fna
```

Maybe this is by design (it always uses size annotations), but I worry about this... 
I'll keep testing.

**Comment by frederic-mahe** [comment]
Hi @colinbrislawn, only values ranging from 0.0 to 1.0 included are accepted for `--minh`. Could you try again with `--minh 1.0`?

**Comment by colinbrislawn** [comment]
OK. `--minh 1` gives the same result at the default.

```
> vsearch -uchime_denovo rep_set.fna \
> -strand plus .-minh 1 \
> -nonchimeras rep_set.one.fna \
> --log rep_set.one.log
vsearch v1.1.3_linux_x86_64, 63.0GB RAM, 32 cores
https://github.com/torognes/vsearch

Reading file rep_set.fna 100%
5041537 nt in 19980 seqs, min 191, max 281, avg 252
Indexing sequences 100%
Sorting by abundance 100%
Counting unique k-mers 100%
Detecting chimeras 100%
Found 15665 (78.4%) chimeras, 4304 (21.5%) non-chimeras,
and 11 (0.1%) suspicious candidates in 19980 sequences.

> md5sum *fna
ca697b5e087901bbbf2509bedce31381  rep_set.fna
a918fca25985aa6fdf6b191107481930  rep_set.one.fna
a918fca25985aa6fdf6b191107481930  rep_set.point28.fna
```

**Comment by colinbrislawn** [comment]
Figured it out!

It looks like `--minh` must be a double, or it silently resets to the default. I wish it threw an error with a value over 1.0 or a integer was given.

This command works:
```
vsearch -uchime_denovo rep_set.fna \
-strand plus --minh 1.0 \
-nonchimeras rep_set.one.fna \
--log rep_set.one.log \
--uchimealns rep_set.one.aln
```

**Comment by frederic-mahe** [comment]
Thanks for reporting this. This is indeed a test that could be added to vsearch to guide users.

I am not sure what to add to the documentation to avoid confusion. Any idea?
> −−minh *real*
> Minimum score (h). Increasing this value tends to reduce the number of false positives and to decrease sensitivity. Default value is 0.28, and values ranging from 0.0 to 1.0 included are accepted.

**Comment by colinbrislawn** [comment]
Oh OK, that documentation looks great. I guess I did not read it well enough and note that all the examples are doubles, not integers. 

A safeguard against integers and out of bound numbers would be even better. A safe guard against people who don't read the documentation, like me, would be best :disappointed_relieved:

**Comment by frederic-mahe** [comment]
No problem. Documentation is one thing, I agree that having built-in safe guards would improve usability and would avoid frustration.

**Comment by torognes** [comment]
I've investigated the case, and vsearch does accept values larger than 1 for the minh option and the number may be an integer or real number. The problem has actually nothing to do with the minh option.

However, if you look closely, it seems that a special character (‑) that looks very similar to a dash or minus (-), appears in the command line in the example of @colinbrislawn with the minh option instead of a proper character. In a later comment the first character is replaced by a dot. These characters makes vsearch ignore this option since it does not start with a proper dash.

Other users have also reported similar problems due to characters that look like dashes but are not proper dashes.

I will try to detect this and report it as an error. Strings on the command line not recognized as part of an option could be detected and flagged.

**Comment by frederic-mahe** [comment]
Hi @torognes, it could come from the usage of `\-` in the man page. Debian maintainers requested that we use `\-` instead of `-` in our man pages. It converts dashes to another character in the PDF. Users might have copy-pasted the commands from the PDF and ended up with errors. For swarm, I use the following command when creating the PDF:
```
man -t <(sed -e 's/\\-/-/g' ./swarm.1) | ps2pdf -sPAPERSIZE=a4 - > swarm_manual.pdf
```

**Comment by torognes** [comment]
Check for extra non-option arguments added in "summer" branch.

**Comment by colinbrislawn** [comment]
Hello @torognes,

Thank you for identifying the issue with the dash like special character! I noticed that my vsearch log files were showing this different character, but was not sure why.

Although neither the ambiguous dash or the size of `--minh` are errors, extra checks to keep people like me from accidentally using them would be appreciated. 

Keep up the good work!
