### ISSUE TITLE
Test scripts

### ISSUE THREAD

**Issue by RonnySoak** [torognes/vsearch#99]
The shell scripts in the test folder use #!/bin/sh which directs to the dash on my system (Linux Mint 17), which produces an error when I run them.

> clusterf.sh v
clusterf.sh: 14: [: v: unexpected operator
clusterf.sh: 17: [: v: unexpected operator
You must specify u or v as first argument

If I change it to #!/bin/bash, the scripts run without a problem.

Should they run with the dash? Or was the bash intended?

**Comment by frederic-mahe** [comment]
Hi @RonnySoak ,

you are right, the shell scripts were intended for bash. I would like to write a new set of test scripts, and I will likely write them for bash. In a second time, I might try to remove "bashisms" to improve the portability of the scripts. In my experience, bash is so widely available that it should not be an issue to target it specifically.

@torognes, can you please change script's shebang lines in the new dev branch you are working on?

**Comment by torognes** [comment]
Fixed the shebang to point to bash in all scripts in the summer branch.
